### ISSUE TITLE
Storage location of claims may mine data

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#10]
We should make it clear that the storage location of claims may mine data or forward data so participants in the ecosystem should be wary of those business models. Systems that don't mine data may be able to use that feature as a competitive advantage. We should be clear that even though this system is privacy-enhancing, that it is not a panacea.

**Comment by David-Chadwick** [comment]
Why dont we recommend that users store their own claims locally?

**Comment by msporny** [comment]
> Why dont we recommend that users store their own claims locally?

It's not realistic to expect everyone to store their own claims locally. Some will store them w/ credential repositories, others will store them locally but want them backed up, etc.

I expect that, in time, a rating system will be created for credential repositories and those repositories will be rated on whether or not they mine your data, store things encrypted at rest, etc. That said, we may not want to make recommendations that will be overtaken by technology (like encrypting at rest).

**Comment by msporny** [comment]
This was handled with PR #39, closing this issue.
