### ISSUE TITLE
Will it be correct to use Verifiable Credentials standard for generic claims?

### ISSUE THREAD

**Issue by Drabiv** [w3c/vc-data-model#100]
MAIN QUESTION: Will it be correct to use VC standard to link digital signatures with signed data/files and with explicit explanation of the meaning of the signature for the signer at the time of signing, or VC standard is only for creating relatively simple credentials? 

Reading the examples in Verifiable Credentials specification (https://w3c.github.io/vc-data-model/) I see that the standard obviously is mainly meant to be used for credentials (driver's license, passport, proof of age, proof of citizenship, address, legal name, proof of educational attainment  – no surprise here, after all the group was recently renamed from Verifiable Claims to Verifiable Credentials).

The original name of the group "Verifiable Claims" lead me thinking that the standard can be used to create, sign, verify signatures and explicitly explain meaning of the signatures for any kind of claims. 

SUB-QUESTION 1: Can Verifiable Credential standard be used to create generic claims as provided in the  examples 1,2,3 ?

EXAMPLE 1, a claim that an entity represented by DID::Alice, has read the contract represented by URN:hash256-111, URL:http-111, fully understood the contract and agreed to adhere to it.  Alice's signature provided.

EXAMPLE  2, a claim that an entity represented by DID::Bob, has released the file URN:hash256-222, 
available to the public at URL:http-222 and to the best of his knowledge the file does not contain viruses. Bob's signature provided.

EXAMPLE  3, a claim that an entity represented by DID::Charley, supports the claim URN::hash256-333 made in Example 2 by Bob, and although did not check the content of the file released by Bob, himself supports Bob's claim that it is viruses free. Charley's signature provided. 

Note: in the example 3 the claim is made about the claim, not about the identity.
SUB-QUESTION 2: Is it possible to make claim about a claim using current VC standard?

A bit of a context on why I am posting these questions. I am trying to design and implement a signing service that will store digital signatures in a such way that it will be very transparent, and **explicitly clear** what digital signatures were created for what files/data, and what the act of creating these signatures meant to the signers at the time of the signing.
 
Currently, as per my understanding (which is actually quite limited, so correct me if I am wrong), there is no universal standard on how to link digital signatures with signed files/data _**and with**_ the meaning/claim of what that signatures meant for the signers at the time of signing (currently, the meaning of the signatures is always implicit).
For example, MS Office suite has their way to store signatures with signed files, Adobe PDFs have their way, GPG have theirs. The ways MS and Adobe sign and store signatures are obviously locked into their ecosystem and are not explicitly transparent 
GPG signing is not explicitly transparent as well. By "not explicitly transparent" I mean that there is no JSON file, by reading which it would be very clear to understand, what data/file was signed, where the signatures are, and what the act of creating the signatures meant for the signer at the time of signing.

Additional note: As per my understanding the renaming of the standard from Verifiable Claims to Verifiable Credentials was made recently, and I understand that there are probably good reasons for it, but if the generic claims provided in the examples above are possible within the standard I would vote to rename the standard to Signed Claims rather than Verifiable Credentials.

**Comment by msporny** [comment]
> MAIN QUESTION: Will it be correct to use VC standard to link digital signatures with signed data/files and with explicit explanation of the meaning of the signature for the signer at the time of signing, or VC standard is only for creating relatively simple credentials?

The VC standard is not just for simple credentials. There are already examples such as a multi-year student transcript possibly containing hundreds of claims that are being produced in pilot systems.

> The original name of the group "Verifiable Claims" lead me thinking that the standard can be used to create, sign, verify signatures and explicitly explain meaning of the signatures for any kind of claims.

Yes, that is still true.

> SUB-QUESTION 1: Can Verifiable Credential standard be used to create generic claims as provided in the examples 1,2,3 ?

Yes, it can. You will need to use additional JSON-LD Contexts and Linked Data Vocabularies, but the standard is designed to be extremely flexible with respect to the types of claims you can make.

> EXAMPLE 1, a claim that an entity represented by DID::Alice, has read the contract represented by URN:hash256-111, URL:http-111, fully understood the contract and agreed to adhere to it. Alice's signature provided.

Yes, you can express that. Whether or not Alice truly did "fully understand" the contract is a topic of legal debate, but you can model an attestation that Alice said she read and agreed to the contract identified by the given hash and URL. You also don't needt o use DID::Alice as the identifier, but can use HTTP URLs or other types of URI-based identifiers.

> EXAMPLE 2, a claim that an entity represented by DID::Bob, has released the file URN:hash256-222,
available to the public at URL:http-222 and to the best of his knowledge the file does not contain viruses. Bob's signature provided.

Yes, this can also be expressed. Again, you'd need to pair the Verifiable Credential with the appropriate Linked Data Vocabulary and JSON-LD Context that defines a set of terms for talking about files and viruses.

> EXAMPLE 3, a claim that an entity represented by DID::Charley, supports the claim URN::hash256-333 made in Example 2 by Bob, and although did not check the content of the file released by Bob, himself supports Bob's claim that it is viruses free. Charley's signature provided.

Yes, this is also possible given the caveat above.

> SUB-QUESTION 2: Is it possible to make claim about a claim using current VC standard?

Yes, you can do this in two ways. The first is to use the credential identifier that made the original set of claims and make a claim about the accuracy of the original credential. The second is to state make a statement about the graph containing the claim, where you may want to be very specific about the claim you're refuting. For example: "Alice said the sky was purple, and I contest that statement and simultaneously claim that the sky is blue".

Again, the modelling of the data is important, but the container format for Verifiable Credentials provide for all of the use cases that you have specified above.

**Comment by msporny** [comment]
> Currently, as per my understanding (which is actually quite limited, so correct me if I am wrong), there is no universal standard on how to link digital signatures with signed files/data and with the meaning/claim of what that signatures meant for the signers at the time of signing (currently, the meaning of the signatures is always implicit).

Yes, this is correct and is one of the reasons we are creating the standard.

> Additional note: As per my understanding the renaming of the standard from Verifiable Claims to Verifiable Credentials was made recently, and I understand that there are probably good reasons for it, but if the generic claims provided in the examples above are possible within the standard I would vote to rename the standard to Signed Claims rather than Verifiable Credentials.

Yes, "Signed Claims" came up as an option over a year ago. The biggest argument against it is that those that didn't know about cryptography mistook the name for a pen and ink signature and therefore completely missed the whole point of the technology. Naming is hard. :)

**Comment by msporny** [comment]
@Drabiv, is it ok if I close this issue? I think everything you wanted to do is possible and it doesn't raise any resolvable issues with the current spec (other than the name, which I've responded to as well). 

Please close the issue if we've answered all of your questions as long as you don't think they'll impact the specification. If you want to have a more in depth discussion about your questions, please join the Community Group and send an email to the public mailing list (there are many more people that can respond to your question there): https://www.w3.org/community/credentials/

**Comment by Drabiv** [comment]
@msporny thanks a lot for the answers. They clarified all of my high level concerns about the standard. I am now intend to use the standard for my own implementation and specifications now. Closing this issue.

I am subscribed to the mailing list, but thought it is better to post the questions on Github. 
If I have more specific questions, issues with a standard (and I think I will) is it better to post them here or on the mailing list?

**Comment by msporny** [comment]
> I am now intend to use the standard for my own implementation and specifications now. 

Great! Please let us know how your implementations go.

> I am subscribed to the mailing list, but thought it is better to post the questions on Github. If I have more specific questions, issues with a standard (and I think I will) is it better to post them here or on the mailing list?

General questions are best handled on the mailing list. Technical issues with the spec that will most likely result in specification text being added, changed, or deleted, are best handled here.
