### ISSUE TITLE
Provide guidance when media type is incorrect

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1015]
For a variety of reasons, developers or systems don't always use the correct media type. Some of these reasons include:

* A web server defaults to `text/plain` or `application/octet-stream` when a file extension isn't available and it can't determine the media type via content sniffing.
* A developer adds a file extension that is less accurate than the content of the file (e.g., `application/json` vs. `application/ld+json` vs. `application/credential+ld+json`)
* An implementer mis-implements the media type for a particular transaction (e.g., using `application/credential+ld+json` instead of `application/verifiable-credential+ld+json`)

For these scenarios, it might be beneficial for the specification to provide some guidance such that developers know the deterministic media type fallback strategy to use.

**Comment by msporny** [comment]
One way we could provide this guidance is language to the following effect:

* Implementations, developers, and authors SHOULD use the most accurate media type when referring to media types related to Verifiable Credentials.
* If, for whatever reason, they fail to do the above, it is possible to deterministically detect some specific media types when a less specific media type is served to you.
* When dealing with Data Integrity secured VCs, the most specific to least specific media types are: `application/verifiable-credential+ld+json` -> `application/ld+json` -> `application/json`

Therefore, if you are expecting a `application/verifiable-credential+ld+json` but you're served an `application/ld+json` or an `application/json`, then you can deterministically evaluate if it is an `application/verifiable-credential+ld+json` by 1) checking to make sure the first element in `@context` is `https://www.w3.org/ns/credentials/v2` or `https://www.w3.org/2018/credentials/v1`, and 2) it has a `proof` field. If it does, you can proceed and process it as an `application/verifiable-credential+ld+json`.

While it's a bit janky to write such text in a specification, this is roughly what HTML5 decided to do after years of developers getting the details, including media type, wrong.

**Comment by Sakurann** [comment]
We should also add the guidance that "media types do not necessarily need to be put in the credential itself - profiles can say they accept only a certain media type in certain ecosystems/use-cases"

**Comment by OR13** [comment]
Suggest before CR, but it can be done after

**Comment by msporny** [comment]
PR #1189 has been raised to address this issue. This issue will be closed once that PR has been merged.

**Comment by msporny** [comment]
PR #1189 has been merged, closing.
