### ISSUE TITLE
Remove requirement for JWT (etc.) support from VC 2.0 & only support Linked Data

### ISSUE THREAD

**Issue by ChristopherA** [w3c/vc-data-model#1018]
I am concerned that the larger digital credential ecosystem that is doing some form of verifiable digital credentials is no longer present in our discussions here and has largely given up and abandoned our venue for collaboration.

Those that remain in these are largely people comfortable with RDF-style Linked Data architecture choices (as represented by specs in the JSON-LD WG and the Linked Data Signature WG).

As a cryptographic engineering expert, I am very concerned that by trying to compromise and reconcile JWT & JSON-LD support in VC 2.0 and trying to support both, that we are not able to address the issues and the attack surface sufficiently.

However, I do feel confident that this group can improve on Verifiable Credentials using JSON-LD, especially if they do not have to deal with reconciliation with JWT and other architectures (including KERI's ACDC/JSON, IPFS/CBOR, mDL/CBOR, Gordian Envelope/CBOR, etc.). I would love to see this group focus on just doing VCs and VPs using JSON-LD properly.

I really want to see selective disclosure in JSON-LD be required, and that we address various other correlation & schema security and privacy issues that are specific to JSON-LD, and not having to deal with JWT/CBOR/et al would give us the space to do so and resolve these important security and privacy issues without being distracted.

Thus I specifically propose that our key deliverable in our charter be "VC 2.0 for JSON-LD", and let other communities decide if they want to advance their work separately as other W3C working groups, W3C community groups, IETF, or not at all.

**Comment by ChristopherA** [comment]
BTW, this is the kind of thing a JSON-LD specific VC 2.0 spec could address if we don't get distracted:

"Formalising Linked-Data based Verifiable Credentials for Selective Disclosure" 
https://ieeexplore.ieee.org/document/9799315 (pdf at https://sako-lab.jp/download.php?article=ssr2022_proceedings_dan.pdf)

"In this paper, we propose a formal definition for Linked-Data based verifiable credential to enable secure selective disclosure among one or multiple verifiable creden-tials a user has. Previous schemes considered using a single verifiable credential and could not hide the user's identifying information when performing selective disclosure. We pro-pose the first Linked-Data based verifiable credentials that can perform selective disclosure free from the restrictions the previous scheme had, and prove its property. We also discuss a novel use of combining multiple certificates issued by independent issuers to still allow users to perform selective disclosure on the set of credentials. Our scheme has been implemented as an open source Web-based application that generates a verifiable presentation for a given selection of attributes. The performance evaluation is also provided in the paper."

**Comment by TallTed** [comment]
I wonder why "Linked-Data based Verifiable Credentials for Selective Disclosure" weren't brought up in/to the Credentials Community Group, the Verifiable Credentials Working Group, and/or the Verifiable Claims Working Group (depending on their specific years of development), instead of going the the IEEE which (so far as I know) hasn't specified any spec related to RDF-style Linked Data nor W3C Verifiable Credentials?

**Comment by ChristopherA** [comment]
> I wonder why "Linked-Data based Verifiable Credentials for Selective Disclosure" weren't brought up in/to the Credentials Community Group, the Verifiable Credentials Working Group, and/or the Verifiable Claims Working Group (depending on their specific years of development), instead of going the the IEEE which (so far as I know) hasn't specified any spec related to RDF-style Linked Data nor W3C Verifiable Credentials?

I think the authors of that paper are participating in the RDF Dataset Canonicalization and Hash WG - https://www.w3.org/groups/wg/rch — I’m not a member of that group.

**Comment by peacekeeper** [comment]
> I think the authors of that paper are participating in the RDF Dataset Canonicalization and Hash WG

Yes, Dan is one of the editors, and Kazue is participating as well. I'm happy about this, since the selective disclosure topic is not only about cryptography, but also about how the JSON-LD/RDF data content is modeled and canonicalized. The authors of this paper have some really good ideas about this.

**Comment by mwherman2000** [comment]
> I am concerned that the larger digital credential ecosystem that is doing some form of verifiable digital credentials is no longer present in our discussions here and has largely given up and abandoned our venue for collaboration.
> 
> Those that remain in these are largely people comfortable with RDF-style Linked Data architecture choices (as represented by specs in the JSON-LD WG and the Linked Data Signature WG).

During some originally unrelated research, I found the following. I'm not offering any further commentary but it is worthy of a read and some reflection IMO.

> **Strategy**
> The strategy's three phases are:[14][[15]](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish#cite_note-15)
> 
> 1. Embrace: Development of software substantially compatible with a competing product, or implementing a public standard.
> 2. Extend: Addition and promotion of features not supported by the competing product or part of the standard, creating interoperability problems for customers who try to use the "simple" standard.
> 3. Extinguish: When extensions become a [de facto standard](https://en.wikipedia.org/wiki/De_facto_standard) because of their dominant market share, they marginalize competitors that do not or cannot support the new extensions.
> [An organization] has claimed that the original strategy is not anti-competitive, but rather an exercise of its discretion to implement features it believes customers want.[[16]](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish#cite_note-1
Reference: https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish#Strategy

Is this strategy poentially at play here in the push to support JSON-LD/RDF?

**Comment by OR13** [comment]
> Linked-Data based Verifiable Credentials for Selective Disclosure

https://github.com/w3c-ccg/ldp-bbs2020/

Uses URDNA2015 and bbs... everything we work on at W3C means not working on something else... The working group has very limited bandwidth.

**Comment by OR13** [comment]
I suggest we close this issue.

**Comment by Sakurann** [comment]
(discussed on a WG call that the WG is highly unlikely to get consensus on this topic)

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-11-vcwg-special#section1-9) on 2023-04-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.9. Remove requirement for JWT (etc.) support from VC 2.0 & only support Linked Data (issue vc-data-model#1018)

_See github issue [vc-data-model#1018](https://github.com/w3c/vc-data-model/issues/1018)._




**Kristina Yasuda:** "Remove requirement for JWT (etc.) support from VC 2.0 & only support Linked Data" is the issue....  

> *Manu Sporny:* +1 to close, since we won't get consensus on it..

**Joe Andrieu:** suggests pending close.  
… does not think we will get consensus.  

**Kristina Yasuda:** marking pending close for now.  

</details>
