### ISSUE TITLE
Typos in v.1.1

### ISSUE THREAD

**Issue by shujikamitsuna** [w3c/vc-data-model#1021]
This is KAMITSUNA Shuji from Japan.

I translated the v.1.1 spec into Japanese.
Thank you for the great spec.
http://www.asahi-net.or.jp/~ax2s-kmtn/internet/did/REC-vc-data-model-20220303.html

I found some possible typos:
(1) in the image, Figure 10: "Repeateable" might be "Repeatable".
(2) in the alt attribute, Figure 12: "ia" might be "via".
(3) in the alt attribute, Figure 13: "e.g., Parent, Pet Owner, Travel Agent" might be "e.g., Pet Owner, Travel Agent". That is, no mention about parent in the image.

It seems like some of these remain in v.2.0.

Additionally, according to the W3C Link Cheker, there are issues with the URLs.
https://validator.w3.org/checklink?uri=https%3A%2F%2Fwww.w3.org%2FTR%2F2022%2FREC-vc-data-model-20220303%2F&hide_type=all&depth=&check=Check

Best regards,

**Comment by bumblefudge** [comment]
🙇 🙇 🙇

**Comment by shujikamitsuna** [comment]
Thank you!
