### ISSUE TITLE
Add guidance on ignoring optional fields

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1027]
Originally reported on: https://github.com/w3c/vc-data-model/pull/987#issuecomment-1413789794

@David-Chadwick noted that there are many "optional" fields of a W3C Credential, which can safely be ignored by a verifier.

I would like to explicitly state this in normative language, to remove confusion of ambiguous processing.

`credentialStatus`, `ToU`, `Evidence`, `validity period`, `Status`... MUST NOT result in a verification or validation failure if not understood by the issuer or verifier.

^ Probably not correct, but hopefully triggering enough to bikeshed some better text on the issue.

**Comment by David-Chadwick** [comment]
This is where X.509 has an edge over VCs. It has the critical  extensions flag, set by the issuer, which effectively says "if you do not understand this field then you MUST fail the verification" OTOH, if the flag is not set, if you do understand this field then you must obey it, but if you do not understand it you may safely ignore it.
@OR13 Please note the difference between verification and validation. The verification procedure should always act on all the optional fields and report the result to the application, which will then decide, during validation, whether to ignore the result of the verification or not. So an unverifiable VC may be accepted at validation time, whilst a verified VC may be rejected at validation time. But the application layer needs to know that the verification has been performed correctly and deterministically and not randomly.

**Comment by David-Chadwick** [comment]
CONCRETE PROPOSAL
we should add a Critical boolean to every optional metadata field so that the verifier knows whether it can ignore fields it does not understand.

**Comment by OR13** [comment]
JOSE / COSE have the `crit` header... 

- https://www.rfc-editor.org/rfc/rfc7515#section-4.1.11
- https://www.rfc-editor.org/rfc/rfc8152.html#section-3.1

**Comment by David-Chadwick** [comment]
@OR13 Thanks for these pointers. The deficiency (or maybe not) in these definitions is that it does not explicitly say what a recipient must do with an extension that is not marked critical. Maybe the specs are relying on each extension to explicitly state this, whereas X.509 made a blanket statement that applied to all extensions.

Note also that the proposal I am making is to the VCDM and not to the proof method. This new Critical boolean should be independent of the proofing mechanism and should apply to all of them.

**Comment by dlongley** [comment]
Linking in the discussion from the first VCWG on "critical" fields: https://github.com/w3c/vc-data-model/issues/158

**Comment by Sakurann** [comment]
+1 to adding a language that says "optional field do not have to be present for the credential to be valid".

mandatory/optional for metadata about credential (status, evidence, ToU) should not be confused with the mandatory/optional for the claims about the user in the credential (firstName, lastName, etc.) I think Orie was talking about the former in which case, one clarifying sentence in the lines of what is suggested above would be sufficient.

Regarding validation/verification, I would suggest using validate vs verify section in [RFC4949](https://www.rfc-editor.org/rfc/rfc4949). (Happy to open a new issue on this).

```
     usage, IDOCs SHOULD comply with the following two rules:
      -  Rule 1: Use "validate" when referring to a process intended to
         establish the soundness or correctness of a construct (e.g.,
         "certificate validation"). (See: validate.)
      -  Rule 2: Use "verify" when referring to a process intended to
         test or prove the truth or accuracy of a fact or value (e.g.,
         "authenticate"). (See: verify.)
```

**Comment by msporny** [comment]
> Regarding validation/verification, I would suggest using validate vs verify section in RFC4949. (Happy to open a new issue on this).

Note that the specification already has definitions for "validation" and "verification". It took the WG a long time to settle on those definitions:

https://w3c.github.io/vc-data-model/#dfn-credential-validation
https://w3c.github.io/vc-data-model/#dfn-verify

Raising a PR to change those definitions will almost certainly re-open that can of worms (plus, we'll have to make sure all references to those definitions fit how they're used within the specification.

**Comment by jandrieu** [comment]
I think there's a potential category error here.

Optional properties aren't describing optionality for the Verifier. The verifier already has ultimate authority as to which properties they accept as useful. They may accept a birthdate from a driver's license, but ignore its height and weight details.

Rather, the optional properties are optional for the Issuer. The choice to include an optional field or not is at the point of issuance.

So, I'm not sure there is any guidance to give, other than perhaps clarifying the nature of the optionality (in the VCDM spec). Optional does not mean that the verifier can ignore it, but rather that the issuer can choose to include that property or not.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-06-vcwg-special#section1-13) on 2023-06-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.13. Add guidance on ignoring optional fields (issue vc-data-model#1027)

_See github issue [vc-data-model#1027](https://github.com/w3c/vc-data-model/issues/1027)._




**Brent Zundel:** Adding guidance on ignoring optional fields -- pre/post CR?  

**Manu Sporny:** I think we could end up with normative guidance, there's always a risk of that, so a pre-CR thing probably.  

**Brent Zundel:** Any opposition for before CR?  

> *Orie Steele:* +1 to fixing this before CR.

**Joe Andrieu:** I have a question -- optional fields are issuer things, not that they can be ignored by a Verifier -- it's about whether or not the issuer needs to put it in.  

**Orie Steele:** In general, a Verifier can ignore 100% of what an issuer has put in there. In terms of requirement, there are required fields, optional fields that are supposed to be understood -- part of why our vocab should be normative if fields are going to be present.  

**Brent Zundel:** Thanks for everyone coming today -- this was fantastic and satisfying, let's do this again tomorrow.  

> *Phillip Long:* "The magnificent 10".

**Brent Zundel:** We'll try to figure out the call details.  
… pleasure to work with you all, bye.  

---

</details>

**Comment by brentzundel** [comment]
An attemptat concrete normative text, please feel free to suggest alternatives:
An Issuer MAY choose to omit optional fields, but a verifier MUST NOT ignore any fields defined in the data model

**Comment by OR13** [comment]
hmm... we do seem to be discussing something close to https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.11

I will give it a try:

An Issuer MUST include all required fields.

A Verifier MUST validate all required fields.

Optional fields can be ignored by all parties.

**Comment by dlongley** [comment]
I haven't had time to think through text here myself, but I think @OR13's suggestion is looking pretty good:

> An Issuer MUST include all required fields.
> 
> A Verifier MUST validate all required fields.
> 
> Optional fields can be ignored by all parties.

**Comment by TallTed** [comment]
> * A Verifier MUST validate all required fields.

That's getting close to forcing business logic... I think that's better as a SHOULD, if even that forceful.
