### ISSUE TITLE
Broken link in 1.0 data integrity section

### ISSUE THREAD

**Issue by vongohren** [w3c/vc-data-model#1036]
Hi! I just found a broken link in https://www.w3.org/TR/vc-data-model/#data-integrity-proofs, the link marked as Data Integrity.

But I cannot find it in the https://github.com/w3c/vc-data-model/blob/main/index.html file.

Im just getting used to proposing changes to the spec, but the current main link points towards 1.0, and the index html points to 2.0 version. So it might be fixed already, or removed.

Where do I find 1.0 version, and is it worth fixing? Depending on when the 2.0 version comes out?
Does this section, with broken link, exist in the 2.0 version? Not as I could view from the index.html file and searching for the same workd.

Sorry for the stupid issue, just trying to familiar myself with the way of making proposals and changes

**Comment by msporny** [comment]
We need to update the redirect from https://w3c-ccg.github.io/data-integrity-spec/ to https://w3c.github.io/vc-data-integrity/.
