### ISSUE TITLE
Query on HashLinks

### ISSUE THREAD

**Issue by sumanair** [w3c/vc-data-model#1038]
Hi all,
Ref #135 
The vc-data-model has a Content Integrity Protection section with some recommendations  https://www.w3.org/TR/vc-data-model/#content-integrity-protection. I am coming across some scenarios where the clients may prefer to host the referenced artifact - whether it is a credential or an image / document, and IPFS may not always be appropriate. I was looking at the [HASHLINK](https://datatracker.ietf.org/doc/draft-sporny-hashlink/) reference.
I see that the https://datatracker.ietf.org/doc/html/draft-sporny-hashlink-07 seems to be an expired internet draft. I was curious to know where that effort is headed and if it is still the recommendation for the vc-data-model.

**Comment by Sakurann** [comment]
might be a related issue #831

**Comment by OR13** [comment]
Suggest closing, we don't need to comment on hashlinks.

**Comment by msporny** [comment]
> I see that the https://datatracker.ietf.org/doc/html/draft-sporny-hashlink-07 seems to be an expired internet draft. I was curious to know where that effort is headed and if it is still the recommendation for the vc-data-model.

Hi, I'm the Editor of that independent draft... the work continues, but there isn't strong enough demand to standardize it at this point in time. I'll keep it going, but using it at this point is experimental.

It's not ready to be added in any sort of normative capacity in this specification, so we're marking it pending close for now, we might revisit it during the VC 3.0 work.
