### ISSUE TITLE
Fix media type registration language

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1052]
The media type registration language in the current specification is a bit wonky. It says:

> This specification registers the application/credential+ld+json MIME Media Type specifically for identifying documents conforming to the Verifiable Credentials format.
> ...
> Note that while the Verifiable Credentials format uses JSON-LD conventions, there are a number of constraints and additional requirements for Verifiable Credential implementations that justify the use of a specific media type.

We should be clear if we're talking about "Credentials", "Verifiable Credentials", or "the Verifiable Credential Data Model".

**Comment by msporny** [comment]
Keep in mind that we might have an `application/verifiable-credential+ld+json` and `application/verifiable-presentation+ld+json` media type incoming (or not!), so the language might have to reflect that as well. With that in mind, how about something like this:

> This specification registers the application/SOMETHING media type for identifying conformant documents (link to document conformance section of the specification) that express a (credential|verifiable credential|presentation|verifiable presentation).
> ...
> Note that while the Verifiable Credentials Data Model uses JSON-LD conventions, there are a number of additional constraints and requirements that justify a specific media type.

**Comment by TallTed** [comment]
I've said things like this elsewhere, but those seem to be closing with this to track the ongoing, so...

I'm fine with one media type being used for both Verifiable and UNverifiable Credentials, and that or another single media type being used for both Verifiable and UNverifiable Presentations.

Whether the media type(s) is(are) branded "Verifable" or not, the specified structure should allow for the presence *or* lack of the proof(s) necessary for that verifiability, which presence or lack is what determines whether the data contained in the structure is or is not verifiable.

**Comment by OR13** [comment]
IIRC this has been done.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-06-vcwg-special#section1-11) on 2023-06-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.11. Fix media type registration language (issue vc-data-model#1052)

_See github issue [vc-data-model#1052](https://github.com/w3c/vc-data-model/issues/1052)._




> *Phillip Long:* close it!

**Brent Zundel:** This looks like it has been addressed, pending close?  

**all:** No objections.  

</details>
