### ISSUE TITLE
Invalid definition of context in schema

### ISSUE THREAD

**Issue by xaviaracil** [w3c/vc-data-model#1059]
Context is defined in the spec as an array of string or objects (https://www.w3.org/TR/vc-data-model/#contexts):

> The value of the `@context` [property](https://www.w3.org/TR/vc-data-model/#dfn-property) MUST be an ordered set where the first item is a [URI](https://www.w3.org/TR/vc-data-model/#dfn-uri) with the value https://www.w3.org/2018/credentials/v1. For reference, a copy of the base context is provided in Appendix [B.1 Base Context](https://www.w3.org/TR/vc-data-model/#base-context). Subsequent items in the array MUST express context information and be composed of any combination of [URIs](https://www.w3.org/TR/vc-data-model/#dfn-uri) or objects. It is RECOMMENDED that each [URI](https://www.w3.org/TR/vc-data-model/#dfn-uri) in the `@context` be one which, if dereferenced, results in a document containing machine-readable information about the `@context`.

However, the schema restricts `@context` to be only an array of strings (https://github.com/w3c/vc-data-model/blob/main/schema/verifiable-credential/verifiable-credential-schema.json#L139-L148):

```json
"@context": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "contains": {
        "const": "https://www.w3.org/2018/credentials/v1"
      },
      "minItems": 1
    },
```

Schema should be fixed to allow also objects in the array.

**Comment by Sakurann** [comment]
an explicit sentence in the specification that says "do not use anything other than JSON-LD `@context` values" might be helpful.

**Comment by decentralgabe** [comment]
dropped the string requirement here https://github.com/w3c/vc-data-model/pull/1064
