### ISSUE TITLE
Can you use WebAuthN for Presentation Holder Binding?

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1063]
Consider the following:

WebAuthN Registration where "name" / "user-id" are bound to a verifiable credential serialization.

When the credential is presented, the presentation (including replay mitigation) is hashed and used as the "challenge" for a web auth n authentication.

The verifier checks the signature is bound to the public key that was registered for the verifiable credential serialization.
The veriifer checks that the presentation hashes to the challenge that was signed with the authenticator.

The nasty part is all the, webauthn metadata ( clientDataJSON,  authenticatorData ), and the domain binding to the RP...

Instead of a nice signature in standard JOSE / COSE, the verifier has to check a web auth n signature.

The positive side is that Web Auth N is widely deployed and supported by web browsers today, so presentation of this manner, are relatively trivial to implement.

**Comment by Sakurann** [comment]
This would require Issuer knowing at the point of issuance with which Verifier the User intends to use the credential (so that it can use a Verifier specific key for the holder binding). So.. don't think it is a good idea.

**Comment by OR13** [comment]
Just to be clear on the hacky things you can do:

1. You could use sd+jwt
2. You could put the authenticator public key in the cnf.
3. You could use a serialized authenticator signed response as the "holder binding jwt"

The issue is primarily that 3 is not a "standard digital signature", and in general... 

You cannot use WebAuthN to produce standard digital signatures.

**Comment by nikosft** [comment]
Just to put another perspective. We are experimenting with something similar using a web-based wallet. In our approach the public key used in WebAuthN is associated with the wallet. So the issuer does not need to know with which Verifier the User intends to use the credential. It might be possible to do the same using application-based wallets, e.g., Yubikey has a convenient SDK that allows applications to generate WebAuthN signatures. The main problem we are facing is what @OR13 says: WebAuthN does not produce standard signatures.  Having something similar to this [inactive draft](https://github.com/jaredhanson/id-oauth-fido2/blob/main/draft.txt) would have been useful.

**Comment by Sakurann** [comment]
https://chromestatus.com/feature/5138422207348736

This WebAuthn PRF extension should enable using "WebAuthn" with cryptographic holder binding (in the browsers that have implemented this extension)

**Comment by Sakurann** [comment]
https://chromestatus.com/feature/5138422207348736

This WebAuthn PRF extension should enable using "WebAuthn" with cryptographic holder binding (in the browsers that have implemented this extension)

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-04-12-vcwg#section4-7) on 2023-04-12

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.7. Can you use WebAuthN for Presentation Holder Binding? (issue vc-data-model#1063)

_See github issue [vc-data-model#1063](https://github.com/w3c/vc-data-model/issues/1063)._



**Orie Steele:** no you cannot. That's the answer. There are browser APIs if you're in a browser environment. Should close issue.  

> *Manu Sporny:* +1 to Orie, no you cannot, close issue..

**Brent Zundel:** any objections to marking as pending closed. No objections - marked pending close.  

</details>

**Comment by brentzundel** [comment]
No objections raised since being marked as `pending close`. Closing.
