### ISSUE TITLE
Media types do not indicate securing mechanism

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1065]
_Originally posted by @Sakurann in https://github.com/w3c/vc-data-model/pull/1062#discussion_r1136323602_

>> media types do not indicate proofing mechanisms

>  I think we should apply the same philosophy to all media types related to this specification that media types describe a secured 'thing' and media type itself does not imply the proofing mechanism. given the base media type is application/vc+ld+json; all extensions of VCDM core spec should use `vc+`.

**Comment by TallTed** [comment]
Rather, I would say that _media types describe a **securable** 'thing'_ or _media types describe a **possibly** secured 'thing'_.

That is to say — as with a password-secured ZIP, or a signed and/or encrypted email message — the _structure_ is defined by the media type and allows for signature or encryption, but the _content_ does not necessarily include either signature or encryption.

**Comment by Sakurann** [comment]
might be more in-scope fo vc-jwt spec. but needs guidance that this media type is to be used as `cty` not `typ` JOSE Header.

**Comment by brentzundel** [comment]
I've attempted to capture the language and ideas above in PR #1107, please review.
