### ISSUE TITLE
Audience in Verifiable Presentations?

### ISSUE THREAD

**Issue by nikolockenvitz** [w3c/vc-data-model#1069]
The spec does not say anything about specifying the audience within a Verifiable Presentation. In case a VP is requested and a challenge is included in the VP, I could understand that the audience is not required. But if one wants to share a VP pro-actively, it makes sense to specify an audience in the VP. Also, in the [JWT implementation of VCs/VPs](https://w3c.github.io/vc-jwt/), the usage of `aud` is mentioned.

Should this be added to the vc-data-model spec? Or has this been discarded intentionally?

**Comment by awoie** [comment]
In Data Integrity proofs the audience is defined by the `domain` property in the `proof`. With JWT-VCs, the JWT itself represents the proof and `aud` is a claim in the JWT.

Does this answer your question?

**Comment by nikolockenvitz** [comment]
Ah I see; yes, this answers my question. Thanks for the fast response.
