### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#107]
The current text in section 3.3 Profiles states
"A verifiable profile is a collection of one or more verifiable
credentials typically about the same subject"

The word typically is misleading and redundant. Suggest delete it.
Since a VC is about a single subject, then the profile must be about the
same subject.
When would it make sense to take the VCs of different subjects and merge
them together in a profile? To my mind this would be a vulnerability (e.g. I try
to pass off someone else's VC as mine).

**Comment by David-Chadwick** [comment]
Additional ambiguous text is presented in section 2 which states
A verifiable profile is a profile that is tamper-resistant and whose contents are typically counter-signed by the holder or subject. 
Ambiguity is bad for standards as it leads to different interpretations, different implementations and lack of interworking.
The verifiable profile should ONLY be signed by the holder. Suggest remove 'typically' and 'or subject'.
In this way, the profile can be used to indicate when the holder=subject or the holderNEsubject. Specifically, example 12 in section in 7.1.2 shows a the profile where the holder ID is the same as subject ID in the credential. However, the current text makes no mention of this. I suggest replacing the example 12 caption with
Example 12: A simple verifiable profile in which the holder is the subject.

If wanted, a second example could be added where the holder is not the subject.

**Comment by burnburn** [comment]
Waiting on resolution of issue #106

**Comment by msporny** [comment]
All mentions of "typically" and "or subject" have been removed from the specification. I've scanned the current specification for the original issue and further issues raised in the first comment and have found all of the text to have been updated over time. I'm closing this issue because all text has been updated over time to remove the issues mentioned.
