### ISSUE TITLE
How could we deals with chain reaction revocation of VC?

### ISSUE THREAD

**Issue by MizukiSonoko** [w3c/vc-data-model#1072]
Hello, I have read https://www.w3.org/TR/vc-data-model/
and I have a question about revocation.

According to spec. there are many mentions about revocation,
- An issuer might revoke a verifiable credential.
- The holder and verifier trust the issuer to issue true (that is, not false) credentials about the subject, and to revoke them quickly when appropriate.
- verifiable data registry has revocation state of vc,

Etc....

But, I. cannot find a mention about chain reaction revocation.
For example,
- Issuer A issued `VCa` to holder M, VCa claims `M have graduated the X Univ`.
- Issuer B issued `VCb` to holder M, VCb claims `M is employee of Company Y`. and Company Y requires that M have graduated the X Univ.
- Issuer C issued `VCc` to holder M, VCc claims `M is employee of Company Z`. and Company Z requires that M have graduated the X Univ and A is a retired employee of Company Y.

In this case, when VCb or VCa revoked, I think it would be more correct to revoke VCc in a chain reaction. but any Issuer are independent, so only Issuer C can revoke the VCc and if Issuer C is unaware, it is valid until expiration date.　

What is the best specification for such a situation?
Is this specification no problem?

I propose. `precondition` field. 
`"precondition":["<dids of VC, if VC was revoked, this VC is revoked>"]`

(sorry for if already same issue exists) 

Regards

**Comment by MizukiSonoko** [comment]
Sorry for late reply.

I see, I will make a proposal about revocation, thanks!
So should I make the PR in https://github.com/w3c/vc-specs-dir ?
regards

**Comment by awoie** [comment]
> Sorry for late reply.
> 
> I see, I will make a proposal about revocation, thanks! So should I make the PR in https://github.com/w3c/vc-specs-dir ? regards

The idea is to create your own vocab and specification somewhere (e.g. your github pages) and then you would create a PR against vc-specs-dir, yes.

I guess we can close this issue now since the original issue was a question and I guess the question is answered. Tracking the vc-specs-dir entry is out-of-scope of VCDM and this issue.

**Comment by MizukiSonoko** [comment]
Ok, I appreciate your reply.
I made the PR about this issue
https://github.com/w3c/vc-specs-dir/pull/20
thanks

**Comment by brentzundel** [comment]
No objections raised since being marked `pending close`, closing.
