### ISSUE TITLE
Typo in Example 6

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#108]
The Example 6  title and description are inconsistent
The title says

Usage of termsOfUse property by an Issuer

but the text below states
In the example above, the holder is prohibiting a verifier from using the information provided to correlate the holder.

**Comment by David-Chadwick** [comment]
#170 fixes this

**Comment by msporny** [comment]
Resolved in https://github.com/w3c/vc-data-model/commit/f96e446802928bb7d80516d5ef23da8415c56406 ... closing issue.
