### ISSUE TITLE
How to know who specified the Terms of Use

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#109]
The current data model section 5.1 states "Terms of use can be utilized by an issuer, subject or a holder to express limitations on the use of information expressed by the Verifiable Credentials Model. "

How does each of these specify terms of use?

1. Issuer. Clearly  any terms of use in a credential must have been inserted by the credential issuer
2. Holder. In this case, the holder can group various credentials together and insert a terms of use into the profile, after the credentials and before the counter signature.
3. Subject, where Subject = Holder. Same as for holder above.
4. Subject, where Subject NE Holder. This is outside the scope of the current data model. The subject is not able to specify terms of use in the VC or the profile.

It is suggested that clarifying text is added to section 5.1 to specify each of the above

**Comment by David-Chadwick** [comment]
Furthermore in Section 6.8, the following text is not quite right, viz:
"If the holder has placed any policy information about the use of the credential, e.g. intended verifiers, restricted usage rights, etc., that this policy is adhered to."
since the holder can only place policy information in a profile and not in a credential. Therefore I suggest we modify the above text to read:
"If the holder has placed any policy information in a profile, about the use of the enclosed credential(s), e.g. intended verifiers, restricted usage rights, etc., that this policy is adhered to."

**Comment by David-Chadwick** [comment]
An example of an Issuer terms of use is AllowedVerifiers, which lists the URLs of the verifiers that are the intended recipients of the VCs. If the VC is sent to any other verifier by the holder (as he/she/it can easily do) then a conformant verifier Must refuse to accept the VC. A conformance test can easily be written for this. Note that this does not stop a non-conformant implementation from accepting any VC that it wants to, but in this case, it should be made clear to the verifier that its behaviour is non-conformant to the standard.

An example of a holder terms of use is This Session Only, which binds the session ID into the profile. This terms of use is telling the verifier that the set of VCs in this profile Must only be used for this session and Must not be used for any subsequent session, for example, one in which the verifier can identify that it is the same holder in both sessions. Again, one can write a conformance test for this, by getting the holder to access a verifier's protected resource and providing the VCs for this, with the profile containing the This Session Only terms of use, then closing the session, opening a new session to access the same protected resource, and only identifiying itself to the verifier without providing the authorising VCs. In the latter case the holder should be denied access to the protected resource.

**Comment by David-Chadwick** [comment]
If people are happy with the above examples I can write a PR to include them.

**Comment by stonematt** [comment]
"one-click" only URLS are incredibly brittle.  Events like browsers don't load, users accidentally navigates way, internet connectivity issues may consume the event pre-maturely.  Are we at risk of something like this here?  We need an explicit way to consummate the consumption transaction.

**Comment by David-Chadwick** [comment]
@stonematt These are not one click URLs. There is no remote retrieval needed. The verifier reads the content of the terms of use and sees if the value matches its already known 'own' value (either its name/URL or session ID)

**Comment by burnburn** [comment]
#170 was replaced by #188, which has just been merged.  Closing.
