### ISSUE TITLE
Aggregation of claims reveal more than the data itself

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#11]
Aggregation of claims can reveal more information than just the attributes being aggregated. For example, exposing a birthdate and a zip code may identify a person far more accurately than a first and last name.

**Comment by David-Chadwick** [comment]
This is true. Whenever you start to intersect sets you will eventually end up with an intersection that uniquely identifies one individual in the whole world. I don't see how you can prevent this.

**Comment by msporny** [comment]
This issue is merely to track that we are aware of the issue and to generate some text in the privacy section of the specification pointing this out.

**Comment by prototypo** [comment]
It seems to me that this issue is theoretically inescapable, but could be practically addressed by being careful with what information is given out in various scenarios. Carefully thinking through the minimum information needed per use case might do it.
