### ISSUE TITLE
Trust Model

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#110]
The data model talks a lot about trust, but the text is widely dispersed throughout the document.
It would be advisable and helpful to the reader, if all the statements about trust could be brought together into a new section entitled The Trust Model. Here is some strawman text for the new section.

Section X. The Trust Model

The VC trust model is as follows. 

1.	The verifier trusts the issuer to issue the VC that it receives (although this trust could be weakened depending upon the risk assessment of the verifier). 
2.	All entities trust the identifier registry to be un-corruptible and to be a correct record of which identifiers belong to which entities.
3.	The subject trusts the issuer to issue true (i.e. not false) credentials about itself, and to revoke them quickly when requested to do so.
4.	The holder trusts the repository to store his/her VCs securely, to not release them to anyone other than the holder, and to not corrupt or lose them whilst they are in its care.

Note in particular that 
i) the issuer and the verifier do not (need to) trust the repository, and  
ii) the issuer does not (need to) trust the verifier.

**Comment by msporny** [comment]
The PR is in, I need to remove the text that @David-Chadwick suggested be removed (as it shouldn't have been in the PR in the first place). As soon as that's done, I think we should merge the PR and close this issue.
