### ISSUE TITLE
Dispute Resolution

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#111]
Currently there is no text about dispute resolution for example when the subject disagrees with a claim made by an issuer.

5. Dispute Resolution
The situation may arise when a subject or holder determines that the claim information held by an issuer is incorrect, and consequently, that all VCs issued by the issuer to the holder contain incorrect information about the subject. This is a tricky situation, since the issuer is the owner of the information that it issues, but the subject often knows better than the issuer whether the information is correct or not. Before changing any of the held information, the issuer needs to be convinced that it is incorrect, that the requester is the true subject (or his/her agent and not an imposter) and that the subject is not trying to either insert false information or remove true information. 

Consequently it is recommended that all issuers publish their procedures by which subjects may
i)	obtain the complete set of information held by the issuer about the subject
ii)	determine which subset of this information may be issued as VCs to holders (and as a corollary, which must not be inserted into VCs)
iii)	obtain one or more VCs
iv)	ask for an issued VC to be revoked
v)	ask for information held by the issuer to be updated
vi)	resolve disputes arising from either the information held by the issuer about the subject, or the issuing and revoking of VCs by the issuer.

Legislation such as the EU GDPR [http://ec.europa.eu/justice/data-protection/reform/files/regulation_oj_en.pdf] provide the subject with the right to request a copy of the information held by the issuer, the right to correct erroneous information, and the right to lodge a complaint with a supervisory authority if any dispute with the issuer cannot be resolved amicably.

**Comment by stonematt** [comment]
Would we categorize this as privacy, revocation, validation, or something else?

**Comment by jandrieu** [comment]
I think this is out of scope.

**Comment by dlongley** [comment]
+1 for out of scope. There could be something in the future that allows people to file some standardized dispute resolution with issuers but I don't think we're chartered to deal with this at the moment.

**Comment by msporny** [comment]
I'll suggest some spec text to reduce scope and resolve this issue.

**Comment by dlongley** [comment]
We need to define what the scope is here --

Are we talking about simply issuing separate claims or about a dispute protocol with the issuer for getting things "fixed"? Because I think the latter is out of scope.

**Comment by dlongley** [comment]
+1 to adding an example of a credential about another credential.

**Comment by David-Chadwick** [comment]
The original intention was not to add anything to the data model, its syntax or its examples, but to give non-normative guidance to issuers as to how they should operate. The suggestion was to add a non-normative section to the data model document. This may lead in future to other standards that define how issuers should operate in relation to their subjects (akin to the CP and CPS documents that CAs publish for their PKIs)

**Comment by msporny** [comment]
I propose that we create a PR that adds the following section to the specification in the advanced concepts section:

## Disputes

An entity may dispute a credential issued by another entity. The mechanism for doing this is the same as issuing a regular credential except that the subject identifier for the claims are those of the disputed credential. For example, if a disputed credential with an identifier of ```https://example.org/credentials/123``` contains fraudulent statements, an entity may issue the following credential in a public venue to make it known that the credential is disputed:

```
{
  "claim": {
    "id": "http://con-artist.example.com/credentials/3732",
    "currentStatus": "Disputed",
    "statusReason": "Credential contains fraudulent statements"
  },
  "issuer": "http://state.example.gov/",
  "issued": "2017-12-05T14:27:42Z",
  "proof": { ... }
}
```

Note: If a credential does not have an identifier, a content-addressed identifier may be used to identify the disputed credential.
