### ISSUE TITLE
Update diagrams to not use RSA, and generally be accurate

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1121]
Probably use `DataIntegrityProof` since it is the only proof format that is also a graph format.

- https://w3c.github.io/vc-data-model/#info-graph-vc

- https://w3c.github.io/vc-data-model/#info-graph-vp

**Comment by msporny** [comment]
PR https://github.com/w3c/vc-data-model/pull/1129 has been raised to address this issue. Once PR #1129 has been merged, this issue will be closed.
