### ISSUE TITLE
Remove reference to OdrlPolicy2017

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1123]
This RDF types was never documented, and is confusing.

https://github.com/search?q=repo%3Aw3c%2Fvc-data-model%20OdrlPolicy2017&type=code

**Comment by awoie** [comment]
IMO, it has to be replaced with `IssuerPolicy` or `HolderPolicy` although these two have not been defined either.

**Comment by OR13** [comment]
If there are not 2 independent implementations for at least 1 RDF Class, for a given predicate, it should be reserved in the table and removed from the specification.

AFAIK, so far the only extension predicates we have that seem to meet this bar:

- credentialStatus
- credentialSchema

**Comment by msporny** [comment]
PR #1170 was raised to address this issue. This issue will be closed when that PR is merged.
