### ISSUE TITLE
Remove reference to DocumentVerification2018

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#1124]
This RDF Class was never defined and is confusing:

https://github.com/search?q=repo%3Aw3c%2Fvc-data-model%20DocumentVerification2018&type=code

**Comment by brentzundel** [comment]
I agree that this reference should be fixed (if `evidence` ends up being retained) or removed.

**Comment by TallTed** [comment]
This issue should be retitled to reflect that the referenced RDF Class is not `20DocumentVerification2018`, but `DocumentVerification2018`. (The `%20` in the URL is a URL-escaped space in the GitHub search term.)

**Comment by Sakurann** [comment]
+1 to remove.
