### ISSUE TITLE
Make `validFrom` optional

### ISSUE THREAD

**Issue by awoie** [w3c/vc-data-model#1133]
I cannot see why `validFrom` has to be mandatory in the VCDM. Especially since securing mechanism take care of the validity period of the signature. IMO, we should make it OPTIONAL.

Not every VC will have a `validFrom` property. For example, it is even questionable what would be the `validFrom` of a digital driver's license since most DMVs just define the issuance date which has a different semantic meaning than `validFrom`. 

Note that ISO 18013-5 for instance uses `issue_date` (and `expiry_date`) to express validity periods. `issue_date` is the date when the mDL was issued, not when it stated to become valid.

**Comment by awoie** [comment]
I'm aware that this is a breaking change but this should not be a blocker because of the charter of the WG.

**Comment by awoie** [comment]
Note, those fields are typically decided by policy people who don't want to listen to people that are specialized on what the best data model is. In some other cases, there is just no meaningful default value possible. And sometimes `validFrom` might be just wrong when something has been valid forever or since the beginning of time.

**Comment by decentralgabe** [comment]
I agree this should be an optional field. I see value in having a separate "issued at" time, but I'm also OK leaving that up to securing formats.

**Comment by David-Chadwick** [comment]
I also agree that this should be an optional field.
I also believe that every type of proof should mandatorily state its validity period, both start and end.
I think the reason that `validFrom` was originally made mandatory is that it was conflating the starting time of the credential with the starting time of the proofed (or verifiable) credential

**Comment by awoie** [comment]
I think most people are positive on making validFrom optional. I will create a PR that can be discussed in the WG.

**Comment by Sakurann** [comment]
+1 to making it optional.

**Comment by brentzundel** [comment]
+1 to making is optional

**Comment by awoie** [comment]
PR here #1168
