### ISSUE TITLE
id, issuer properties: URL or URI

### ISSUE THREAD

**Issue by alenhorvat** [w3c/vc-data-model#1160]
Hi,

issuer type: URL, is limiting in some use cases. In v1.1 issuer type is URI. In the case of long-term signatures, location persistence cannot be guaranteed.

URL vs URI - was the topic already discussed?

Thank you!

**Comment by alenhorvat** [comment]
_Example id values include UUIDs (urn:uuid:0c07c1ce-57cb-41af-bef2-1b932b986873), HTTP URLs (https://id.example/things#123), and DIDs (did:example:1234abcd).

If the id [property](https://www.w3.org/TR/vc-data-model-2.0/#dfn-property) is present:

The id [property](https://www.w3.org/TR/vc-data-model-2.0/#dfn-property) MUST express an identifier that others are expected to use when expressing statements about a specific thing identified by that identifier.
The id [property](https://www.w3.org/TR/vc-data-model-2.0/#dfn-property) MUST NOT have more than one value.
The value of the id [property](https://www.w3.org/TR/vc-data-model-2.0/#dfn-property) MUST be a [URL](https://www.w3.org/TR/vc-data-model-2.0/#dfn-url) which MAY be dereferenced._

The text says id MUST be a URL, in the example we also see an URN.

@msporny @OR13 @awoie 

Thank you in advance!

**Comment by msporny** [comment]
@alenhorvat wrote:
> URL vs URI - was the topic already discussed?

Yes, discussed to death at W3C between the years of 2008-2018 or so. Ultimately, that resulted in this specification:

https://url.spec.whatwg.org/

... which is now the normative specification for "URLs" for the Web... where URLs include things like URIs and URNs. The argument was that developers were getting confused over the differences between a URI, IRI, URN, and URL... and that most developers were just using the term "URL" to mean all of those things... so browser manufacturers decided that "URL" was the term that everyone should be using.

While I don't agree with the decision, that's where things are between W3C and WHATWG at present. 

This is noted in the definition for URL in the specification (as well as the reference to WHATWG URL): https://www.w3.org/TR/vc-data-model-2.0/#dfn-url

**Comment by alenhorvat** [comment]
Thank you @msporny.

Strange decision of the WHATWG. L somehow stands for "Location" :)

Nevertheless, closing this issue.

**Comment by msporny** [comment]
@alenhorvat wrote:
> Strange decision of the WHATWG. L somehow stands for "Location" :)

Yes, it was and still is. Here's the line in the spec (https://url.spec.whatwg.org/) that does it:

> Goal: Standardize on the term URL. URI and IRI are just confusing. In practice a single algorithm is used for both so keeping them distinct is not helping anyone. URL also easily wins the [search result popularity contest](https://trends.google.com/trends/explore?q=url,uri).

 If you want to read about some of the gory details leading up to that, the bodies are buried here:

https://daniel.haxx.se/blog/2016/05/11/my-url-isnt-your-url/

https://github.com/whatwg/url/issues/118

:)
