### ISSUE TITLE
(tracking issue) apparent copy-paste error in #1144 needs fixing

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-data-model#1161]
```suggestion
    This media type can be used with credentials secured using an <a>external proof</a>.
```

Hmm, this looks wrong? Is this what we're trying to say? I'm going to merge this, but wondering if this is a copy-paste error. If so, @OR13, can you fix it in a future (editorial) PR?

_Originally posted by @msporny in https://github.com/w3c/vc-data-model/pull/1144#discussion_r1233107772_

**Comment by brentzundel** [comment]
@OR13 is there an error that needs to be fixed here?

**Comment by msporny** [comment]
> @OR13 is there an error that needs to be fixed here?

Specifically, the PR said "credentials" when I think it meant "presentations". The `application/vp+ld+json` media type is used to secure /presentations/, not /credentials/?
