### ISSUE TITLE
consider changing all mentions of misnamed `holder binding` to something like `authorized presenter list`

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-data-model#1162]
> Maybe we can agree to change all mentions of the misnamed `holder binding`, because it doesn't do any such thing, to something like `authorized presenter list`, which would do exactly what it says on the tin, i.e., it would provide verifiers with a list of holder identifiers against which the presenting holder's identifier could be tested, which I'm confident could be implemented in a privacy-preserving, crypto-involving manner?

_Originally posted by @TallTed in https://github.com/w3c/vc-data-model/issues/1141#issuecomment-1587997653_

**Comment by brentzundel** [comment]
I'm not sure what concrete spec changes are being requested with this issue. The spec does not currently contain the term `holder binding`

**Comment by TallTed** [comment]
I am glad the spec does not contain this phrase. I am concerned that this phrase continues to occur regularly in issue and PR titles and discussions.

**Comment by brentzundel** [comment]
> I am concerned that this phrase continues to occur regularly in issue and PR titles and discussions.

I don't understand what this issue is intending to track and would appreciate more clarity.

If you are proposing that our work mode prohibit WG participants from using the term `holder binding` in issues and PR titles, then this issue should probably be raised in https://github.com/w3c/verifiable-credentials, though I doubt consensus to add such a prohibition could be achieved.

Or are you requesting the WG spend time working toward a resolution to stop using the phrase `holder binding`?

It is not clear to me what concrete result would resolve this issue.

**Comment by awoie** [comment]
IMO, since holder binding is no longer mentioned anywhere, we can close this issue.

**Comment by TallTed** [comment]
Well... It's not "no longer mentioned anywhere."

It's "not mentioned in the VCDMv2 document," though it remains in [8 issues](https://github.com/search?q=repo%3Aw3c%2Fvc-data-model+%22holder+binding%22++&type=issues&state=open) (including this one) and [1 pull request](https://github.com/search?q=repo%3Aw3c%2Fvc-data-model+%22holder+binding%22++&type=pullrequests&state=open).

If we intend to, and believe we can, keep it out of the documents we publish, I'm OK with closing this issue.

**Comment by awoie** [comment]
I don't think it is appropriate to fix what people put into their issues. I closed PR #1054 . IMO, we can close this issue.

**Comment by OR13** [comment]
This issue should be closed, I welcome PRs to address the holder term definition or it's use in the specification.

**Comment by TallTed** [comment]
The phrase "holder binding" suggests that a VC/VP can only be *held by* (and probably *transferred to*), i.e., is *bound* to, particular holders — but everyone who has advocated for a feature labeled with this name has *meant* that the VC/VP should only be accepted when *presented by* particular holders.

These are RADICALLY DIFFERENT meanings for this apparently simple label, and they will be (and have been, in this WG!) misunderstood.

That was the basis of my creating this issue.

I anticipate another several issues and/or PRs touching on the same thing, hopefully not during VCDMv2, but probably during the eventual VCDMv3.
