### ISSUE TITLE
Add language that there is generally no relationship between a VP and their VCs other than integrity protection

### ISSUE THREAD

**Issue by awoie** [w3c/vc-data-model#1165]
We should add some language that says that there is generally no relationship between a VP and their VCs other than integrity protection. Everything else is outside of the of the scope of this specification and subject to securing mechanisms or embedding protocols.

**Comment by brentzundel** [comment]
Now that #1164 has been merged, the spec includes the line 
> Unless additional requirements are defined by the particular securing mechanism or embedding protocol, a [verifier](https://w3c.github.io/vc-data-model/#dfn-verifier) cannot generally assume that the [verifiable presentation](https://w3c.github.io/vc-data-model/#dfn-verifiable-presentation) has any correlation with the presented [verifiable credentials](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential).

Does that change address this issue?

**Comment by awoie** [comment]
Yes, issue addressed. I thought it would have been closed automatically because it was referenced but it didn't. Closing issue.
