### ISSUE TITLE
[admin] Add PR Preview | Diff links

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/vc-data-model#117]
This makes reviewing PRs of spec text changes *much* simpler to review. It provides both Preview link and a Diff link (with highlight-able changes that can be "paged" through).
https://github.com/tobie/pr-preview

We use it in the Web Publishing WG ([example](https://github.com/w3c/wpub/pull/142)--see [Preview](https://pr-preview.s3.amazonaws.com/w3c/wpub/pull/142.html) & [Diff](https://pr-preview.s3.amazonaws.com/w3c/wpub/142/2fb4b0b...b85f92a.html)) and it helps conversations about changes immensely.

Cheers!

**Comment by msporny** [comment]
@liamquin Could you please hook up pr-preview to this repo? 

I haven't done it yet because I don't have Admin privileges. I'm happy to do it if someone grants admin privileges to me.

/cc @burnburn @stonematt

**Comment by liamquin** [comment]
I _think_ i've done all that's needed (a .pr-preview.json file). Please test and close, or grump at me some more as needed ;D
