### ISSUE TITLE
Ensure the base context doesn't constrain lower-maturity specifications

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-data-model#1175]
https://github.com/w3c/vc-data-model/pull/1158 will freeze the content of the base context (https://www.w3.org/ns/credentials/v2) when vc-data-model goes to REC. The base context currently includes definitions for terms like `DataIntegrityProof`, which is defined in https://www.w3.org/TR/vc-data-integrity/#dataintegrityproof rather than in the spec that's freezing the context, so if vc-data-integrity goes to REC _after_ vc-data-model, there's a chance that it would want to change the definition and wouldn't be able to because it was already frozen.

I think that implies that the vc-data-model REC should be delayed until all of the terms its context defines are also defined by Recommendations (or equivalent maturity levels published by other standards bodies). This may not actually be a delay if the specs are finished in the right order.

**Comment by OR13** [comment]
We discussed not including status list or data integrity terms in the v2 context.

The working group decided to include those terms to "make it easier for developers".

I don't agree that including the terms makes it easier for developers.

If we are at risk of delaying the core data model if there are objections to data integrity or status list, I prefer to not include them in the v2 context.

**Comment by selfissued** [comment]
It would be much cleaner to remove all dependencies on the "securing" specs from the core data model.  I suggest that we do this before going to Candidate Recommendation.

**Comment by mprorock** [comment]
I think the best approach is to only include terms in the core context that are defined in the core context - other specs can provide their own contexts if required

**Comment by mprorock** [comment]
The more I dig into this @brentzundel @Sakurann I think we need to prioritize ensuring nothing in the core data model is dependent in any normative fashion (directly or indirectly) on work outside the core data model.  Otherwise an issue with another spec could prevent the core data model from advancing

**Comment by OR13** [comment]
Potential solution discussed in

https://github.com/w3c/vc-data-model/pull/1149#issuecomment-1636302571

**Comment by msporny** [comment]
PR #1251 has been raised to address this issue. This issue will be closed once PR #1251 has been merged.
