### ISSUE TITLE
Add OPTIONAL to conformace section

### ISSUE THREAD

**Issue by awoie** [w3c/vc-data-model#1184]
> OPTIONAL is a normative word, but we were using the lowercase version of it (on purpose). We could also fix things by just using "OPTIONAL", as that's equivalent to "MAY".

@msporny According to the [Conformance](https://w3c.github.io/vc-data-model/#conformance) section, we only have the following:

> The key words MAY, MUST, MUST NOT, RECOMMENDED, SHOULD, and SHOULD NOT in this document are to be interpreted as described in [BCP 14](https://datatracker.ietf.org/doc/html/bcp14) [[RFC2119](https://w3c.github.io/vc-data-model/#bib-rfc2119)] [[RFC8174](https://w3c.github.io/vc-data-model/#bib-rfc8174)] when, and only when, they appear in all capitals, as shown here.

I know that OPTIONAL is used in IETF RFCs but I couldn't find it in the paragraph above. Should we add OPTIONAL there too? Or what is the reason it was not added?

_Originally posted by @awoie in https://github.com/w3c/vc-data-model/issues/1181#issuecomment-1621898806_

**Comment by msporny** [comment]
> I know that OPTIONAL is used in IETF RFCs but I couldn't find it in the paragraph above. Should we add OPTIONAL there too? Or what is the reason it was not added?

That paragraph is auto-generated by ReSpec based on the normative RFC language used throughout the document. So, if you don't use a certain RFC term, it's not added to that paragraph. If we use "OPTIONAL" (in all caps) in the document, ReSpec will modify that paragraph I pointed to and will add the word automatically to that paragraph.

So, no reason to modify that particular paragraph, it'll auto-update if we use the OPTIONAL language in the places where we use lowercase "optional" today.

We should close this issue given that ReSpec auto-generates that paragraph (and we have no control over it).

**Comment by awoie** [comment]
Closing issue based on @msporny reply.
