### ISSUE TITLE
Derived Credential Presentations

### ISSUE THREAD

**Issue by abhishekmaha23** [w3c/vc-data-model#1187]
I'm working on a blog post describing a basic (largely independent) implementation of an SSI use-case integrating with ZKPs (hopefully in a modern SNARK system) and I'm at this point in the specs:

``` json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "type": "VerifiablePresentation",
  "verifiableCredential": [
    {
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://www.w3.org/2018/credentials/examples/v1"
      ],
      "type": ["VerifiableCredential", "UniversityDegreeCredential"],
      "credentialSchema": {
        "id": "did:example:cdf:35LB7w9ueWbagPL94T9bMLtyXDj9pX5o",
        "type": "did:example:schema:22KpkXgecryx9k7N6XN1QoN3gXwBkSU8SfyyYQG"
      },
      "issuer": "did:example:Wz4eUg7SetGfaUVCn8U9d62oDYrUJLuUtcy619",
      "credentialSubject": {
        "degreeType": "BachelorDegree",
        "degreeSchool": "College of Engineering"
      },
      "proof": {
        "type": "AnonCredDerivedCredentialv1",
        "primaryProof": "cg7wLNSi48K5qNyAVMwdYqVHSMv1Ur8i...Fg2ZvWF6zGvcSAsym2sgSk737",
        "nonRevocationProof": "mu6fg24MfJPU1HvSXsf3ybzKARib4WxG...RSce53M6UwQCxYshCuS3d2h"
      }
  }],
  "proof": {
    "type": "AnonCredPresentationProofv1",
    "proofValue": "DgYdYMUYHURJLD7xdnWRinqWCEY5u5fK...j915Lt3hMzLHoPiPQ9sSVfRrs1D"
  }
}
```
The example provided uses the CL Signature method. Are there other examples or references available? 
I couldn't find any other signature schemes that have been used for this, and am struggling to track down/identify what the implementations from the VC Implementation Report use.

In addition, where may I find a repository of Credential templates for interoperability purposes?

**Comment by brentzundel** [comment]
The implementations in the VC Implementation report that supported the ZKP features used CL Signatures.
CL Signatures are still used by the Hyperledger Indy project and Sovrin. 

There is currently work in the VCWG on BBS Data Integrity signature suite that has a similar set of capabilities, as well as work at IRTF to define BBS more formally in a general setting.

**Comment by abhishekmaha23** [comment]
@brentzundel Thank you for these very relevant leads! This was an interesting rabbithole to go through - I was struggling a bit to find exactly the right search terms to find relevant signature schemes here.
It seems MattrGlobal has a working implementation of BBS+, and the field is seeing active work, also interesting research.

Any other directions I might be missing to apply selective disclosure beyond CL or BBS Signatures?

**Comment by brentzundel** [comment]
For an effort specific to selective disclosure you might want to check out the SD-JWT work (also at IETF), though the compatibility of SD-JWT with VC is still being worked out, if I understand correctly.

Do you feel that your questions have been answered sufficiently for us to close this issue?

**Comment by abhishekmaha23** [comment]
Thanks again, that helps also!
Closing the issue now.
