### ISSUE TITLE
Move Data Schemas to Basic Concepts section

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-data-model#1196]
[Data Schemas](https://w3c.github.io/vc-data-model/#data-schemas) is currently in the [advanced concepts](https://w3c.github.io/vc-data-model/#advanced-concepts) section.

I believe it is not more advanced than securing a credential, or representing the status of a credential both of which are in the [basic concepts](https://w3c.github.io/vc-data-model/#basic-concepts) section of the data model.

Given the adopted work item [vc-json-schema](https://github.com/w3c/vc-json-schema) I would like to propose moving the section to Basic Concepts to continue promote its usage and utility in the VC space. Notably, data schemas are already used in credential deployments such as [the EBSI project](https://ec.europa.eu/digital-building-blocks/code/projects/EBSI/repos/json-schema/browse), and upcoming deployments by TBD and others.

**Comment by brentzundel** [comment]
This makes sense to me. I would support a PR that makes this change.

**Comment by msporny** [comment]
Agreed, supportive of the change, given how commonly used JSON Schema is in the general developer ecosystem.

**Comment by msporny** [comment]
PR #1207 has been raised to address this issue. This issue will be closed once that PR is merged.
