### ISSUE TITLE
Document how VCs are processed as JSON today

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1201]
There are a variety of deployed systems that process VCs as JSON today. 

The v1.0 and v1.1 specification [provided clear guidance](https://www.w3.org/TR/vc-data-model/#contexts) on how to process a VC using only JSON tooling and a little extra logic (from the latest published VCDM v1.1 global standard):

> NOTE: Though this specification requires that a @context [property](https://www.w3.org/TR/vc-data-model/#dfn-property) be present, it is not required that the value of the @context [property](https://www.w3.org/TR/vc-data-model/#dfn-property) be processed using JSON-LD. This is to support processing using plain JSON libraries, such as those that might be used when the [verifiable credential](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials) is encoded as a JWT. All libraries or processors MUST ensure that the order of the values in the @context [property](https://www.w3.org/TR/vc-data-model/#dfn-property) is what is expected for the specific application. Libraries or processors that support JSON-LD can process the @context [property](https://www.w3.org/TR/vc-data-model/#dfn-property) using full JSON-LD processing as expected.

This guidance was removed in PR #1182 and it is [leading to confusion in the ecosystem](https://github.com/w3c/vc-data-model/pull/1088#issuecomment-1591275654); people are starting to believe that you can't process a VC in "pure JSON" mode, and that does not reflect the reality that organizations are doing just that today. Here are the use cases where VCs are processed in "pure JSON" mode today:

* When using the VC-JOSE-COSE specification to sign, processing performed is purely JSON-based.
* When performing JSON Schema validation (via vc-json-schema), processing performed is purely JSON-based.
* When serializing/deserializing VCs into document-oriented databases (or databases in general), processing performed is purely JSON-based (or text-based).
* When operating on the data in a software application, after verification is performed, processing performed is often JSON-based.

The specification used to be clear about this, and after PR #1182 was merged, is no longer clear about this reality. What was in the specification before should be improved. We need to document that the ecosystem is performing this sort of processing today on VCs and that it's an entirely legitimate way to process this data. IOW, JSON-LD processing is optional in a number of cases, and is only mandatory when you want to ensure that the semantics are well formed (and there are a number of use cases where you don't need to do that).

**Comment by msporny** [comment]
PR #1202 has been raised to address this issue. This issue will be closed if PR #1202 is merged.

**Comment by OR13** [comment]
@msporny which issue tracks the "value of JSON-LD" ?

**Comment by msporny** [comment]
> @msporny which issue tracks the "value of JSON-LD" ?

There isn't one yet, feel free to create one w/ the text that you'd like to see in that section.

Presently, we have this section in the specification:

https://w3c.github.io/vc-data-model/#json-ld

I expect that the text you want could go in that section.

**Comment by OR13** [comment]
@msporny I know we have a had a few conversations on this, if you or @iherman can add any details to https://github.com/w3c/vc-data-model/issues/1227 please do so.
