### ISSUE TITLE
proof property is not compacted with v2 context 

### ISSUE THREAD

**Issue by filip26** [w3c/vc-data-model#1204]
Hi,
I've run into a weird issue. The new `v2` context together with JSON-LD compaction algorithm does not compact `proof` property. See [JSON-LD playground example](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40id%22%3A%22https%3A%2F%2Fapicatalog%2Fcom%2Fvc%2Ftest-credentials%230001%22%2C%22%40type%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2018%2Fcredentials%23VerifiableCredential%22%5D%2C%22https%3A%2F%2Fwww.w3.org%2F2018%2Fcredentials%23issuer%22%3A%5B%7B%22%40id%22%3A%22https%3A%2F%2Fgithub.com%2Ffilip26%2Firon-verifiable-credentials%2Fissuer%2F1%22%7D%5D%2C%22https%3A%2F%2Fwww.w3.org%2F2018%2Fcredentials%23credentialSubject%22%3A%5B%7B%22%40id%22%3A%22did%3Aexample%3Aebfeb1f712ebc6f1c276e12ec21%22%7D%5D%2C%22https%3A%2F%2Fw3id.org%2Fsecurity%23proof%22%3A%5B%7B%22%40type%22%3A%5B%22https%3A%2F%2Fw3id.org%2Fsecurity%23DataIntegrityProof%22%5D%2C%22https%3A%2F%2Fw3id.org%2Fsecurity%23cryptosuite%22%3A%5B%7B%22%40value%22%3A%22eddsa-2022%22%7D%5D%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fcreated%22%3A%5B%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23dateTime%22%2C%22%40value%22%3A%222022-05-28T17%3A02%3A05Z%22%7D%5D%2C%22https%3A%2F%2Fw3id.org%2Fsecurity%23proofPurpose%22%3A%5B%7B%22%40id%22%3A%22https%3A%2F%2Fw3id.org%2Fsecurity%23assertionMethod%22%7D%5D%2C%22https%3A%2F%2Fw3id.org%2Fsecurity%23verificationMethod%22%3A%5B%7B%22%40id%22%3A%22https%3A%2F%2Fgithub.com%2Ffilip26%2Firon-verifiable-credentials%2Fverifier%2F0005-verification-key.json%22%7D%5D%2C%22https%3A%2F%2Fw3id.org%2Fsecurity%23proofValue%22%3A%5B%7B%22%40type%22%3A%22https%3A%2F%2Fw3id.org%2Fsecurity%23multibase%22%2C%22%40value%22%3A%22z2mAhYjqr36ENgi31zxc1S6rLnrFJBV9FL4cQPBH1DciYTwgEqNiJaUDeQ1WkxjwMx6wcKhwSrwKfybB8T3kmtYem%22%7D%5D%7D%5D%7D&context=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2Fns%2Fcredentials%2Fv2%22%2C%22https%3A%2F%2Fw3id.org%2Fsecurity%2Fdata-integrity%2Fv1%22%5D%7D)

**Comment by filip26** [comment]
It's caused by `@container`: `@graph` that has been discussed  here recently.

**Comment by dlongley** [comment]
The input isn't correct, the proof value must be contained within its own graph. I've made the adjustment [in this example](https://tinyurl.com/2e5frpnt).

**Comment by filip26** [comment]
@dlongley you are right! thanks.
