### ISSUE TITLE
Document issuer defined vocabulary and use of @vocab

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1210]
@decentralgabe wrote in https://github.com/w3c/vc-data-model/pull/1202/files#r1265764973 :
> Would it help to add a note here around the inclusion of @vocab into the core context making this a bit simpler?

**Comment by msporny** [comment]
There are a number of things that we've done to make it easier to work w/ VCs in a JSON-only mode. Use of `@protected`, use of `@vocab`, aliasing `@id` and `@type`, etc. We do talk about some of these mechanisms in these sections: 

* https://w3c.github.io/vc-data-model/#syntactic-sugar
* https://w3c.github.io/vc-data-model/#getting-started

... but, we don't mention "the issuer defined vocabulary" anywhere in the spec, and we probably should.

**Comment by iherman** [comment]
@msporny @decentralgabe I will come up with PR covering this (and #1217) to move things.

**Comment by msporny** [comment]
PR #1420 has been merged, closing.
