### ISSUE TITLE
Missing term in the vcdm spec

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-model#1216]
As reported in #1209, the `serviceEndpoint` term, though present in the vocabulary, does not have a formal specification in the VCDM specification (nor in the DID specification, although [it has been suggested](https://github.com/w3c/vc-data-model/pull/1209#discussion_r1270610876) that this may be a DID related term).

**Comment by brentzundel** [comment]
The definition I know of is here: https://www.w3.org/TR/did-core/#service-endpoints

**Comment by iherman** [comment]
I am happy to use that URL and be over with it, but it is a little bit strange to see this term in this vocabulary.

However, this is a layman's reaction. If there is an agreement to use that, I will make a PR for this.

cc @msporny @dlongley

**Comment by iherman** [comment]
Note #1230. If that PR is accepted and merged, it makes this issue moot, ie, can be closed.

**Comment by msporny** [comment]
As @brentzundel noted above... this is how we defined `service` and `serviceEndpoint` in DID Core... which shows that both of those terms are defined in the DID Core vocabulary, not the security vocabulary.

```
    "service": {
      "@id": "https://www.w3.org/ns/did#service",
      "@type": "@id",
      "@context": {
        "@protected": true,
        "id": "@id",
        "type": "@type",
        "serviceEndpoint": {
          "@id": "https://www.w3.org/ns/did#serviceEndpoint",
          "@type": "@id"
        }
      }
    },
```

IOW, I think we can close this issue because `service` and `serviceEndpoint` isn't defined by the security vocabulary.

**Comment by iherman** [comment]
> IOW, I think we can close this issue because `service` and `serviceEndpoint` isn't defined by the security vocabulary.

Which means merging #1230 ...

**Comment by iherman** [comment]
#1230 has been merged, I will close this comment.
