### ISSUE TITLE
Add link to Linked Data Best Practices 

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1217]
In https://github.com/w3c/vc-data-model/pull/1203#discussion_r1275176621 @awoie wrote:
> We should also provide a link to what it means to follow linked data best practices. 

This issue is to track the request by @awoie above.

Perhaps the best place to put the advice is in the Extensibility section.

**Comment by awoie** [comment]
The proposal would work for me.

**Comment by iherman** [comment]
@msporny I will come up with a PR to this (and #1210) to move things further along.

**Comment by msporny** [comment]
PR #1420 addressed this issue and has been merged, closing.
