### ISSUE TITLE
Privacy: Retention times

### ISSUE THREAD

**Issue by rigow** [w3c/vc-data-model#124]
The Specification should allow a holder and/or a requester to specify expiry and retention times.

**Comment by msporny** [comment]
At present, there is a section on Terms of Use: https://w3c.github.io/vc-data-model/#terms-of-use

There are two use cases here:

1. The holder specifies an expiry time for the credential, and
2. The verifier specifying a retention time for the credential.

The first is a part of the data model, the second is a part of the protocol (and may have an effect on the data model).

I think we can make the first item clear by adding an example into the specification. The second could be seen as a subset of the first use case.

I propose that we add an example in the Terms of Use section that enables a holder to specify a validity period for the provided credential.
