### ISSUE TITLE
Privacy: Anonymous credentials

### ISSUE THREAD

**Issue by rigow** [w3c/vc-data-model#125]
Verifiable claims should be usable while using anonymous credentials according to the Camenisch/Lysyanskaya - system:
https://link.springer.com/chapter/10.1007/3-540-44987-6_7

**Comment by David-Chadwick** [comment]
@rigow 
I know, I have a student working on this (with help from Jan) for his MSc project. I will report to the group how he gets on when he has finished in September.

**Comment by dlongley** [comment]
A related RWoT paper by Nathan George:

https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-spring2018/blob/master/topics-and-advance-readings/AttributeBasedCredentials_and_VariableLengthDataGraphs.md

**Comment by msporny** [comment]
Hey @nage or @talltree, you guys need to take this issue. We can't assign you for anything VC related, can you please get added to this repository. @liamquin can you help them do that?

**Comment by liamquin** [comment]
On Tue, 2018-03-13 at 15:17 +0000, Manu Sporny wrote:
> Hey @nage or @talltree, you guys need to take this issue. We can't
> assign you for anything VC related, can you please get added to this
> repository. @liamquin can you help them do that?

Invitations sent (github sends them by email so check spam mailbox if
needed!)

> 
-- 
Liam Quin, W3C, http://www.w3.org/People/Quin/
Staff contact for Verifiable Claims WG, SVG WG, XQuery WG
Improving Web Advertising: https://www.w3.org/community/web-adv/
Personal: awesome vintage art: http://www.fromoldbooks.org/

**Comment by msporny** [comment]
@nage, @talltree -- second ping on this issue, @liamquin has invited you to the W3C group. Please accept the invite and take this issue. This has Sovrin and CL Signatures all over it. :)

**Comment by nage** [comment]
There is active work going on in the fork at https://github.com/sovrin-foundation/vc-data-model. I expect more to discuss as we review which of these changes are necessary.

**Comment by burnburn** [comment]
@nage can you update?

**Comment by stonematt** [comment]
@nage and @talltree can you update us on this issue?

**Comment by talltree** [comment]
Although I have not been able to be on the calls recently, I know this has
been the subject of a lot of discussion with @nage and with the Evernym
folks cc'd on this message (all of whom are now official VCWG members).

Ball over to them.

=Drummond

**Comment by lovesh** [comment]
@burnburn @stonematt We proposed our changes in a [PR here](https://github.com/w3c/vc-data-model/pull/208). Then it was suggested to split our changes in multiple PRs so we raised [213](https://github.com/w3c/vc-data-model/pull/213) and [214](https://github.com/w3c/vc-data-model/pull/214)

**Comment by dhh1128** [comment]
I am currently working on an additional PR that embodies a subset of PR 208. I expect that there will be several PRs in addition to 213 and 214, before we are done.

**Comment by msporny** [comment]
This issue has moved to PRs and #237 -- closing issue so we don't have a duplicate.
