### ISSUE TITLE
Update/mint new JSON-LD context

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-data-model#127]
The existing https://w3id.org/credentials/v1 context is out of date in non-backwards compatible ways at this point. There are some legacy verifiable credentials that depend on it, so we should either mint a `v2` or come up with a new name (if the group finds that desirable).

**Comment by Drabiv** [comment]
The https://w3id.org/credentials/v1 context references https://w3id.org/credentials. This is the most important reference in the context, that should describe such properties as "claim", "credential", but it returns nothing. Just pointing out what needs to be fixed in the first place.

```
. . .
"cred": "https://w3id.org/credentials#",
. . .
"claim": {"@id": "cred:claim", "@type": "@id"},
"credential": {"@id": "cred:credential", "@type": "@id"},
. . .
```
