### ISSUE TITLE
Add @TallTed and @iherman to Editors list

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1273]
Just noting that our 2nd and 3rd most prolific contributors to the VCDM v2.0 specification are @TallTed and @iherman ... they should be recognized for their contributions by being added to the Editors list.

![image](https://github.com/w3c/vc-data-model/assets/108611/d530d538-2c5d-4f6a-8950-31e03315280b)

**Comment by iherman** [comment]
This was handled in #1354 (and has been merged). Marking pending close @brentzundel

**Comment by msporny** [comment]
We can just close this, the issue has been resolved.
