### ISSUE TITLE
Add standard (generic) JSON Schema for implementors to validate their verifiable credentials.

### ISSUE THREAD

**Issue by Drabiv** [w3c/vc-data-model#128]
While trying to implement Verifiable Credentials I faced a need for JSON Schema to validate my VCs against. It would be great to have community reviewed JSON schema appended to the spec for this purpose.

**Comment by David-Chadwick** [comment]
I agree that a schema for the JSON is needed, along with a standard way of extending the schema.

**Comment by msporny** [comment]
I think we should defer this feature until the next version of the specification for the following reasons:

* Digital Bazaar is using JSON Schema and no changes to the specification are required for this to happen.
* No one else has stepped forward to do an implementation of this feature nor write the PR for it.
* We can defer the feature safely and add it later as it's not vital for the operation of the VC ecosystem.
* We don't have enough implementation guidance based on real world deployments to do anything yet.

**Comment by dmitrizagidulin** [comment]
Decision at the Barcelona F2F meeting: Open an issue and add the JSON schema to the Implementation Guide. (I volunteered).

**Comment by dmitrizagidulin** [comment]
Issue opened on the Implementation Guide - https://github.com/w3c/vc-imp-guide/issues/1

This one can be closed.
