### ISSUE TITLE
Normative requirement for securing a VC or VP

### ISSUE THREAD

**Issue by andresuribe87** [w3c/vc-data-model#1282]
The current language in the section [Securing Verifiable Credentials](https://www.w3.org/TR/vc-data-model-2.0/#securing-verifiable-credentials) make it so that a VC or VP need not be secured. I think this is unintentional. 

We have normative text in the section https://www.w3.org/TR/vc-data-model-2.0/#conformance, but it doesn't use normative language. It does not require VC nor VPs to be secured. Specifically, we currently say

> Digital proof mechanisms, a subset of which are digital signatures, are required to ensure the protection of a [verifiable credential](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-credential). Having and validating proofs, which may be dependent on the syntax of the proof (for example, using the JSON Web Signature of a JSON Web Token for proofing a key holder), are an essential part of processing a [verifiable credential](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-credential).

They are required to ensure the protection, but protecting a VC or VP is not mandatory.

Do we want text like "verifiable credentials or verifiable presentations MUST be secured"? Or is my understanding incorrect?

**Comment by Sakurann** [comment]
I agree we need a clear normative statement on this.

**Comment by decentralgabe** [comment]
+1 verifiable verifiable credentials needs to be normative
