### ISSUE TITLE
(Editorial) Use a three level deep TOC in the VCDM spec

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-model#1306]
At the moment, the TOC setting in the document stops at two levels (i.e., §A or §A.B). I would propose to add a third level (ie, §A.B.C). Our spec is complex, and many important sections are on that level (e.g., the ones discussed in PRs like #1302) and it makes it very difficult to read the spec. I realize the TOC becomes fairly complex: so be it...

**Comment by msporny** [comment]
I have implemented a 3-level deep TOC in add0ade10588842e46ee3169497b61433b950b30.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-07-vcwg#section4-1) on 2024-02-07

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.1.  (Editorial) Use a three level deep TOC in the VCDM spec (issue vc-data-model#1306)

_See github issue [vc-data-model#1306](https://github.com/w3c/vc-data-model/issues/1306)._




**Brent Zundel:** Right now we have 2 levels in the TOC and ivan is recommending 3. How do folks feel?  

**Manu Sporny:** I dont like the three levels. It makes the TOC messy.  

**Ivan Herman:** I have major difficulties finding stuff in this spec.  

**Ted Thibodeau Jr.:** If we have a 2 level TOC we should make the document two levels deep. unless we add an index.  

**Brent Zundel:** is anyone willing to do this work?  

**Manu Sporny:** I can do the work. I am trying to see how sad it makes me. You can assign it to me.  

**Brent Zundel:** with your statement we don't have consensus.  

**Ted Thibodeau Jr.:** pretty sure the work require is changing a line in the HTML source.  

**Brent Zundel:** Ted are you volunteering.  

**Manu Sporny:** Already done this. They have updated respec to make the TOC items smaller. I'm ok with this change.  

</details>
