### ISSUE TITLE
Updating figures 6 and 7

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-model#1318]
As discussed in https://github.com/w3c/vc-data-model/issues/1248, both [Figure 6](https://www.w3.org/TR/vc-data-model-2.0/#info-graph-vc) and [Figure 8](https://www.w3.org/TR/vc-data-model-2.0/#info-graph-vc) are incorrect and misleading. I have come up with an alternative for both which is also in line with exact semantics of the vocabulary. I can do a PR at some point, but I thought it is worth discussion it in an issue whether approach works.

Compared to the current diagrams:

- the nodes properly separate literals from objects (ie, entities with their own URLs); it was messy in the original
- the term "graph" is reserved for what is indeed a graph in the RDF sense, and the property arrows reflect these choices. The separate entity (eg, for claim) is a "conceptual" partition of the terms, but not reflected in the properties.
- stylistically, I keep to black-and-white so that these diagrams could work properly with various dark modes; that is to be experimented with a separate PR (if it gets to the point).

Note that the description in the text should also be reviewed as for the usage of "graph". As I said, if we keep to the precise vocabulary meaning, the "claim" is not a separate graph (in the RDF sense, that is), so we should probably change the description.

Here are the proposed new versions:

![Figure 6](https://github.com/w3c/vc-data-model/assets/520723/985aaf44-41d2-4e1a-b0ee-adb9be79f91e)

and

![Figure 8](https://github.com/w3c/vc-data-model/assets/520723/41085318-d462-4ae9-9eba-95a095c83fb2)

**Comment by dlongley** [comment]
I'm concerned about the "Claim" label -- as each of the other statements are also claims. What if the label said "Example Claim" or "One Claim" ... or something? Maybe it's best to just remove that particular circle. It also seems to imply there's a separate container thing there of some *other* type when there isn't.

**Comment by iherman** [comment]
See #1321 for a PR.

Also, due to my combined stupidity and clumsiness, some comments have been misplaced. The real target for 
https://github.com/w3c/vc-data-model/issues/1248#issuecomment-1770490256 and https://github.com/w3c/vc-data-model/issues/1248#issuecomment-1771154697 and, I suppose, https://github.com/w3c/vc-data-model/issues/1248#issuecomment-1771100088 is this current issue...

**Comment by msporny** [comment]
PR #1326 was raised to address this issue, closing.
