### ISSUE TITLE
Recommend how authors set default language and direction

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1335]
Part of the Internationalization Horizontal Review noted that we need to suggest how a Verifiable Credential's default language and direction is specified. This issue is to ensure that we specify how this is done before we enter the CR phase.

**Comment by msporny** [comment]
Implement [Option B](https://github.com/w3c/vc-data-model/issues/1264#issuecomment-1712807665).

**Comment by msporny** [comment]
PR #1339 has been raised to address this issue. This issue will be closed once PR #1339 has been merged.

**Comment by aphillips** [comment]
Adding our tracking label, since #1264 was tracked and is closed in favor of this issue.

**Comment by msporny** [comment]
PR #1339 has been merged, closing.
