### ISSUE TITLE
credentialSubject doesn't say how to identify the "subjects" of the verifiable credential.

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-data-model#1341]
https://w3c.github.io/vc-data-model/#credential-subject says

> The value of the credentialSubject [property](https://w3c.github.io/vc-data-model/#dfn-property) is defined as a set of objects that MUST contain one or more claims that are each related to a [subject](https://w3c.github.io/vc-data-model/#dfn-subjects) of the [verifiable credential](https://w3c.github.io/vc-data-model/#dfn-verifiable-credential).

To check that MUST, we have to be able to tell what the subjects of the VC are, but the "subject" link just says

> A thing about which [claims](https://w3c.github.io/vc-data-model/#dfn-claims) are made.

Which isn't related to VCs at all.

I'm guessing that this text was written with the JSON data model in mind, and hasn't been updated for JSON-LD. I think the values of the `credentialSubject` property _are_ the subjects of the VC, and then the graph can or must include some claims about those subjects.

**Comment by msporny** [comment]
> I think the values of the credentialSubject property are the subjects of the VC, and then the graph can or must include some claims about those subjects.

Yes, that's the correct interpretation. I'll make an attempt at a revision that makes the statement more directly testable.

**Comment by msporny** [comment]
PR #1346 has been raised to address this issue. This issue will be closed once PR #1346 is merged.

**Comment by msporny** [comment]
PR #1346 is merged, closing.
