### ISSUE TITLE
Confused by "all times MUST be specified as offsets against Universal Coordinated Time (UTC)."

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-data-model#1343]
In https://w3c.github.io/vc-data-model/#representing-time, we have

> In order to reduce misinterpretations between different regions, all times MUST be specified as offsets against Universal Coordinated Time (UTC).

I thought that might be saying that the timezoneFrag had to be just "Z", but the example in the next paragraph has `-07:00`. Then I thought you might be excluding use of named timezones, but dateTimeStamp doesn't allow those at all. So what constraint is this line trying to add?

**Comment by msporny** [comment]
The normative statement is attempting to say "You MUST NOT specify a datetime that does not include a time zone offset.". That is, `dateTime` allows times like `2023-01-01T00:00:00` (no timezone offset against UTC), which means you interpret the time according to your local timezone (which could be off by 14 hours -- I think -- based on weird daylight savings times differences on opposite sides of the world). 

I'll try to raise a PR that's more clear with the intent... feel free to propose some text that would have not led to you being puzzled by the statement.

**Comment by jyasskin** [comment]
I think you just don't need anything normative here, now that the spec uses `dateTimeStamp` instead of `dateTime`.

**Comment by msporny** [comment]
PR #1344 has been raised to address this issue. This issue will be closed once PR #1344 has been merged.

**Comment by msporny** [comment]
> I think you just don't need anything normative here, now that the spec uses `dateTimeStamp` instead of `dateTime`.

The statement is meant to cover /any/ time value expressed in a VC. I understand that is quite a reach for a spec, we could downgrade it to a SHOULD, or get rid of it.

Thoughts @aphillips and @r12a?

**Comment by jyasskin** [comment]
Ooooh. That's plausible, but I'd expect it to be in a separate section that talks about the claims that a VC can make, rather than a subsection of the `validFrom` and `validUntil` section.

Making this a MUST increases the difficulty of having a verifier enforce that a document is conformant, since it says that the verifier has to recognize all the ways a VC might encode a time, and check that those ways include a timezone. E.g. do verifiers have to notice that a field contains an encoded ASN.1 [GeneralizedTime](https://en.wikipedia.org/wiki/GeneralizedTime)?

**Comment by aphillips** [comment]
I commented on the PR, but I'll comment here as well: I agree that there is a problem with MUST potentially invalidating otherwise-useful credentials. I generally recommend that specs use MUST for generators but then provide instructions for receivers (in this case, lack of an offset should be interpreted as UTC).

Offsets are not time zones. When serializations become available that provide zone IDs (see for example [SEDATE](https://datatracker.ietf.org/doc/draft-ietf-sedate-datetime-extended/)'s update of 3339), then these should be recommended instead.

**Comment by msporny** [comment]
@jyasskin wrote:
> Ooooh. That's plausible, but I'd expect it to be in a separate section that talks about the claims that a VC can make, rather than a subsection of the `validFrom` and `validUntil` section.

Yes, understood. We don't have a section like that in the spec at the moment... and maybe that's an indication that this normative statement is an overreach. We've also received guidance from I18n (@aphillips) that we should make these sorts of statements inline, where it makes sense to do so.

I think what I'm going to do is:

* Clarify that we're talking about /other/ time claims a VC makes and that issuing software SHOULD encode w/ offsets relative to UTC.
* Clarify that verifying software MUST interpret a time value that does not specify an offset as "Z" (UTC).

@jyasskin wrote:
> Making this a MUST increases the difficulty of having a verifier enforce that a document is conformant, since it says that the verifier has to recognize all the ways a VC might encode a time, and check that those ways include a timezone. 

Yeah, and we don't want to do that... maybe we should say "for time values that are XML Schema dateTimes or dateTimeStamps"? It's a bit repetitive, but given that this has been a point of interop failures in the past (not mentioning an offset relative to UTC), we do need to say something this time around.

@aphillips wrote:
> I agree that there is a problem with MUST potentially invalidating otherwise-useful credentials. I generally recommend that specs use MUST for generators but then provide instructions for receivers (in this case, lack of an offset should be interpreted as UTC).

Yeah, agreed. I think I'm going to downgrade to "producers SHOULD generate w/ offset relative to UTC for any time value capable of expressing an offset" and "consumers MUST presume 'Z' (UTC) if a time zone offset isn't provided". I think that covers our bases w/o getting into intricacies wrt. things like ASN.1 generalized time... if your verifier software understands that, and if an offset isn't provided, you presume UTC... and ideally, the issuer software clearly specified an offset relative to UTC.

**Comment by msporny** [comment]
PR #1344 has been merged, closing.
