### ISSUE TITLE
Reference or attach credential in another credentials

### ISSUE THREAD

**Issue by Drabiv** [w3c/vc-data-model#135]
This issue is a part of general "Reference and Attach data in credential" issue #126 

There should be a standard way to reference or attach credential in another credential. 

Let's say, a supermarket chain issued "Permit to buy alcohol" to its customer and want to reference/attach "Proof of Age" credential into their permit credential. 

Proposed solution.

Hash referenced credential and reference it as proposed below:
```
"reference": [ 
{
      "id": "18EE24150DCB1D96752A4D6DD0F20DFD8BA8C38527E40AA8509B7ADECF78F9C6",  
      "type": [ "Credential", "Passport" ],
      "purpose": [ "Other" ],
      "hash": "18EE24150DCB1D96752A4D6DD0F20DFD8BA8C38527E40AA8509B7ADECF78F9C6",
      "location": [ "http://example.com/example789" ]
}]
```

Attach "Proof of Age" credential into "Permit to buy Alcohol" credential directly. Like this:
```
"reference": [ 
{
      "id": "ff227bae-dacf-4ef0-94be-b2550ab2ee0q",  //reference to another credential, located internally (attached into current credential)
      "type": [ "Credential", "ProofOfAge" ],
      "purpose": [ "Other" ],
      "hash": "18EE24150DCB1D96752A4D6DD0F20DFD8BA8C38527E40AA8509B7ADECF78F9C6",
      "location": [ "$.attachment[:].id=ff227bae-dacf-4ef0-94be-b2550ab2ee0q" ]
}]

  "attachment": [{
      "type": [ "Credential", "ProofOfAgeCredential" ],
      "content": {
           "id": "ff227bae-dacf-4ef0-94be-b2550ab2ee0q",
           "type": [ "Credential" ],
           "issuer": "did:example:example.gov",
           "issued": "2018-03-03",
           "claim": {
                "id": "did:example:123xxx789",
                "ageOver": 21
            },
           "proof": [{
                "type": "RSA...",
                "created": "2018-03-03T21:10:38Z",
                "creator": "did:example:example.gov",
                "nonce": "ea227bae-dacf-4ef0-94be-b2550ab2ee0f",
                "signatureValue": "g4j9UrpHM4/uu32NlTw0HDaSaYF2sykskfuByD7UbuqEc"
           }]
      }
 } ]
```

**Comment by dlongley** [comment]
Note to self: link this to existing issues.

**Comment by David-Chadwick** [comment]
@Drabiv The problem with the Reference solution is that it requires the verifier to go out to the Internet to retrieve the referenced credential, which can lead to DDOS attacks or implementors simply asking the user, what do you want to do now, Continue without fetching the referenced VC or Reject the presented VC.
Attachment does not suffer from this problem.

**Comment by Drabiv** [comment]
@David-Chadwick I agree. IMO, both (how to reference VC and how to attach VC) should be clarified in the spec. Attachments will not be easy to read for humans, hence some issuers will prefer to reference VC. Also, and probably most importantly reference is better for privacy.

**Comment by David-Chadwick** [comment]
@Drabiv Unless I have missed something, I dont know why reference is better for privacy. I am assuming that the holder will transfer the VC encrypted to the verifier via TLS or similar, so both parties will know the entire contents of the VC regardless of whether it is referenced or attached, and nobody else will.

**Comment by Drabiv** [comment]
@David-Chadwick there can be a lot of cases when someone would like to reference credential, and be able to selectively disclose it.
    For example, there is a birth certificate of a child, where parents' names are mentioned and parents passports referenced. Let's say one parent goes to some organization to register there their child, and the organization wants to have both passports of parents. In this case both parents will have to provide additional permissions to organization to access their passports. So both parents will be aware that such and such organization wanted to get access to their passports, for such and such reason, and that this oranization now stores their passports in their archive. Maybe not the best example, but I hope it illustrates the point.
    It is also better for security purposes. If passports were attached into birth certificate, and this certificate got into the wrong hands, they will not get access to parents passports. 

    Also, it might be just not practical to attach VCs. Let's say I have a diploma and diploma supplement. It states that based on my completion of 100 courses with such and such marks I am granted the degree. The diloma supplement lists all completed courses. Now, it can also reference to certificates of completion to all courses. Hence there is no need to attach 100 certificates into the supplement.

**Comment by David-Chadwick** [comment]
@Drabiv Selective disclosure is a separate issue to attach/reference. I dont know if anonymous credentials will work if they are attached and given to someone else to selectively disclose their properties. I suspect not since the subject has a private key used for disclosure and he/she will not give this away. However, selective disclosure can be utilised by issuing atomic VCs, and attaching the single atomic VC to another one. So one would not attach a passport to a birth cerificate, but only the atomic attribute that is required by the verifier.

**Comment by Drabiv** [comment]
@David-Chadwick I might be wrong using "selective disclosure" term as maybe it has some specific use I am not aware of. 
What I am trying to convey is maybe better illustrated with this scenario:
A hospital wants to issue birth certificate. In this certificate the hospital wants to add parents' names and also uniquely identify parents by referencing their passports. 
When birth certificate is being used/verified, a parent might decide to provide/disclose their  passport or not. 
A full algorithm of birth certificate verification in this case will be: verifier gets birth certificate and verifies its content, it sees that parent names where populated based on passports, verifier sees pointers to locations (end point of Credential Provider service) where passports might be and their hashes to check them. If verifier decides to get these passports it follows the references and requests to get them. Credentials owners - parents will see request and decide whether to disclose their passports or not.
This might be not the best example, but anyway, IMO there should be a universal clearly described way to reference (point to) one verifiable credential from another verifiable credential. 
For example, this is clearly needed in case of Diploma Supplement.

**Comment by Drabiv** [comment]
@David-Chadwick Ok, another example – reference from short live crdential to longer live credential – from Access Card (to office building) to Passport. Let's say company issued access card to employee based on his passport or employment contract.

> ...inside the birth certificate is the name of the parent, and a pointer to the address that can be contacted in order to ask it to validate the name (with an appropriately trusted credential).

Yes, this is actually / in effect a reference to credential that I want to have. 

As I propose in the example below, the JSON object describes a reference to credential with id="ff227bae-dacf-4ef0-94be-b2550ab2ee0q", hash of the credential = "18EE24150DCB1D96752A4D6DD0F20DFD8BA8C38527E40AA8509B7ADECF78F9C6". To get the credential one has to go to address "http://example.com/example789"  and retreive it from there or ask for it from there.
```
"reference": [ 
{
      "id": "ff227bae-dacf-4ef0-94be-b2550ab2ee0q",  
      "type": [ "Credential", "Passport" ],
      "purpose": [ "Other" ],
      "hash": "18EE24150DCB1D96752A4D6DD0F20DFD8BA8C38527E40AA8509B7ADECF78F9C6",
      "location": [ "http://example.com/example789" ]
}]
```

**Comment by David-Chadwick** [comment]
@Drabiv There is a difference between a reference to a credential (which you suggested) and a reference to an address where a property/attribute can be validated. The former points to a specific credential, the latter to either a subject or a holder or an issuer that can return a credential to validate the attribute. The level of indirection provided by the latter gives greater flexibility and caters for revocation and expiration of credentials, which the former does not.

**Comment by David-Chadwick** [comment]
@Drabiv I think the best way to link credentials together in the way you require is via the verifiable profile that the holder sends to the verifier. Credentials should either embed supporting information e.g. terms of use, or contain references to where it can be found e.g. revocation information. Currently the only example I have of one credential embedding another credential is when the latter is delegated to the former, and former cannot outlive the latter.

**Comment by Drabiv** [comment]
@David-Chadwick I think that notion of profile should be dropped from the spec (it is confusing), instead attachments and references should be used (more simple and straightforward). Actually, the origin of this issue is in issue #126 and the original name of the issue #126 was "Reference and Attachment instead of Profile ..."

**Comment by stonematt** [comment]
@Drabiv I'm not sure relabeling a concept it the right direction to go.  The notion of a Profile is to allow a Holder/Subject to collect credentials for presentation to a verifier.  They may or may not be interconnected as a references, not as attachments.  In the event that they're simply a stack of documents submitted together, the Profile is the container that can be signed and managed as as single object for the verifier to understand.

That's not to say that it's solves all our needs in the area of References and Attachments, I'm just not convinced we should throw it away.

**Comment by Drabiv** [comment]
@stonematt Profile is in essence a bundle of credentials. I think it will be more correct and convenient to have generic approach to bundling credentials by using references and attachments. 
Then when we have references and attachments, the concept of Profile (a bundle of credentials about subject) becomes redundant.

**Comment by stonematt** [comment]
@Drabiv I see the need for a Credential to reference another.  I also see the need for Credentials to "attach" or embed other Credentials, particularly in the evidence scenarios.  In both of those cases, there  is a "root" credential that is a the key reference.  What do you call the bundle of Credentials presented together that are simply rooted on the person/subject?  To date, Profile (soon to be called Presentation) has been that artifact of aggregated credentials.  The term Profile has been confusing and misinterpreted, as a results, we've debating to relabel these bundles as "Presentations".  IOW "These n Credentials are presented together."  It may, in fact, be the attachment mechanism you're envisioning.

**Comment by Drabiv** [comment]
@stonematt actually, I do not have a strong opinion on how to call Profile/Presentation. IMO it should be replaced with references/attachments altogether. Although, if the concept of Profile/Presentation needs to exist I would call it "Bundle". "Presentation" name might be confused with the concept of visual presentation of JSON data to end users in the form of HTML/SVG. I will propose "Bundle" name in #163.
Although my spoken English is far from perfect, I'd love to join teleconference this or next week. Just need to publish example application that uses references/attachments and visual presentations in VCs in the way I describe here.

**Comment by msporny** [comment]
I'm not seeing consensus forming around the suggestion that we need a new mechanism to reference separate credentials. I suggest we close this issue as it doesn't seem to be making any progress.

**Comment by Drabiv** [comment]
I am against closing this issue. The absense of consensus does not mean that there is no issue or demand to fix this issue.
In Validbook we have a graph of credentials that reference each other or are attached in each other. 
I have proposed a way how to do this [here](https://github.com/w3c/vc-data-model/issues/135#issue-307175973), but I do not held to it dearly. 
If someone has another, better proposal on how to reference or attach credentials from another credential, or can demostrate how to do it with current specs, I will be glad to accept it. 
Otherwise I am against closing this issue.

**Comment by msporny** [comment]
> I am against closing this issue.

Ok, we'll leave the issue open.

**Comment by burnburn** [comment]
@Drabiv , your comments have several times included specific suggestions for substantive changes to the specification.  Unfortunately, we cannot accept substantive contributions from you until you have made the IPR commitments that all other members of this group have made.  We would love to have you join the Working Group!  You can find information on those commitments and how to join the Working Group at https://www.w3.org/2004/01/pp-impl/98922/status .

**Comment by Drabiv** [comment]
@burnburn I have  submitted a W3C Invited Expert Application as I am not an employee of W3C memeber organization. When/if it is approved I will apply to join the group as IE. Thank you!

**Comment by liamquin** [comment]
@Drabiv I've reviewed your application and sent you some questions, thank you very much for that

A quick note (for you and for anyone else)... Our W3C policy is that we can't normally accept invited experts from organizations that would normally be expected to join W3C - partly because it's how the work is funded but also becuse of software patents the organization might own. So we would like to get into a position where we can welcome your contributions and participation, which means we'll need to see whether you're employed by a company that's working in the area and might have intellectual property rights over the techniques you're proposing that could affect other implementors.

If necessary there's a mechanism where your employer can sign something to say they waive any patent rights in regard to implementations of the specs you're working on within the W3C. 

We have to be really careful about this as it is a real problem.  Feel free to ask me directly if you have any questions about how it works (you have my email now, as I replied to your application).

**Comment by dlongley** [comment]
@Drabiv,

> I have proposed a way on how to do this here, but I do not hold on to it dearly.
If someone has another, better proposal on how to reference or attach credentials from another credential, or can demostrate how to do it with current specs, I will be glad to accept it.

I disagree with your technique for the reasons [stated here](https://github.com/w3c/vc-data-model/issues/126#issuecomment-374639077). In short, adding a generic "reference" or "attachment" property that carries no semantics is an anti-pattern in my view.

The current data model enables issuers to create verifiable credentials with an unbounded variety of claims about other credentials or holders of credentials. This means that you should be able to use our data model extension mechanism to create a vocabulary for SURLHI style credentials that includes properties that users could take advantage of to address your use case. As there are no clear semantics given for the proposed properties (or there seems to be an implied reliance on your use case for any to exist), I do not think they should be added to the core vocabulary.

I recommend we close the issue for that reason -- not because your use case is not supported, but rather, because it is, through the extension mechanism. I suspect there are some implied semantics that "reference" or "attachment" somehow enhance one's likelihood of deciding that a particular subject is a unique human being -- but, of course, this is specific to your use case, not the data model in particular.

I recommend that your extension make these semantics more explicit using a term like `surlhiEvidence` or something along those lines, rather than the generic "reference". You could even reuse `evidence` (which is core) and create a type like `SurlhiIndicator` or something along those lines.

If we need anything in the spec, it would be a section giving some guidance to issuers on how to extend the data model (i.e. how to write an extension). That I would support and I think it's becoming clear from several of these issues that we need to add that section.

**Comment by Drabiv** [comment]
@dlongley I still do not understand the following:
1. how to securely reference credential from a credential 
2. how to attach credential into credential
2. why proposed Reference, and Attachment properties are not good

>I disagree with your technique for the reasons stated here. In short, adding a generic "reference" or "attachment" property that carries no semantics is an anti-pattern in my view.

I am OK to use another technique. Please, describe it or point me to it (see use cases that I am looking to satisfy below).

This issue is raised not only because of SURLHI Endorsements use case, but for many other more common use cases, that Validbook Statements (based on VC standard) plan to satisfy.

Use cases where reference, attachment needed:
- Contract with attached ID documents. For example, here is contract - http://futurama1x.validbook.org/statements/templates/Wedding%20Photography%201-13 attach (or  securely reference)  into it digital passports of contractual parties. Attaching ID documents to contracts is a very common practice in real life.
- Student Card. Issue student card based on passport/ID card. Reference/attach passport in student card.
- Library Card. Issue library card based on student card. Reference/attach student card in library card.
- Statement of Incorporation. 2 companies merge. Issue new Statement of Incorporation and reference/attach statements of incorporation of companies that merge.
- Court Decision. Issue court decision and reference/attach to it witness statements, expert statements, plaintiff statement, defendant statement.
  
IMO, proposed Reference and Attachment properties is very _simple_ and practical way to reference/attach credentials and other data. 
Also, it allows to bundle credentials under one credential, which IMHO is more elegant way  to create collections of credentials, than current arbitrary "Presentation" (former "Profile") data structure.

On a theoretical note, I think digital credentials should be foremost understood as nodes in a graph of credentials. When you receive such digital credential-node, you can traverse its graph, provided you have proper permissions. As a result of such traversal you will be able to understand if you can trust the credential or not. Isolated credentials, that are not part of the graph will not be trusted. When we look at credentials in this way (as nodes in a graph) we can clearly see that there should be a simple, well described standard way to securely reference credentials.

**Comment by msporny** [comment]
@msporny to create a PR that adds a new section to the Advanced Concepts section talking specifically about how to link to external documents and ensure the integrity of the linked document.

**Comment by Drabiv** [comment]
@msporny I am willing to work on (add to specifications) examples of 
- Contract w/ referenced/attached ID documents; 
- Access/Student/Library Card (VC to access resources - enterence to building, student privilages, library privilages)
I think these are very commonplace and to be in demand use cases. Let me know if examples for them are appropriate in specs.

**Comment by kimdhamilton** [comment]
@Drabiv I have a need for the same concept you described in #163, i.e. a verifiable view/display of the credential as a hash embedded in the JSON. I'd like to help push this forward in any way I can. Let me know if you'd like to discuss; otherwise, I'll be happy to help PR your changes.

**Comment by Drabiv** [comment]
@kimdhamilton this is great! This concept comes down to defining a standard way to add hash value to VC JSON and describing how that value was created and where presentation that was used to create this hash is located.
I have proposed a way to do it in the issues #126, #136.  
Manu has suggested how this can be done via extensions without changing current data model - https://github.com/w3c/vc-data-model/issues/136#issuecomment-403316353

I think it would be also very beneficial to have a standard way to embedd VC JSON into HTML and SVG so that they can be easily rendered by any browser. See examples -http://futurama1x.validbook.org/statements/templates. Happy to talk more about this.

**Comment by msporny** [comment]
@kimdhamilton and @gannan worked on a paper at RWoT7 called Resource Integrity Proofs that enables this: 

https://github.com/WebOfTrustInfo/rwot7/blob/master/draft-documents/resource-integrity-proofs.md

So the general problem is "solved", but there is not spec text, the RIP stuff is a separate document that's not a W3C spec yet, this WG has no charter deliverable for it, and thus all we would be able to do is refer to that document. 

I suggest we put a note about this in an "Implementation Guidance" document.

**Comment by brentzundel** [comment]
Decision at Barcelona F2F: Move to the implementation guide repo and close

**Comment by brentzundel** [comment]
to clarify, that means an issue needs to be created in the implementation guide repo for this.

**Comment by brentzundel** [comment]
@dlongley this issue is assigned to you. Are you able to take the work items from Barcelona?

- [ ] Create an issue to track this in the implementation guide repo
- [ ] Close this issue

**Comment by burnburn** [comment]
Created https://github.com/w3c/vc-imp-guide/issues/4 in Imp-Guide to continue this.  Closing.
