### ISSUE TITLE
Broken reference to LD-PROOFS

### ISSUE THREAD

**Issue by rogargon** [w3c/vc-data-model#137]
The reference to LD-PROOFS (https://github.com/w3c/vc-data-model/blob/gh-pages/common.js#L39) is broken. 

The linked page does not exist (404): 
https://w3c-ccg.github.io/ld-proofs/

**Comment by dlongley** [comment]
Yes, we still need to create that document as one spec lower in the stack than [LD Signatures](https://w3c-dvcg.github.io/ld-signatures/), i.e. it will include what is common for all LD Proofs, for which signatures are just one kind.

**Comment by msporny** [comment]
This has been fixed in the latest spec, closing.
