### ISSUE TITLE
Bug in the context file?

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-model#1373]
Consider a skeleton VP content:

```
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ],
  "type": "VerifiablePresentation",
  "verifiableCredential": [{
    "@context": [
      "https://www.w3.org/ns/credentials/v2"
    ],
    "id": "http://university.example/credentials/1872",
    "type": "VerifiableCredential",
    "issuer": "https://university.example/issuers/565049"
  }]
}
```

per specification, the N-quads equivalent should be something like (I use CURIEs to make it more readable):

```
_:vp rdf:type cred:VerifiablePresentation .
_:vp cred:verifiableCredential _:credGraph .
<http://university.example/credentials/1872> rdf:type cred:VerifiableCredential _:credGraph .
<http://university.example/credentials/1872> cred:issuer <https://university.example/issuers/565049>  _:credGraph.
```

However, what I get [on the playground](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2Fns%2Fcredentials%2Fv2%22%5D%2C%22type%22%3A%22VerifiablePresentation%22%2C%22verifiableCredential%22%3A%5B%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2Fns%2Fcredentials%2Fv2%22%5D%2C%22id%22%3A%22http%3A%2F%2Funiversity.example%2Fcredentials%2F1872%22%2C%22type%22%3A%22VerifiableCredential%22%2C%22issuer%22%3A%22https%3A%2F%2Funiversity.example%2Fissuers%2F565049%22%7D%5D%7D):

```
<http://university.example/credentials/1872> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2018/credentials#VerifiableCredential> .
<http://university.example/credentials/1872> <https://www.w3.org/2018/credentials#issuer> <https://university.example/issuers/565049> .
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2018/credentials#VerifiablePresentation> .
_:b0 <https://www.w3.org/2018/credentials#verifiableCredential> <http://university.example/credentials/1872> .
```

i.e., the "enclosing" graph does not appear.

This is either a bug in the `@context` file or the playground. If the former, it is the WG's job to solve it...

Do I miss something?

@dlongley @BigBlueHat @davidlehn @pchampin

**Comment by BigBlueHat** [comment]
@iherman fwiw, @gkellogg's [Distiller](http://rdf.greggkellogg.net/distiller?command=serialize&format=jsonld&output_format=nquads) creates these n-quads from the same JSON-LD...so there may indeed be a bug in the playground.

Here are the n-quads from the Distiller--which match what you were after:
```turtle
_:g524580 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2018/credentials#VerifiablePresentation> .
_:g524580 <https://www.w3.org/2018/credentials#verifiableCredential> _:g524600 .
<http://university.example/credentials/1872> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2018/credentials#VerifiableCredential> _:g524600 .
<http://university.example/credentials/1872> <https://www.w3.org/2018/credentials#issuer> <https://university.example/issuers/565049> _:g524600 .
```

I'll do some more direct testing with `jsonld.js` (which is used on the Playground), and see how deep the rabbit hole goes. @davidlehn may have other thoughts.

**Comment by iherman** [comment]
> @iherman fwiw, @gkellogg's [Distiller](http://rdf.greggkellogg.net/distiller?command=serialize&format=jsonld&output_format=nquads) creates these n-quads from the same JSON-LD...so there may indeed be a bug in the playground.
> 
> Here are the n-quads from the Distiller--which match what you were after:
> 
> ```turtle
> _:g524580 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2018/credentials#VerifiablePresentation> .
> _:g524580 <https://www.w3.org/2018/credentials#verifiableCredential> _:g524600 .
> <http://university.example/credentials/1872> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2018/credentials#VerifiableCredential> _:g524600 .
> <http://university.example/credentials/1872> <https://www.w3.org/2018/credentials#issuer> <https://university.example/issuers/565049> _:g524600 .
> ```
> 
> I'll do some more direct testing with `jsonld.js` (which is used on the Playground), and see how deep the rabbit hole goes. @davidlehn may have other thoughts.


Phew. From the point of view of VCDM I am relieved (and also from the point of view of my own understanding...).

@msporny @brentzundel I am not sure whether we want to close this issue (being irrelevant for the VCDM spec) or leave it open until is handled, to avoid errors in discussions like in https://github.com/w3c/vc-data-model/pull/1358#discussion_r1414437955 or https://github.com/w3c/vc-data-model/pull/1358#discussion_r1415377608. I leave this decision to you. In any case, I removed the before-CR label.

**Comment by gkellogg** [comment]
I suspect it's a bug in handling scoped context in jsonld.js. Looking at the credentials/v2 context definition:

* `VerifiablePresentation` is a term which is used as a type in the outermost object, thus  the type-scoped context it defines is used for expanding the rest of that object, which includes the term definition for `verifiableCredential`
* `verfiableCredential` which is in scope has a `@container: @graph`, meaning that its value is taken to be a named graph, which at least in my implementation, gets a blank node graph label. It also sets `@context: null`, but establishes a new `@context` which is used to expand the values of that graph object.

For some reason, jsonld.js does not seem to interpret the value of `verifiableCredential` as being a blank graph. I would have thought that some test would catch this case, though.

**Comment by pchampin** [comment]
FWIW, [Sophia](https://github.com/pchampin/sophia_rs/), which is based on @timothee-haudebourg's [JSON-LD library](https://github.com/timothee-haudebourg/json-ld), also parses this correctly: [example](https://perso.liris.cnrs.fr/pierre-antoine.champin/2023/sowasm/?guess=&oformat=application%2Ftrig&auto=&input=%0A%0A%7B%0A++%22%40context%22%3A+%5B%0A++++%22https%3A%2F%2Fwww.w3.org%2Fns%2Fcredentials%2Fv2%22%0A++%5D%2C%0A++%22type%22%3A+%22VerifiablePresentation%22%2C%0A++%22verifiableCredential%22%3A+%5B%7B%0A++++%22%40context%22%3A+%5B%0A++++++%22https%3A%2F%2Fwww.w3.org%2Fns%2Fcredentials%2Fv2%22%0A++++%5D%2C%0A++++%22id%22%3A+%22http%3A%2F%2Funiversity.example%2Fcredentials%2F1872%22%2C%0A++++%22type%22%3A+%22VerifiableCredential%22%2C%0A++++%22issuer%22%3A+%22https%3A%2F%2Funiversity.example%2Fissuers%2F565049%22%0A++%7D%5D%0A%7D%0A).
