### ISSUE TITLE
Remove repetition of normative statements in verification algorithm

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1375]
@OR13 has asserted that the current verification algorithm (arguably) [repeats a number of normative statements throughout the specification](https://github.com/w3c/vc-data-model/pull/1338#pullrequestreview-1763413263). Those statements are in there because @jyasskin requested that we add them to ensure that implementers had a definitive list of items to check.

The Working Group needs to come to consensus on whether we are keeping that text, removing it, or modifying it in a way that achieves consensus.

**Comment by jyasskin** [comment]
I don't want to insist on exactly this arrangement of the [verifier's data model conformance checks](https://w3c.github.io/vc-data-model/#data-model-conformance-checking). My request that led to this was in https://github.com/w3c/vc-data-model/pull/1338#discussion_r1388509458, and I hope it's clear that the pattern of "ensure that the _X_ property conforms to the "MUST" statements in Section _Y_" is only a little better than "Check whether <var>verified</var>.<var>document</var> is a [=conforming document=]" with the current definition of "conforming document". @OR13's [suggestion](https://github.com/w3c/vc-data-model/pull/1338#discussion_r1414492504) to have the "conforming document" definition name the "MUST" statements brings them closer together.

I'd rather have an algorithm that returns "conforming" or "nonconforming" for a document, probably by calling down to a sub-algorithm for each property, but I won't object to the more declarative version that has the verifiers grep for "MUST".

Which is a long way of saying that the route to consensus is probably to do what @OR13's asking.

**Comment by msporny** [comment]
PR #1381 has been raised to address this issue. This issue will be closed once PR #1381 has been merged.

**Comment by msporny** [comment]
PR #1381 has been merged, closing.
