### ISSUE TITLE
Separate verification from validation in verification algorithm

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1376]
@OR13 would [like us to separate verification from validation](https://github.com/w3c/vc-data-model/pull/1338#pullrequestreview-1763420896). This issue is being raised to track his concern.

**Comment by msporny** [comment]
It is not clear to me exactly what concrete specification text we need to write to address this concern. It might be related to [this change suggestion](https://github.com/w3c/vc-data-model/pull/1338#discussion_r1414482567). 

@OR13 please edit the initial text to elaborate on what changes you'd like to see in the specification.

**Comment by OR13** [comment]
@msporny the key concept I would like to see is "sharing of validation".

After verification, you have a JSON-LD document that might be conformant.

It should be possible to craft the language, such that the exact same algorithm applies to validating both verified data integrity proof secured and verified sd-jwt secured JSON-LD documents.

Status checks and schema checks can also be shared, assuming that is desirable.

**Comment by msporny** [comment]
@OR13 I believe PR #1381 addresses the concern you raised above (because it uses a suggestion you requested in a separate thread). Once PR #1381 is merged, this issue will be closed.

**Comment by msporny** [comment]
PR #1381 has been merged, closing.
