### ISSUE TITLE
Update algorithms section to normatively depend on the INFRA specification

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#1378]
@jyasskin and @iherman [requested that the specification uses terminology from INFRA](https://github.com/w3c/vc-data-model/pull/1338#discussion_r1394242350) to [define data structures](https://github.com/w3c/vc-data-model/pull/1338#discussion_r1388489174) and [algorithms](https://github.com/w3c/vc-data-model/pull/1338#discussion_r1388488567). @OR13 noted that he would not object to such usage of INFRA.

This issue is to track that concern and ensure that we normatively depend on INFRA before we enter the Candidate Recommendation phase.

**Comment by OR13** [comment]
The result of verifying a secured credential or presentation is an INFRA map expressing a conforming document.

Conforming document implies compact JSON-LD document implementing all normative statements associated with credentials or presentations.

**Comment by msporny** [comment]
PR #1383 has been raised to address this issue. This issue will be closed once PR #1383 has been merged.

**Comment by msporny** [comment]
PR #1383 has been merged, closing.
