### ISSUE TITLE
How are verifiable credentials updated

### ISSUE THREAD

**Issue by r-soltani** [w3c/vc-data-model#139]
Observing a scenario where a person's driver's license is required to be updated.. in the traditional non-digital model the card holder would go to the local government office and request a new driver's licence with the new address. In many cases the old license is destroyed either by the person.. or requested by the office and discarded before the new license is given out.. 

How does this scenario translate into the VC world?

Is it possible to overwrite an existing VC? or do both old and new VCs co-exist and are differentiated by their version field.. and the identity owner has the option to use the appropriate one depending on the situation?

The issuer can invalidate the old VC by invalidating the signature.. however the can the issuer request the identity owner  to delete the old VC upon receiving the new one? perhaps through ODRL?

**Comment by Drabiv** [comment]
I guess, this will work, by issuer revoking old driving license and issueing new one. In the new credential if needed, the issuer can reference old credential. 
Also, credentials may have expiration date, hence they can become invalid "passively" (without innervation from issuer).

**Comment by dlongley** [comment]
Closed via #210.
