### ISSUE TITLE
Verifying a VC should return the same credential regardless of the verification method

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#1399]
Our Data Model is that we have a credential, and by adding a proof (external or embedded) we get a verifiable credential. Conversely after verifying a VC, the credential that is returned should be identical regardless of the proofing mechanism

**Comment by selfissued** [comment]
David is correct.  This logic needs to be applied to the ambiguous text in https://github.com/w3c/vc-data-model/pull/1393 before it can be merged.

**Comment by dlongley** [comment]
A credential with a `proof` field does not "unbecome" a credential, it is just both a credential and a verifiable credential. However, I would be supportive of allowing both of these options to be returned from an "embedded proof" securing mechanism to enable users of either approach.

**Comment by msporny** [comment]
> Conversely after verifying a VC, the credential that is returned should be identical regardless of the proofing mechanism

This was done in PR #1393, commit 8c16fec9990f0f5b4b0d16d1fd8d587fa59a5461.
