### ISSUE TITLE
Backtick characters in Internationalization / Language examples

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c/vc-data-model#1417]
Current Internationalization examples (like [Example 39](https://www.w3.org/TR/vc-data-model-2.0/#example-expressing-natural-language-text-as-english)) have backtick characters as part of the language and direction value:

```json
"title": {
  "@value": "HTML and CSS: Designing and Creating Websites",
  "@language": "`en`"
}
```
I suspect this is a rendering artifact rather than deliberate choice, so just wanted to double-check (before somebody implements it this way :) ).

**Comment by iherman** [comment]
Opened #1422 for this. This issue must be closed if that PR is closed.

**Comment by iherman** [comment]
Relevant PR merged; closing
