### ISSUE TITLE
typo in Terms of Use

### ISSUE THREAD

**Issue by lemoustachiste** [w3c/vc-data-model#1418]
in this section: https://www.w3.org/TR/vc-data-model-2.0/#terms-of-use

The second paragraph has a typo (pubic instead of public): 

> the rules and policies of the [issuer](https://www.w3.org/TR/vc-data-model-2.0/#dfn-issuers) that apply to the presentation of this [verifiable credential](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-credential) to a [verifier](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifier), by providing, for example, a pointer to a **pubic** location

**Comment by brentzundel** [comment]
I am deeply grateful that you caught this typo, thank you.

**Comment by msporny** [comment]
PR #1423 has been merged to address this issue. I'm glad that we dealt with this issue head on and that we can now put it behind us. Closing.
