### ISSUE TITLE
"…" as a term name in the context file? 

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-model#1421]
The default context file includes this term:

```
"...": {
      "@id": "https://www.iana.org/assignments/jwt#..."
}
```

Is this intentional or a bug? This is certainly very unusual for a term name (not even sure it is legal but I did not check)

@msporny

**Comment by msporny** [comment]
> Is this intentional or a bug? This is certainly very unusual for a term name (not even sure it is legal but I did not check)

Unfortunately, it's not a bug... that's literally what SD-JWT uses to denote elided values: https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-07.html#section-5.2.4.2

It's weird, to say the very least. :)

**Comment by iherman** [comment]
Hm. This really looks weird, but, well, ... (sic!)

Isn't it possibly a problem that this URL `https://www.iana.org/assignments/jwt#...` looks, depending on fonts, the same as `https://www.iana.org/assignments/jwt#…` but they are not? (Hint: the second one uses an "ellipse" character, i.e., (U+2026)?

Anyway. That is done above our heads, so to say. Closing this issue...
