### ISSUE TITLE
Unmatched HTML Tag 

### ISSUE THREAD

**Issue by lukasjhan** [w3c/vc-data-model#1460]
Hi I'm currently working on a translation of this on going standard (VCDM 2.0). I found some unmatched tags.
Can I fix this and make a PR? or Is is intentional?

This is actually my first time here. Let me know if I missed anything.
Thank you.

**Comment by davidlehn** [comment]
Yes, please make a PR.

**Comment by lukasjhan** [comment]
Thank you I'll make a PR :) @davidlehn

**Comment by msporny** [comment]
PR #1461 was raised to address this issue. That PR has been merged. Closing.
