### ISSUE TITLE
EnvelopedVerifiablePresentation missing in https://www.w3.org/ns/credentials/v2

### ISSUE THREAD

**Issue by vincentkelleher** [w3c/vc-data-model#1482]
Hi 👋 

We have noticed that the `EnvelopedVerifiablePresentation` term is missing in the https://www.w3.org/ns/credentials/v2 context although it has been added to the specification through #1431 and is mentioned [here](https://www.w3.org/2018/credentials/#EnvelopedVerifiablePresentation).

Are we missing something or a fix is needed ?

Thanks for your help 😊

**Comment by msporny** [comment]
> Are we missing something or a fix is needed ?

Good catch, a fix is needed, we'll make the fix. Thank you for finding that bug!

**Comment by msporny** [comment]
Fixed in 1826543e116ce14f6a0ac5f092c5ed387fe1f571. Closing.
