### ISSUE TITLE
Data URLs showed in the examples are incorrect

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/vc-data-model#1542]
The data URLs showed this spec are all using a semicolon `;` to separate the media type from the data. According to [RFC2397 Section 3](https://www.rfc-editor.org/rfc/rfc2397.html#section-3), it should be a comma `,` instead.

**Comment by msporny** [comment]
Fixed in d320d85af58e3923aa080d52f82aa828fc2210e0; closing.
