### ISSUE TITLE
Example 21 contains an undefined term

### ISSUE THREAD

**Issue by filip26** [w3c/vc-data-model#1564]
see [Example 21](https://www.w3.org/TR/vc-data-model-2.0/#example-a-verifiable-presentation-secured-with-an-embedded-data-integrity-proof-with-a-self-asserted-verifiable-credential-about-the-verifiable-presentation)

`assertion` is an undefined term. Possible solutions:
* remove `assertion` and replace it `description` for example, which is defined
* remove credential scoped `@context`
* add examples context to the credential scoped `@context`, duplicate the main `@context`

**Comment by filip26** [comment]
the same for [Example 20](https://www.w3.org/TR/vc-data-model-2.0/#example-a-verifiable-presentation-secured-with-an-embedded-data-integrity-proof-with-a-self-asserted-verifiable-credential)

**Comment by msporny** [comment]
The example uses the `https://www.w3.org/ns/credentials/examples/v2` context, which includes an `@vocab` statement. That makes `assertion` defined. Yes, it's a bit sloppy, but that's what the examples context is there for -- to make the content valid so we can demonstrate an example.

I suggest we keep the example as-is, as it is what we intended. Would you be ok with that, @filip26?

**Comment by filip26** [comment]
@msporny  It's a presentation, the main `@context` is erased in v20 for `verifiableCredential`.  

Easiest fix is to replace `assertion` with `description` for 21, and replace `favoriteCheese` in example 20 with something else, .e.g.  `@id`, as those props are not important for those examples. I can open PR if this 'fix' is OK.

I've found another issues like those, e.g. non-dereferenceable contexts in examples. Do you prefer to have it reported, or is there some plan to fix all the examples in once?

**Comment by filip26** [comment]
or move `examples` context to credential scoped context, it could be a nice example that there can be more contexts embedded .

**Comment by davidlehn** [comment]
I'd add the examples context to the inner credential.  A move wouldn't work since the presentation uses ExamplePresentation which needs to be handled as well.

**Comment by msporny** [comment]
Fixed in 05c8f8e2193e0112482c362114a751e57f9437f6. Closing.
