### ISSUE TITLE
Will extensibility lead to vulnerability?

### ISSUE THREAD

**Issue by burnburn** [w3c/vc-data-model#157]
Question from @David-Chadwick that needs to be addressed in the spec.

**Comment by David-Chadwick** [comment]
Yes it does. I have indicated how one attack can work in PR #159

**Comment by David-Chadwick** [comment]
PR #159 is technically flawed for reasons I have identified there. Consequently it should be removed until correct text can be agreed to

**Comment by burnburn** [comment]
PR merged.  Closing.
