### ISSUE TITLE
VC test suite requirements document

### ISSUE THREAD

**Issue by cwebber** [w3c/vc-data-model#161]
Please help review to determine which requirements should be tested, how, and if some requirements should be adjusted due to being untestable currently: https://docs.google.com/spreadsheets/d/1MCIZghhT5xCTnBpqDMpeCqc0zBS2Lgwfoi0tONijZOQ/edit#

**Comment by stonematt** [comment]
updates will happen in the test case repo, found here: https://github.com/w3c/vc-test-suite

also added link to the README.md

**Comment by stonematt** [comment]
closing after updating README.md
