### ISSUE TITLE
Determine how/if WebAuthn will work with VCs

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-data-model#162]

**Comment by dlongley** [comment]
This is being explored with implementations. Specifically, we're looking into using WebAuthn with Verifiable Presentations and DIDs. We should have a marker in the spec indicating that we're exploring this issue but leave it at that for the moment. We don't know how our implementation experiments will work out yet -- but either way we'll probably leave some kind of comment in the spec. That comment will likely either be: Here's an example for how you can use WebAuthn with a VerifiablePresentation or that it was explored but left for a future version (or something to that affect).

**Comment by burnburn** [comment]
@dlongley ping.

**Comment by dlongley** [comment]
@burnburn, we'll have an update here after this week.

**Comment by msporny** [comment]
I suggest we make this addition in a "Implementation Guidelines" document and close this issue.

**Comment by brentzundel** [comment]
Decision at Barcelona F2F: Exploration complete enough to shift issue to CCG, close issue.

**Comment by burnburn** [comment]
Created https://github.com/w3c/vc-imp-guide/issues/3 in Imp-Guide to continue this.  Closing.
