### ISSUE TITLE
Change VerifiableProfile to VerifiablePresentation

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#163]
Based on discussion at the VCWG F2F in 2018, there was consensus to rename the "Verifiable Profile" to "Verifiable Presentation" to support use cases like ZKPs and to provide a different identifier for the presentation vs. the subject being identified.

**Comment by msporny** [comment]
I will submit a PR for this.

**Comment by Drabiv** [comment]
I think that Profile/Presentation concept in the spec should be replaced with a generic mechanism to reference/attach credentials from another credential (see issues #135).
Also, if the concept of Profile/Presentation needs to exist I propose to call it "Bundle", or "verifiableBundle". 
"Presentation" name might be confused with the concept of visual presentation of JSON data to end users in the form of HTML/SVG.

**Comment by Drabiv** [comment]
Just to illustrate the point, that using "presentation" word to mean bundle of credentials might be confusing with understanding "presentation" - as a human friendly presentation of credentials JSON data.
In Validbook Statements we calculate hash of presentation layer and show it in JSON object with purpose "Presentation". 
See example of signed VB Statement with calculated hash of presentation layer at: https://drive.google.com/file/d/1UjIZrREO7iJJ00qJQtaLW1ohtBIx3NgN/view?usp=sharing
You can drop it to VB Statements service (http://futurama1x.validbook.org/statements) to go between presentation and JSON layers.
