### ISSUE TITLE
Disputed credential section is confusing

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-data-model#180]
https://github.com/w3c/vc-data-model/blob/gh-pages/index.html#L1064-L1089

A type of "DisputedCredential" is a statement about the credential doing the disputing, so this name seems wrong. Also, it may be that the IDs appear in the wrong place in the example.

**Comment by lovesh** [comment]
@dlongley I agree, it says `For example, if a disputed credential with an identifier of https://example.org/credentials/245` but it should say `For example, if a disputed credential with an identifier of http://con-artist.example.com/credentials/3732`. The credential id being disputed goes in `claim`

**Comment by msporny** [comment]
Attempted a fix in https://github.com/w3c/vc-data-model/commit/19bb3f43b042b7d9280e469316ab23ba23489470 ... pay particular attention to the `disputedClaim` addition. Don't know how I feel about it yet, but tried to find a way to point out specific claims that are disputed.
