### ISSUE TITLE
Verifiable Claims --> Verifiable Credentials

### ISSUE THREAD

**Issue by petrsnm** [w3c/vc-data-model#181]
Noticed that one significant difference between the [latest published version](https://www.w3.org/TR/verifiable-claims-data-model/)  and the [current editor's draft](https://w3c.github.io/vc-data-model/) is a rename of title and terminology:  "verifiable claims" is changed to "verifiable credentials" 

There are a few remaining occurrences of "verifiable claims" left in in "Privacy Considerations" section the current editors draft that you'll want to fix.  Thanks.

**Comment by msporny** [comment]
> latest published version

The W3C version of the spec is horribly out of date... it's almost a year old at this point. @liamquin -- is there any way that we can make sure that the W3C version of the spec is published at least on a monthly (or more frequent) basis? Perhaps using the autopublisher? I think we approved this move a while ago, but it still hasn't been implemented?

> There are a few remaining occurrences of "verifiable claims" left in in "Privacy Considerations" section the current editors draft that you'll want to fix.

Thanks, will fix in the next editorial pass of the spec.

**Comment by msporny** [comment]
> Might also be worth making corresponding renaming change to the current
editor's draft of "Verifiable Claims Use Cases"

That would be a task for @stonematt and @jandrieu.

**Comment by msporny** [comment]
Thanks for the issue @petrsnm ... fixed in https://github.com/w3c/vc-data-model/commit/ba43ef77f52abcd031f243a593eb46986f546331.
