### ISSUE TITLE
Renaming "issued" and "expires" to "issuanceDate" and "expirationDate"

### ISSUE THREAD

**Issue by lovesh** [w3c/vc-data-model#184]
"expires" sounds ambiguous as to whether it means the credential can expire or not. Can we make the name more explicit?

**Comment by msporny** [comment]
> "expires" sounds ambiguous as to whether it means the credential can expire or not. Can we make the name more explicit?

The spec is pretty clear about the meaning: https://w3c.github.io/vc-data-model/#expiration

We had considered appending "Date" in the past, but folks asserted that it's really a date *and* time. So, we could do expirationDatetime or expirationTime. 

There has also been a request to align with JWT, which uses "Expiration Time" or "exp" and "Issued At" or "iat"... both of which are not great either.

There is also the "notValidBefore" and "notValidAfter" approach that X.509 took. All of these have their benefits and drawbacks. 

We tried to keep it simple with "expires" and "issued", but if folks want to bikeshed this -- we'll need more people picking out colors for the bikeshed. Someone set up a poll. :)

**Comment by msporny** [comment]
Ok, I'll switch the spec over to "issuanceDate" and "expirationDate" unless there are strong objections in the next 7-14 days.

**Comment by talltree** [comment]
+1 to "issuanceDate" and "expirationDate".
