### ISSUE TITLE
Composing JWT documents

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#2]
What is the data model for composing JWT documents. For Linked Data Signatures, the approach utilizes a graph-based data model to "merge" the data together. Is this same approach valid for JWT-signed data? Do we assume a graph-based data model and merge using the same rules, ignoring the JSON tree structure? Or do we have to specify how different JWT documents are merged together? We need examples of how this is done.

**Comment by dlongley** [comment]
> Do we assume a graph-based data model and merge using the same rules, ignoring the JSON tree structure?

Yes, I think this is what we do. We define a single point (or JWT claim) as an entry point for placing JSON-LD data. This is the simplest solution.

**Comment by msporny** [comment]
No one has worked on this issue. I suggest we close it.

The latest RsaSignature2018 cryptography suite supports JOSE JWS-style signatures: https://github.com/digitalbazaar/jsonld-signatures/commit/f583bd4333785b847c6fcddc7065eeb388aa6733

Given that no one in the group has written a JWT-based VC implementation, I'm suggesting that we close this issue for the 1.0 work. We can always support JWT-based VCs later if someone decides to write a spec encapsulating VCs in JWTs.

Notice: Closing this issue on or after 2018-2-20.
