### ISSUE TITLE
Should commenting by adding Github issue be mentioned in Status section?

### ISSUE THREAD

**Issue by stevenrowat** [w3c/vc-data-model#20]
"Status" currently includes this sentence about commenting on the document:
“If you wish to make comments regarding this document, please send them to public-credentials@w3.org (subscribe, archives).”

Should the method of creating Github issues (like this one) also be included?

**Comment by msporny** [comment]
Yes, we should add a link to the issue tracker.

**Comment by msporny** [comment]
Text on filing issues via Github and a link to the issue tracker were added a while ago: https://github.com/w3c/vc-data-model/commit/ab66847903107c37c5f7eb7839c5af723c48cfbb

Closing this issue.
