### ISSUE TITLE
Repeated subsections in "Security Consideration" section

### ISSUE THREAD

**Issue by aabdulwahed** [w3c/vc-data-model#211]
I found that <code>11.3 Bundling Dependent Claims</code> and <code>11.5 Bundling Dependent Claims</code> were repeated twice as shown [here](https://w3c.github.io/vc-data-model/#bundling-dependent-claims). I'm not sure if it was already fixed or not but I just wanted to reference these duplicates in the published document.

**Comment by msporny** [comment]
Fixed, thank you!
