### ISSUE TITLE
Accessibility Impact Statement

### ISSUE THREAD

**Issue by stonematt** [w3c/vc-data-model#221]
From email at: https://lists.w3.org/Archives/Public/public-vc-comments/2018JulSep/0001.html

2.)	We note that you provide extensive comments on the Security and
Privacy implications of your specification. We are confident
implementers of your specification can easily create accessibility
barriers if not careful when implementing this specification. We would,
therefore, request that we jointly determine appropriate language for an
Accessibility Impact statement alongside the Security and Privacy
section.

**Comment by msporny** [comment]
I think this is in the spec now... may need to move it to a11y section.

**Comment by TzviyaSiegman** [comment]
Addressed by https://github.com/w3c/vc-data-model/pull/246

**Comment by stonematt** [comment]
Closing based on Tzviya's comment.
