### ISSUE TITLE
Coordinate with PING during review process

### ISSUE THREAD

**Issue by stonematt** [w3c/vc-data-model#222]
we need a leader to stay in touch w/ PING and be a resource as they complete the review

**Comment by David-Chadwick** [comment]
Please accept my apologies for today's meeting but I cannot attend.

As I am a member of the PING working group, I will be happy to take on
the leader role proposed below if no-one else volunteers at today's meeting

Kind regards

David

**Comment by burnburn** [comment]
From TPAC 2018:
- [ ] Add more ZKP examples (everywhere, not just Data Model Spec).  See #237.
- [ ] Focus first on privacy-preserving examples
- [ ] Provide specific guidance for private browsing mode
- [ ] In Implementation Guidance NOTE, suggest how to do progressive trust or graceful degradation
- [ ] Verify with PING that the above is the complete list :)

**Comment by brentzundel** [comment]
Decision for F2F Barcelona:
- [ ] @stonematt will create an issue in the implementation guidance repo to track adding suggestions on how to do progressive trust or graceful degredation
- [ ] @brentzundel will add comment in privacy section about private browsing
- [ ] close this issue

**Comment by stonematt** [comment]
See issue in implementation guidance: https://github.com/w3c/vc-imp-guide/issues/6

**Comment by stonematt** [comment]
Move dialog to issue in Implementation Guide, Leave open until ImpGuide content addresses this.

**Comment by stonematt** [comment]
@brentzundel when you update the privacy section, please remove the CR-Blocker tag and Add the CRExit-Blocker tag.

**Comment by stonematt** [comment]
@brentzundel to complete by EOW March 15

**Comment by brentzundel** [comment]
first attempt is in PR 448

**Comment by brentzundel** [comment]
All work items fro Barcelona are complete. Not sure if this issue needs to stay open.

**Comment by stonematt** [comment]
No open issues from PING at the moment. New items will be opened as new issues.  Closing.

**Comment by burnburn** [comment]
Will will close when the final IMplementation guide action items are completed.

**Comment by burnburn** [comment]
Assigned to VCWG chairs.

**Comment by burnburn** [comment]
At this point we are only waiting on https://github.com/w3c/vc-imp-guide/issues/6.  Once the associated PR goes in this issue will be closed.
