### ISSUE TITLE
Disputed credentials - who can issue them?

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#226]
I raised the following issue with the PR#185 on disputed credentials, but I do think it was addressed prior to the PR being pulled in. Please correct me if I am wrong.

There is another issue with this section, namely who is entitled to issue a "DisputeCredential". We must consider the case of an attacker issuing a false dispute credential. If we regard a "DisputeCredential" as being similar to a revoked credential, then if anyone is allowed to issue a DisputeCredential we have the opportunity for a DOS attack, or at least the opportunity to give the verifier sufficient cause for concern to temporarily suspend access to its resources for the credential owner. I would therefore like to see a statement along the lines of:

Only the subject of a verifiable credential, or its authorised agent, is entitled to issue a "DisputeCredential". A "DisputeCredential" issued by anyone other than the subject, or its authorised agent, SHOULD be disregarded by the verifier, unless the verifier has some out of band means of ascertaining the truth of the dispute.

**Comment by msporny** [comment]
> Only the subject of a verifiable credential, or its authorised agent, is entitled to issue a "DisputeCredential". A "DisputeCredential" issued by anyone other than the subject, or its authorised agent, SHOULD be disregarded by the verifier, unless the verifier has some out of band means of ascertaining the truth of the dispute.

I agree with this language (with some minor editorial modifications). I don't know if the spec says this at present or not, but I can check and put it in if not. Feel free to suggest a PR to do so, if not, I'll try to do a PR in my next edit cycle.

**Comment by David-Chadwick** [comment]
I have started to do the PR, but it turns out to be more complex than simply adding the above paragraph, due to the ambiguity of the current text. Consequently my PR will include more clarifying text for everyone to review

**Comment by msporny** [comment]
This was fixed in #259, closing.
