### ISSUE TITLE
Context out of date

### ISSUE THREAD

**Issue by cwebber** [w3c/vc-data-model#231]
As mentioned in #230, the context at https://w3id.org/credentials/v1 is out of date and doesn't have all the current terms, eg `Credential` instead of `VerifiableCredential`

**Comment by gkellogg** [comment]
See comment https://github.com/w3c/vc-data-model/pull/230#issuecomment-421435187, the repo has it defined, but there may not be a mechanism to update the version on w3id.

Of course, there may be other terms that need to be updated in the context; please let me know and I'll do another update.

**Comment by msporny** [comment]
I expect that this will be addressed as we go into CR. We still need to make sure the context matches the spec... so someone needs to do that update. That might be best done by @cwebber since he put the test suite together and would have the most recent information in his head.

**Comment by msporny** [comment]
Fixed in https://github.com/w3c/vc-data-model/commit/40e428f7de666ac56099b074925f915618272779. Reconciling auto-generation of files now...

**Comment by msporny** [comment]
Auto-generated files are now reconciled in f1c2bee536f76bcdeeea20145c9ad71992461d5b,

**Comment by msporny** [comment]
All context and vocab files are now updated and aligned with the spec. This is no longer a CR Blocker.
