### ISSUE TITLE
New section/paper: gap analysis

### ISSUE THREAD

**Issue by jandrieu** [w3c/vc-data-model#233]
By charter, the use case document needs a section on gap analysis.
> The document will include an analysis of gaps in existing solutions, notably OpenID Connect and SAML, that the new work will address.

We discussed on a call that this would probably be best as a separate note. This issue is here to flag the chairs to make that happen.

https://github.com/w3c/vc-use-cases/issues/51

**Comment by David-Chadwick** [comment]
I am willing to work with you and others on this

**Comment by dlongley** [comment]
Closing and moving back to use cases document -- doesn't belong in data model spec.
