### ISSUE TITLE
Comments on Section 6.2 Terms of Use

### ISSUE THREAD

**Issue by riannella** [w3c/vc-data-model#234]
The ODRL Community group has made some comments on this section.

Please see: https://github.com/w3c/odrl/issues/4

**Comment by stonematt** [comment]
@msporny @David-Chadwick this is a response from an external review, as such we should consider it a CR-Blocker.  The details of their comments look like editorial comments and tweaks in a couple examples. Any objection to making these modifications in the spec? (and adding "CR-Blocker" to the issues)

**Comment by David-Chadwick** [comment]
Can we say that this issue is subsumed by #269. Once we address #269, then we will know how to address this issue.

**Comment by burnburn** [comment]
@burnburn ping myself to do the PR

**Comment by msporny** [comment]
> In Example 11, the assigner should be a URI.
> Something like https://dmv.example.gov/verifiers/all

All assigners are now URIs in the spec.

> Perhaps they can also state that https://dmv.example.gov/verifiers/all is a PartyCollection.

We use JSON-LD's features to make "AllVerifiers" a PartyCollection.

> They can also use "archive" as the action (from the ODRL common vocab)

We ended up using "Archival" in the example as lower-case class names are frowned upon for JSON-LD.

> The type can be a "Set" (as this is the default Policy type).

I don't understand this suggestion.

> They should update the narrative to read:
> 
> > In the example above, the issuer (assigner) is prohibiting all verifiers (assignee) from storing the data in an archive.

Fixed in 8610f8fc72bb36b3431bf18c7d1c018428666454. Also cleaned up the other two examples that use ODRL.

**Comment by msporny** [comment]
I have responded to all comments from this review and applied a number of changes that were suggested.
