### ISSUE TITLE
Unclear on antecedent of "agent" in Entity Credentials capabilities

### ISSUE THREAD

**Issue by jtibbetts** [w3c/vc-data-model#24]
In section 1 of the vc-data-model there is a list of capabilities for Entity credential holders.  One of them is: "Entity credential holders that share verifiable claims are not required to reveal the identity of the inspector to their agent or to issuers.".  On initial reading I've taken the agent to mean the agent of the Entity credential holder.  If that's true that would imply that the holder's own agent doesn't have the identity  of the of the issuer or the inspector.  (refer to Architecture Block Diagram in section 3 of the Architecture document for a diagram of these entities).
I've always understood that the VCTF architecture provided an insulation protecting the identities of issuer from inspector and vice versa.  But if the above sentence is correct then even the holder's agent is barred from this knowledge.  Is this correct?

**Comment by burnburn** [comment]
@msporny we can't call this editorial yet.  It needs a response to the question, at least.

**Comment by David-Chadwick** [comment]
I think this issue has now been resolved as the offending text is no longer present in the data model document. I therefore suggest this issue can be closed

**Comment by msporny** [comment]
@David-Chadwick is correct, the text no longer appears in the document and we're more careful with the language now (after months of reworking it). Please re-open if you disagree, @jtibbetts.
