### ISSUE TITLE
Privacy issues

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#244]
A couple of privacy issues have been spotted whilst doing a review for PING

1. Section 9.3 mentions the claim ID but not the credential ID. I believe the credential ID could be used for correlation in the same way as the claim ID.

2. Section 8.9 states “All policy information expressed by the issuer in the verifiable credential MUST be enforced unless verifiers accept the risk of not enforcing the policy information.” The text from “unless” onwards seems to be condoning the verifier violating mandatory clauses in the standard, and could certainly lead to severe privacy breaches. I believe the text following “unless” should be removed. Of course I understand that verifiers can ignore all policy information, but then they would be non-conformant implementations. Standards should not make statements about non-conformant behavior (as this is outside the scope of the standard - by definition).

**Comment by David-Chadwick** [comment]
Yes it does, but it is in the wrong place. Can you move section 9.17 Avoid Disclosing Credential Identifier to be after section 9.3 Identifier-Based Correlation

**Comment by RieksJ** [comment]
As a verifier, I would like to be able to check whether or not a credential/claim has been revoked. Does avoiding the disclosure of credential/claim identifiers prevent me from doing this?

**Comment by msporny** [comment]
> Does avoiding the disclosure of credential/claim identifiers prevent me from doing this?

Not necessarily, there are ZKP mechanisms that enable you to prove that a credential hasn't been revoked at the time of presentation. Unfortunately, you can't tell if it has been revoked after it has been presented to you, so not having a credential identifier that you can check against a revocation list creates a challenge in this scenario.

**Comment by msporny** [comment]
Fixed in https://github.com/w3c/vc-data-model/commit/a967b8665ca62662cf9ac0e28be1f964f9914e47 @David-Chadwick, please re-open if you disagree.
