### ISSUE TITLE
Add brief section explaining relationship between DIDs and VCs

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c/vc-data-model#250]
From the VC WG meeting at TPAC, the question came up about the relationship between DIDs and VCs. As in, do DIDs depend on Verifiable Credentials (and conversely, do VCs depend on DIDs)?

I think this is going to be a common question, so I'm wondering if it's a good idea to add a paragraph or so of non-normative explanation:

* VCs need identifiers, which basically means URIs/URNs (although some implementers have used context-dependent key material as identifiers). And DIDs are a way to use URIs to link into not-traditionally-web-enabled systems like distributed ledgers.
* VCs do not depend on DIDs, you can have verifiable credentials without using DIDs (and instead use HTTPS URIs, for example).
* That said, any sort of general-purpose VC libraries will very likely need to know about DID resolution methods, etc.
* Similarly, DIDs do not depend on VCs. DIDs are simply a storage for crypto material and service discovery.

**Comment by msporny** [comment]
@dmitrizagidulin Can you check the PR above and make sure it covers everything you asked for?
