### ISSUE TITLE
Decide if there should be an EOL date on the spec?

### ISSUE THREAD

**Issue by stonematt** [w3c/vc-data-model#253]

**Comment by brentzundel** [comment]
Decision at Barcelona F2F: @jandrieu will engage @ChristopherA to come make the case

**Comment by ChristopherA** [comment]
I think that this issue should be changed to request the TAG or the W3Process "Evergreen Standards" group to give advice on it.

The scenario I'm trying to avoid is a specification that has "international standard" status but should be deprecated for security or privacy reasons.

As the co-editor of IETF TLS 1.0 from 1995 to it's release in the beginning of 1999, I was quite disappointed when there were serious server downgrade attacks against TLS in 2017 (almost 20 years after release of 1.0) using cryptography and versions that should have not been in use for over a decade, but were still "part of the standard" despite there being subsequent 1.1 and 1.2 releases. In retrospect, I wish not only the spec itself, but many of its normative features such as ciphersuites, had expiration dates on them, even if 10 or 20 years ahead. If a spec or feature is still strong after a decade they can be renewed with a new expiration date.

My concern may not applicable to this specific VC specification, as it does not contain normative cryptographic information, but there may be privacy best practices discovered in the future that warrants deprecating this spec in 20 years.

Part of my concern that an expiration should be in the final version of a W3C spec is that this WG ends after the CR is approved. If in an Evergreen process (such as is being discussed in the WG-Process WG) where they can deprecate a spec version or features in a spec, I'd feel this is less necessary.

I am not asking for this issue to be a CR-Blocker, nor should it be a CRExit-Blocker.

**Comment by chaals** [comment]
Agree this is not a CR-blocker. I think that we should point out to W3C that the [maintenance process](https://www.w3.org/2019/Process-20190301/#revised-rec) should be used actively, in particular to deprecate things that we come to consider harmful in the future in an [Amended Rec](https://www.w3.org/2019/Process-20190301/#rec-amended) if there is no Working Group...

**Comment by burnburn** [comment]
Discussed 26 March 2019.  @ChristopherA Since a) there is a maintenance process for Recommendations, b) this issue is about a concern with mandated cryptography, and c) this data model specification makes no normative statements regarding specific cryptographic suite requirements, we believe this not to be an issue for the specification.  Will close 14 days from today if no additional concerns are raised by then in this issue.

**Comment by msporny** [comment]
14 days have passed since the proposed resolution was placed in here. No new information has surfaced in the interim time frame. No changes to the specification have been made as a result of this issue. Closing.
