### ISSUE TITLE
Are JWTs appropriate for Verifiable Claims?

### ISSUE THREAD

**Issue by jtibbetts** [w3c/vc-data-model#26]
I've been a big fan of JWTs.  In fact, in a recent revamp of IMS Global's LTI web service security we've added JWTs as a favored mechanism for generating bearer tokens.

But I have reservations of using JWTs for all but the simplest Verifiable Claims (if at all).  It seems to me that JWTs are optimized for just what the acronym implies: creating a  _**token**_.  A token, to me, is a small thing.  It may carry some state; for example, access control cues.  The fact that it's signed ensures that the access control parameter can't be tampered with.  That's good.  And the fact that its 3 zones are base64-encoded means it will travel easily as a bearer token.

But there are problems using it for a rich verifiable claim.

1. A rich verifiable claim, like an extended Transcript, can be a deeply nested, highly interlinked structure.  It seems counter-intuitive to me to tokenize it.  Furthermore, problems with more complex signature structures (nested, etc) have already been noted.

2. Structurally it looks inside-out to our VC structure which has the signature embedded within the claim.  In the JWT case the entity credentials are inside the JWT with the signature on the outside contained in the obfuscated JWT.

3. While I understand that tooling is beyond the scope of this document, isn't it going to be painful to use JSON-LD tools to work on artifiacts embedded in a JWT?

Perhaps, if there's interest among the JWT community of experts, something can be done to ameliorate these issues.

**Comment by jandrieu** [comment]
There was additional interest in JWT expressed at IIW Oct 2017 for single signature, simple use cases. Specifically, canonicalization was pointed to as a significant pain point, having been intentionally rooted out of other specification efforts.

Would it be possible to allow JWT or JSON-LD?

**Comment by kimdhamilton** [comment]
We bridged LD signatures with JWS through detached, unencoded payloads in [RSA Signature Suite 2017|https://w3c-dvcg.github.io/lds-rsa2017/]

[See Whitepaper with description and references to implementations](https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-spring2017/blob/master/final-documents/ld-signatures.pdf)

**Comment by msporny** [comment]
Building on @kimdhamilton and team's work, the latest RsaSignature2018 cryptography suite supports JOSE JWS-style signatures: https://github.com/digitalbazaar/jsonld-signatures/commit/f583bd4333785b847c6fcddc7065eeb388aa6733

Given that it's been 4+ years and there isn't a spec for Verifiable Credentials expressed as a JWT, and given that no one is implementing JWT-based Verifiable Credentials, I'm suggesting that we close this issue for the 1.0 work. We can always support JWT-based VCs later if someone decides to write a spec encapsulating VCs in JWTs.

Notice: Closing this issue on or after 2018-2-20.
