### ISSUE TITLE
Is a VC a tree or a graph?

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#260]
I would say that a VC is actually a tree and not a graph. In most cases (ideally all) there won't be any times where the same object occurs twice in a VC. If it does, it is probably not the same object, or the modelling is wrong.

Consider the following model of a VC. The issuer may issue a VC about a single subject or about several different subjects. But each of these RDF objects (i.e. VC subjects) are different. The issuer may issue a single assertion about a VC subject, or multiple assertions (aka properties) about a VC subject, but each of these will all be different. This is a tree structure, not a graph.

I would like someone to give me an example (or two) of where a VC is genuinely a graph where the same object occurs more than once.

Unfortunately I am not knowledgeable enough about JSON-LD to fully appreciate the @graph keyword, but it seemed as if it was implicitly being added to the VC construct in order to chop the VC tree into multiple branches, because the model had inadvertently created a loop.

If you look at the RDF I have proposed in #207 you will see that a VC is a tree and not a graph.

**Comment by dlongley** [comment]
Here's one such example (scroll down and click on the CSP exam credential):

http://www.credentialfinder.org/credential/1591/Certified_Safety_Professional%C2%AE_(CSP%C2%AE)

I'm sure you can find many more, there are thousands of credentials designed to be encapsulated in JSON-LD VCs here:

http://www.credentialfinder.org/

**Comment by dlongley** [comment]
The other thing to note here is that many use cases would involve pulling in a VC and then merging/combining that data with other data in order to reason about it (in your application). The CTI (Credential Transparency Initiative) has a lot of data that helps convey this expectation.

**Comment by David-Chadwick** [comment]
@dlongley 
> The other thing to note here is that many use cases would involve pulling in a VC and then merging/combining that data with other data in order to reason about it (in your application)."

But this is out of scope of the VC data model, because the combined data is no longer a VC. There is nothing in what I have said to stop this. I only asserted that the VC itself should be a tree (which is a subset of a graph).

**Comment by msporny** [comment]
> I only asserted that the VC itself should be a tree (which is a subset of a graph).

Rather than get into an esoteric argument around whether you can express a graph using a tree + node references (you can, that's mathematically provable) let me try to go at this a different way.

Will answering this question either way change the specification in any normative way that we want to do before we go into CR? I assert that it would not and thus we should close this issue.

To force the debate, I'm going to close the issue and let @David-Chadwick re-open it if he feels very strongly about debating this topic. :)
