### ISSUE TITLE
Provide support for JWT data format

### ISSUE THREAD

**Issue by awoie** [w3c/vc-data-model#266]
As per section 1.3 Use Cases and Requirements:
> Verifiable credentials and verifiable presentations are expressed in one **or more** standard, machine-readable data formats which can also be extended with minimal coordination.

As per section 7.1.1 JSON Web Token:
> This section will be moved into its own specification before this document enters the Candidate Recommendation stage.

This indicates that the JWT section is going to be disregarded. While JSON and JSON-LD are useful options in many cases, there would be a lack of supporting the well-known and mature JWT industry standard. 

As per RFC 7519 JSON Web Token (JWT):
> JSON Web Token (JWT) is a compact claims representation format

Consequently, the specification does not support other formats than JSON and JSON-LD at the moment. 

The W3C VC specification should support JWT to ensure backwards-compatibility with existing solutions and easier adoption of the specification due to JWT's wide distribution, support by many frameworks and maturity of existing libraries.

A suitable mapping of the W3C VC data model onto JWT should reuses standard JWT claims as much as possible to allow seamless integration. In my mind, this could be considered as "cr-blocker" and "discuss".

**Comment by burnburn** [comment]
PR merged, so I suggest closing.  Clearly other PRs (such as #366) are working on updates, but that's fine.

Please re-open if necessary.

**Comment by Fak3** [comment]
> Clearly other PRs (such as #366) are working on updates, but that's fine.

@burnburn there is no such pr

**Comment by burnburn** [comment]
Weird.  I don’t know what that was supposed to  be referencing, but the
point was that edits can still continue. We no longer need an issue to tell
us to add JWT support now that initial text is in the spec.
