### ISSUE TITLE
Validate requirements text matches test suite and current thinking

### ISSUE THREAD

**Issue by stonematt** [w3c/vc-data-model#270]
Validate and/or update the requirements text in the data model to match tests in the test suite and the text/expectation in the Use Cases.

Working references: 
- Test Suite spreadsheet: https://docs.google.com/spreadsheets/d/1MCIZghhT5xCTnBpqDMpeCqc0zBS2Lgwfoi0tONijZOQ/edit#gid=0
- Use Case/DM Text: https://docs.google.com/document/d/1glTChLU7tgwCE6jX66N7TqelTEUJ0KKihGnzA6THtTM/edit

**Comment by msporny** [comment]
This is in process, and about 50% of the spec is done at this point: https://github.com/w3c/vc-test-suite/pull/5

**Comment by TzviyaSiegman** [comment]
https://w3c.github.io/vc-data-model/#use-cases-and-requirements needs to be updated as well.

**Comment by msporny** [comment]
I have made a complete pass through the specification and ensured that all MUSTs, RECOMMENDED, SHOULDs, MAYs (and their respective NOTs), specifically talk about document conformance and do not talk about issuer, holder, or verifier conformance.

**Comment by msporny** [comment]
> The next step is to ensure that the tests in the test suite are aligned w/ all MUST/SHOULD/MAYs in the document via w3c/vc-test-suite#6.

This is now done thanks to @bigbluehat. The only thing left is to implement the tests. @gannan08 and @dmitrizagidulin have the action to implement the rest of the tests in the test suite. That is not blocking us from going into CR, so I'm closing this issue.
