### ISSUE TITLE
Deontic concepts supported by termsOfUse 

### ISSUE THREAD

**Issue by simonstey** [w3c/vc-data-model#276]
(related to #269 #234)

<hr />

[6.3 Terms of Use](https://w3c.github.io/vc-data-model/#terms-of-use)
> termsOfUse - The value of this property MUST be one or more terms of use that tell the verifier **what actions it MUST perform** if it is to accept the verifiable credential or verifiable presentation.
 
[Example 14](https://w3c.github.io/vc-data-model/#ex-14-usage-of-termsofuse-property-by-an-issuer) - _"the issuer is **prohibiting** a verifier from storing the data in an archive."_
[Example 15](https://w3c.github.io/vc-data-model/#ex-15-usage-of-termsofuse-property-by-a-holder) - _"the holder, who is also the subject, is **prohibiting** the verifier (https://wineonline.example.org) from using the information provided to correlate the holder/subject by using a 3rd party service."_

[ODRL](https://www.w3.org/TR/odrl-model/) defines 3 types of [Rules](https://www.w3.org/TR/odrl-model/#rule):
- [Permissions](https://www.w3.org/TR/odrl-model/#permission) - actions one is allowed to do (but doesn't have to) 
- [Prohibitions](https://www.w3.org/TR/odrl-model/#prohibition) - actions one is not allowed to do
- [Duties](https://www.w3.org/TR/odrl-model/#duty) - actions one has to do

Given above definition of ToU, accompanying examples 14/15, and ODRL's rule types, what actions does a verifier **have to** perform in examples 14/15? 

Someone who's not familiar with the basics of Deontic Logic, hence does not know that:
```
F(a) ... Prohibition of a
P(a) ... Permission of a
O(a) ... Obligation/Duty of a

P(a) = -O(-a)
F(a) = O(-a) 
```
might expect to see Duties only.

<hr /> 

**Proposal**:  depending on the set of supported rule types, consider adding:
- "_what actions it MUST NOT perform_" for prohibitions
- "_what actions it MAY perform_" for permissions

**Comment by David-Chadwick** [comment]
Good catch. Given your correction, we should change the definition to say:

termsOfUse - The value of this property MUST be one or more terms of use that tell the verifier what actions it either MUST perform (i.e. an Obligation) or MUST NOT perform (i.e. a Prohibition) or MAY perform (i.e. a Permission) if it is to accept the verifiable credential or verifiable presentation.

And update the examples to provide one example of each type.

**Comment by msporny** [comment]
Fixed in https://github.com/w3c/vc-data-model/commit/1eef2202f17498bbc9598ec109430ec48dde573b.
