### ISSUE TITLE
Just "registry" not "data verification registries"

### ISSUE THREAD

**Issue by ChristopherA** [w3c/vc-data-model#292]
In https://github.com/w3c/vc-data-model/pull/279 the changes added the term "data verification registries".

There are many possible registries that might be specific to various DID methods, schema registries, TOU registries, revocation or status registries, etc. So just call these "registries". And of course queries to ANY registry should anonymize or not have the issuer or subject.

**Comment by ChristopherA** [comment]
After writing this I see an email from @msporny about a poll on this topic at https://docs.google.com/document/d/1dCPGKiW9uqVd1X_Ye6BCFt4qzRRGjPNfTuYEQKIZk6k

**Comment by msporny** [comment]
The poll resulted in the following outcome:

https://lists.w3.org/Archives/Public/public-vc-wg/2018Dec/0004.html

The specification has been updated to reflect the consensus of the group. Closing issue.
