### ISSUE TITLE
JWTs encoding/decoding rules are not clear

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#336]
At present, JWT encapsulation of Verifiable Credentials strips values from VCs that are required for proper understanding by generalized verifiable credentials libraries. For example, the `id` field is stripped from vc.credentialSubject, which would result in an anonymous subject if processed by a JSON-LD processor.

The JWT section should have rules for encapsulating a VC in a JWT and transforming the encapsulated VC in JWT back to a general VC that any VC library could process.

Alternatively, JWT encapsulation wouldn't modify the VC at all. Trying to save a few hundred bytes is a particularly strange thing to do considering most transports will gzip and do the compression appropriately for duplicated information.

So, either:

1. Do not pre/post process VCs when encapsulating them in JWTs, or
2. Clarify the rules for extracting a VC from a JWT such that VC libraries don't care if the data was encapsulated in a JWT or not.

**Comment by davidlehn** [comment]
Along with this it would be good to add notes or comments for the JWT examples pointing out where the data structure has changed.

**Comment by awoie** [comment]
From a storage perspective, it makes sense to save some bytes if you consider limited storage media such as smart cards, or visual encodings such as QR codes.

@msporny With regards to 2., it might not be feasible to transform the JWS implicit `proof` to an equivalent JSON-LD `proof` attribute and still keeping the signature value intact, right?

**Comment by msporny** [comment]
Addressed in PR #365, closing.
