### ISSUE TITLE
Review from Credentials Community Group

### ISSUE THREAD

**Issue by ChristopherA** [w3c/vc-data-model#360]
It was requested at our last CCG meeting that the W3C Credentials Community Group should do an independent review of the VC-Data-Model Spec. @ipatka is a member of the CCG but not a member of VCWG and volunteered to do so. The comments are at:

https://github.com/w3c-ccg/community/issues/28#issuecomment-450777534

Let us know if there is more review that you need from the CCG.

-- Christopher Allen, co-chair

**Comment by msporny** [comment]
I have responded to all comments and applied changes to the specification as a result of the review. Detailed changes are here: https://github.com/w3c-ccg/community/issues/28#issuecomment-459998140. 

Marking issue as addressed and closing.
