### ISSUE TITLE
[Identifiers] Clarify/be more explicit about where DIDs can be (optionally) used

### ISSUE THREAD

**Issue by mwherman2000** [w3c/vc-data-model#362]
In https://w3c.github.io/vc-data-model/#identifiers, it states...
>The example above uses two types of identifiers. The first identifier is for the credential and uses an HTTP-based URL. The second identifier is for the subject of the credential (the thing the claims are about) and uses a decentralized identifier, also known as a DID.
>NOTE
>As of this publication, DIDs are a new type of identifier that are not necessary for verifiable credentials to be useful. Specifically, verifiable credentials do not depend on DIDs and DIDs do not depend on verifiable credentials. However, it is expected that many verifiable credentials will use DIDs and that software libraries implementing this specification will probably need to resolve DIDs. DID-based URLs are used for expressing identifiers associated with cryptographic keys and other machine-readable information that is useful when used in the verifiable credentials ecosystem.

In the NOTE, can this paragraph clarify/be more explicit about where DIDs can be (optionally) used?
e.g. anywhere that a “id” attribute appears in a VC?  

For example,
•	The id of the VC itself
•	The id of the verifiableCredential (most common use case in the VC data model document)
•	Other role-based id’s: owner, parent, child, holder, etc.
•	The id of a claim
•	…

**Comment by stonematt** [comment]
not CR blocker. will continue to work on clarification.

**Comment by msporny** [comment]
I added a few examples in https://github.com/w3c/vc-data-model/commit/0cefae2e7e8f6b6cdd41b69b90d7f1eee751b004 but stopped short of saying "anywhere `id` can be expressed" as DIDs can be used for the `issuer`, `verificationMethod`, and many other places a regular URL can be used. It's also not a good idea to use them for credential identifiers. In any case, this specification isn't supposed to talk about DIDs that much (as that's speculative work) and so we're trying to hint that they're on the horizon, not quite here yet, useful, but not mandatory. Any concrete spec text to get us there would be appreciated, but for now, I'm marking this issue as closed. Please re-open if you disagree.
