### ISSUE TITLE
[Mode of Operation] Is it necessary to specify only the *final* holder ...

### ISSUE THREAD

**Issue by mwherman2000** [w3c/vc-data-model#363]
In https://w3c.github.io/vc-data-model/#mode-of-operation, it states
> The final holder presents its verifiable credentials to the verifier in a verifiable presentation, requesting a supported action.

Is it necessary to specify that only the *final* holder a present its VCs to the verifier?  Why can't any holder in the chain present the VCs to a verifier vs. just the final holder?

**Comment by David-Chadwick** [comment]
On 03/01/2019 15:55, Michael Herman (Toronto) wrote:
> In https://w3c.github.io/vc-data-model/#mode-of-operation, it states
> 
>     The final holder presents its verifiable credentials to the verifier
>     in a verifiable presentation, requesting a supported action.
> 
> Is it necessary to specify that only the /final/ holder a present its
> VCs to the verifier? Why can't any holder in the chain present the VCs
> to a verifier vs. just the final holder?

Of course any holder MAY present the VC, but in this case only the final
holder DID present the VC. So how to differentiate between the holder
that did and the holder that didnt?

David

**Comment by msporny** [comment]
I believe @David-Chadwick has answered your question @mwherman2000 and I don't expect we need to add more text to the spec to make that distinction. Closing, please re-open if you disagree (and suggest concrete spec text so we have something to consider/refine).

**Comment by brentzundel** [comment]
I believe this has been addressed via the solution for issue #577 and should be closed
