### ISSUE TITLE
ZKP-Examples have different id values in credentialSchema

### ISSUE THREAD

**Issue by awoie** [w3c/vc-data-model#364]
In Example 19 and 20, the `id` in the `credentialSchema` of the verifiable credential does not match the id of the verifiable presentation. IMO, this should be the same:
`did:example:schema:3jf74yr7dsjw83jf`vs `did:sov:schema:3jf74yr7dsjw83jf`

**Comment by brentzundel** [comment]
For Sovrin ZKPs they would almost never be the same.

**Comment by awoie** [comment]
Alright. Could we change ```did:sov:schema:3jf74yr7dsjw83jf``` in ```did:example:schema:4er38er2uior02xy``` to keep the spec more platform agnostic.

**Comment by msporny** [comment]
Fixed in https://github.com/w3c/vc-data-model/commit/ac6c5c9d669037498cdc3d3a9840e5d1227d6a43.
