### ISSUE TITLE
Remove id related requirement in Presentations

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/vc-data-model#367]
This requirement is stated earlier, and doesn't seem to directly effect the processing of a Presentation--so it feels repetitive and a bit confusing:
> The value associated with the id property MUST be a URI.

https://github.com/w3c/vc-data-model/blob/30591535e6efe7535cecadc18baa5c12cd8adc94/index.html#L1285-L1286

Suggestion is to remove it as it's handled in [6.2 Identifiers](https://w3c.github.io/vc-data-model/#identifiers).

**Comment by msporny** [comment]
Agreed that it's repetitive and should be removed. Fixed in a080626539bf565046fd881a52568687af8f527d.
