### ISSUE TITLE
Remove example context URL from Example 9 in 7.1 Extensibility

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/vc-data-model#368]
This series of examples starts with [example 9](https://w3c.github.io/vc-data-model/#ex-9-a-simple-credential) which includes an example extension context `https://example.com/examples/v1`, but it is not used (afaict) within that example and the follow-on examples ultimately replace it.

Suggestion is to remove the second context value (`https://example.com/examples/v1`) in [example 9](https://w3c.github.io/vc-data-model/#ex-9-a-simple-credential).

**Comment by msporny** [comment]
In theory, `"name": "Jane Doe"` comes from the example context, so we can't remove it. The same goes for the other examples. The `credentials/v1` context only contains the bare minimum (typically almost all of the terms in `credentialSubject` are not defined in the `credentials/v1` context.
