### ISSUE TITLE
Defining expected order of credential `type` values

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/vc-data-model#371]
In the [Semantic Interoperability](https://w3c.github.io/vc-data-model/#semantic-interoperability) section, this text is in the first bullet point:
> ensuring the expected values exist in the expected order for the credential type being processed

However, it's not clear how the "expected order" is supposed to be expressed. The expected values would (by necessity) be described within the `@context`, but their preferred/required "ordering" can't be expressed there (afaik).

There's follow on text about pointing to an "extension specification" which MUST be human-readable and SHOULD ("preferably") be machine-readable...but it's not clear what that would actually be in fact:
> The expected order MUST be defined by at least a human-readable extension specification and preferably, by a machine-readable specification.

What's missing from a test perspective is understanding the description of the "expected order" of those values, so that can be subsequently enforced.

It doesn't seem to be `@context` related because the @context can't force the ordering of multiple type values, but hopefully I'm missing something obvious here. 😉

**Comment by BigBlueHat** [comment]
Presumably "ensuring the expected values exist" involves checking the `@context` file (which is the primary thing in the MUST of that sentence) to be sure the values match. However, knowing and testing the "expected order" is still elusive.

**Comment by msporny** [comment]
We're trying to enforce sealed context behavior w/o having JSON-LD 1.1 done. So, we're stating what would need to happen today (extra things that JSON-LD processors would have to do today)... and then expecting future JSON-LD processors make the extra checks unnecessary.

So, we have to make sure JSON-LD processors throw errors when things are redefined (emulating sealed contexts) and make it such that JSON-LD processing is absolutely not required for people that don't want to do that. 

We also have to make sure the `@context` property values are in a specific order, where the VC context comes first, and other contexts are layered on top in a very specific order. This allows people that are not doing JSON-LD processing at all to kinda-sorta do a half-baked thing and be okay most of the time. Fundamentally, the code they're going to write is this:

```javascript
if(obj['@context'][0] !== 'https://w3.org/2018/credentials/v1' || obj['@context'][1] !== MARKET_VERTICAL_CONTEXT) {
  // something is wrong w/ the context ordering, so I don't understand the payload
}
```

Does that make sense?

**Comment by msporny** [comment]
Oh, wait a second, I think I finally understand the question. I'll look into type ordering... sounds like that spec text is wrong.

**Comment by BigBlueHat** [comment]
> Oh, wait a second, I think I finally understand the question. I'll look into type ordering... sounds like that spec text is wrong.

Also, fwiw, this text is only about JSON-based processors, so it shouldn't effect JSON-LD-based ones (afaict).

**Comment by msporny** [comment]
@BigBlueHat can you confirm that I fixed the issue that you hit? I think the major issue was that `type` had `<code>type</code>` when the more common English usage of the word was desired.

**Comment by BigBlueHat** [comment]
@msporny that works. The ordering of the "type" will not be enforce-able by machine-based tests unless that mandatory ordering need is machine-readable--i.e. checking the expressed ordering against the desired ordering will take human eyeballs afaict...which is maybe OK?
