### ISSUE TITLE
Issues from CCG review

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#383]
The following changes are suggested in order to address the points raised in the CCG review https://github.com/w3c-ccg/community/issues/28

1. Add a definition of selective disclosure to the Terminology section. Here is a strawman

selective disclosure
the ability to only disclose to a verifier either a subset of the properties of, or a derived predicate from, a verifiable credential.

2. Add a definition of atomised credentials to the Terminology section. Here is a strawman

atomized credential or atomization
where the issuer issues a set of verifiable credentials, each containing a single property of the subject, rather than issuing a single verifiable credential containing multiple properties of the subject. Atomizing a credential is one way of allowing the holder to selectively disclose the properties of the subject.

3. In the Trust Model section, add "or" at the end of the first indented bullet to read

 -  Include a proof establishing that the issuer generated the credential (that is, it is a verifiable credential), or

**Comment by ChristopherA** [comment]
We should reconcile the suggested language with this document from #RebootingWebOfTrust led by @lwolberg that is now moving to the CCG for further review & improvements. https://github.com/WebOfTrustInfo/rwot5-boston/blob/master/draft-documents/DataMinimization/Data%20Minimzation%20and%20Selective%20Disclosure.md

In particular, the first is “cryptographic selective disclosure”, and atomization is a strategy of data minimization.
