### ISSUE TITLE
Vocabulary location decisions

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#391]
We need to make two decisions before going into CR:

1. Where does the serviceEndpoint vocabulary term go? Which vocabulary?
2. Where does the security vocabulary go?

**Comment by msporny** [comment]
@rhiaro fixed "Where does the serviceEndpoint vocabulary term go?" in https://github.com/w3c/vc-data-model/commit/0313cc4c8b116b0b330b7374651107d457dd0963.

To address the next issue, I recommend that the Chairs and staff contact work with W3C to acquire the following vocabulary URL at W3C:

https://www.w3.org/2018/security

The JSON-LD Context will go in:

https://www.w3.org/2018/security/v1
https://www.w3.org/2018/security/v2

We'll copy the https://w3id.org/security/v1 and https://w3id.org/security/v2 contexts over.

Reassigning to @burnburn @stonematt and @ashimura.

**Comment by brentzundel** [comment]
Decision from F2F in Barcelona: The chairs will take the actions proposed by @msporny in his comment.
Specifically:
- [ ] contact work with W3C to acquire the following vocabulary URL at W3C: https://www.w3.org/2018/security
- [ ] Put the JSON-LD security contexts in 
    - https://www.w3.org/2018/security/v1
    - https://www.w3.org/2018/security/v2

**Comment by burnburn** [comment]
Requested @ashimura  to obtain the URL.

**Comment by burnburn** [comment]
@ashimura says W3C webmaster not happy with VCWG claiming the "security" context and that users will be confused by what it means. Chair decision to go with Kaz' suggestion of https://www.w3.org/2018/credentials/security for now.  Can always request another top-level vocab later.  Waiting for @ashimura .

**Comment by msporny** [comment]
@ashimura, please map the following URLs:

https://www.w3.org/2018/credentials/v1
https://www.w3.org/2018/credentials/security/v1
https://www.w3.org/2018/credentials/security/v2
https://www.w3.org/2018/credentials/examples/v1

to the following locations:

https://w3c.github.io/vc-data-model/contexts/credentials/v1
https://w3c.github.io/vc-data-model/contexts/credentials/security/v1
https://w3c.github.io/vc-data-model/contexts/credentials/security/v2
https://w3c.github.io/vc-data-model/contexts/credentials/examples/v1

**Comment by burnburn** [comment]
Done.
