### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#406]
The current text in section 7.10 states "this specification MUST NOT be used for authorization purposes without an accompanying authorization framework." This is not a statement that can be enforced, nor can you mandate that implementations will not use the VC data model document for authorisation applications. Therefore we should change the text to 
"It is recommended that this specification SHOULD NOT be used for authorization purposes without an accompanying authorization framework."

**Comment by jandrieu** [comment]
Agreed with the point of the correction although my concern is that "authorization framework" is ill defined. Shifting to "SHOULD" helps, but my first take was to replace "accompanying" to "appropriate" to support a bit more flexibility in the definition of the term.

**Comment by stonematt** [comment]
we'll discuss this in the PR as we refine spec text

**Comment by stonematt** [comment]
closed w/ PR
