### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#408]
Most of our data model document talks about the holder, and refers to the subject much less than to the holder.

However when we get to section 9, Verification, we only address how the subject should be verified, and say nothing about holder verification, when in fact the verifier is only contacted by the holder and may not know anything about the subject (apart from what the presented VCs contain). Consequently there appears to be a gaping hole in the verification section of our document which should be rectified.

**Comment by burnburn** [comment]
@grantnoble to take this (can't assign)

**Comment by grantnoble** [comment]
👍

**Comment by brentzundel** [comment]
Decision from F2F Barcelona:
- [ ] @grantnoble will review the verification section for language about subjects and holders and raise a PR to make any needed changes.
- [ ] If that PR is needed, close this after it is merged.

**Comment by grantnoble** [comment]
PR #445 to address this issue.

**Comment by msporny** [comment]
PR #445 has been merged. Changes have also been applied in 6d157ca54e192f8461c7d5b87508ce4d4c342e20 that relate to this issue. The issue has been resolved. Please re-open or submit a correcting PR if the issue has not been addressed.
