### ISSUE TITLE
ZKP section needs corrections 

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-data-model#414]
The zkp section of the data model, especially the example, needs to be modified to better reflect the actual format of a zkp-capable credential.

**Comment by brentzundel** [comment]
Decision at F2F Barcelona:
- [ ] @msporny and @ken-ebert will review PR #413

**Comment by brentzundel** [comment]
PR #453 is in, if merged that will close this issue.

**Comment by msporny** [comment]
PR #453 has been merged. Closing this issue. Reopen if you disagree.
