### ISSUE TITLE
Context URL is down .. and yet another question about override

### ISSUE THREAD

**Issue by chaoxinhu** [w3c/vc-data-model#427]
I have tried to visit the current presented @context URL and they are all inaccessible already:
https://www.w3.org/2018/credentials
https://www.w3.org/2018/credentials/v1
Now the only working URL is the old one: https://web-payments.org/contexts/credentials-v1.jsonld
Please consider to fix this.

Also there is another question.. there does not seem to be any overriding restrictions on same terms existing on different context URLs. I have compared with the @context descriptions between VC data models and DID. In DID specs, it is clearly defined that:

> DID method specifications MAY define their own JSON-LD contexts. However it is NOT RECOMMENDED to define a new context unless necessary to properly implement the method. Method-specific contexts MUST NOT override the terms defined in the generic DID context.

This can be found in https://w3c-ccg.github.io/did-spec/#context yet however I could not find any similar restrictions in VC data model. Is this an expected behavior?

Thanks in advance.

**Comment by brentzundel** [comment]
Decision from Barcelona F2F:
@ashimura will shepherd to close
- [ ] 1 update content in w3c
- [ ] Auto-copy from github
- [ ] Open New issue: Turn off auto-copy when we transition to PR

**Comment by burnburn** [comment]
Reminder email sent to @ashimura .

**Comment by stonematt** [comment]
use this? 
https://github.com/w3c/vc-data-model/blob/gh-pages/contexts/credentials-v1.jsonld

**Comment by msporny** [comment]
@ashimura, please map the following URLs:

https://www.w3.org/2018/credentials/v1
https://www.w3.org/2018/credentials/security/v1
https://www.w3.org/2018/credentials/security/v2
https://www.w3.org/2018/credentials/examples/v1

to the following locations:

https://w3c.github.io/vc-data-model/contexts/credentials/v1
https://w3c.github.io/vc-data-model/contexts/credentials/security/v1
https://w3c.github.io/vc-data-model/contexts/credentials/security/v2
https://w3c.github.io/vc-data-model/contexts/credentials/examples/v1

**Comment by msporny** [comment]
@chaoxinhu wrote:
> Also there is another question.. there does not seem to be any overriding restrictions on same terms existing on different context URLs. I have compared with the @context descriptions between VC data models and DID.

See this section -- https://w3c.github.io/vc-data-model/#syntactic-sugar

specifically:

> The @protected properties feature of JSON-LD 1.1 is used to ensure that terms defined by this specification cannot be overridden. This means that as long as the same @context declaration is made at the top of a verifiable credential or verifiable presentation, even when issuers do not use a JSON-LD processor, that interoperability is still guaranteed if verifiers use a JSON-LD processor.

**Comment by chaoxinhu** [comment]
Thanks for your assistance @msporny ! Really appreciated.

**Comment by ashimura** [comment]
Regarding the redirection from www.w3.org to w3c.github.io, I'm asking the W3C Webmaster to set up the configuration.

Please note that after some more discussion with @burnburn and @stonematt , I'm asking the Webmaster to set a redirection from https://www.w3.org/2018/credentials to https://w3c.github.io/vc-data-model/contexts/credentials/ so that we can add necessary addition (e.g., V2 examples) later.

**Comment by burnburn** [comment]
Done.
