### ISSUE TITLE
Evidence ID

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#432]
As currently specified, the Evidence property contains an ID field, but we do not specify
a) whether the ID is mandatory or optional
b) what the ID actually points to.
This needs to be clarified.

Could I suggest that we say that the ID field is optional, but if present, it contains a URL that points to where more information about this instance of evidence can be found.

**Comment by brentzundel** [comment]
Decision from F2F Barcelona:
- [ ] @David-Chadwick will submit a PR that addresses this.

**Comment by stonematt** [comment]
watch PR #443 for Evidence language

**Comment by brentzundel** [comment]
This issue has been addressed by PR #443

**Comment by msporny** [comment]
PR #443 has been merged. There is now language in the specification that addresses the issue that was raised. Closing this issue. Reopen if you disagree.
