### ISSUE TITLE
anonymous presentation - missing in the standard

### ISSUE THREAD

**Issue by glauserr** [w3c/vc-data-model#435]
Indy anonCreds provides functionality for anonymous credentials, credentials which can be presented to a verifier without revealing its did but with a ZK-proof that I am the owner of the credential. 

Are there any plans to embed standardization of anonymous credentials in the document?

**Comment by brentzundel** [comment]
The data model was designed to be compatible with zero-knowledge proof
systems such as Indy's anonymous credentials, but does not require all
implementers to use zero-knowledge proofs.
There is text throughout the document that attempts to illustrate how the
various components may be used with zero-knowledge proof systems, or that
points out components that may be omitted if a zero-knowledge proof system
is used.
There is also a section of the document that addresses zero-knowledge
proofs.
If there are specific sections of the data model that you feel would
benefit from greater attention to zero-knowledge proofs, I would appreciate
your input.

**Comment by brentzundel** [comment]
Decision from F2F Barcelona:
- [ ] @brentzundel will address this via the new PR referred to in Issue #414 
- [ ] @brentzundel will link that PR to this issue.
This issue should be closed when the PR is merged.

**Comment by glauserr** [comment]
@brentzundel thanks for your fast response. I agree, not everybody have to implement zero knowledge proof systems, but it does not supersede to standardize it. 
The section in the document does only give some examples about ZK support of verifiable credentials and verifiable presentations. It does create a standard for it. E.g Indy's anoCred implementation of vc and vp has a different format than the examples describe. It would be helpful to work to a standardization in this area too.

**Comment by brentzundel** [comment]
@glauserr, I am in the process of submitting PRs to address some issues
related to the zkp section, one of which may address the examples.
The current format of indy credentials and presentations is quite different
from the examples in the data model, but rather than try to introduce the
current format of indy credentials into the W3C Verifiable Credential data
model, @ken-ebert and I are working on a HIPE that will propose changes to
indy anoncreds format so that it can use the standard data model.

**Comment by burnburn** [comment]
I believe the request to standardize anonymous credential use in VCs is a new feature request.  It is the chairs' understanding that such use is already possible, even if not standardized.  Clarification of that use is appropriate at this stage, but as feature freeze was last November it would be inappropriate to standardize a full new feature.
