### ISSUE TITLE
Reference to ISO8601 should be more specific

### ISSUE THREAD

**Issue by aphillips** [w3c/vc-data-model#437]
A number of timestamp values appear in the document. One example is:

5.2 Issuer
https://w3c.github.io/vc-data-model/#issuer

> The value of this property MUST be a string value of an [ISO8601] combined date and time string and represents the date and time the credential was issued.

This definition of a date-time value, while the correct choice, is insufficiently specific. I would recommend referencing RFC3339 `date-time` explicitly. 

Note well that use of an offset or (better!) use of UTC ("`Z`") is necessary for actual timestamp values to work correctly. Time values that are not in or convertable to UTC timestamps are said to "float" and are subject to local walltime interpretation (cf. [WWTZ](https://www.w3.org/TR/timezone)). You may wish to provide either a health warning or forbid the use of offset-free values (using RFC3339 date-time accomplishes the latter).

This was discussed in I18N WG here: https://www.w3.org/2019/02/28-i18n-minutes.html#item07

**Comment by brentzundel** [comment]
Decision from F2F Barcelona:
- [ ] @chaals will submit a PR that changes the type for a date from ISO8601 to W3C date-time.

**Comment by aphillips** [comment]
(I don't have permission to reopen)

I made a comment on the PR. The reference change on its own isn't quite sufficient, since RFC3339 provides a number of predefined formats. The use of `date-time` explicitly is an important part of the comment.

**Comment by msporny** [comment]
> The use of date-time explicitly is an important part of the comment.

Ok, reopened, working on it now.

**Comment by msporny** [comment]
Alright, closed in https://github.com/w3c/vc-data-model/commit/c0dafd0250f3c6d212bac7a356b6f449c56b4bc9 ... let me know if that doesn't work for you @aphillips.

**Comment by aphillips** [comment]
Thanks Manu. LGTM.
