### ISSUE TITLE
VC is verifiable without proof property in case of JWT

### ISSUE THREAD

**Issue by awoie** [w3c/vc-data-model#438]
According to the spec: 
> The data model described in this specification is designed to be proof format agnostic. 

JWT proofs don't make use of the `proof` property. The specification needs to be fixed that allows JWT proofs, i.e., JWS, to be used regardless of the presence of the `proof`property. 

The suggestion is to specifically fix the description of the `proof`property which says that without a `proof`property a credential is not verifiable:
> For a credential or presentation to be verifiable, the following property MUST be present

Furthermore, we should discuss if section 4.5 Proofs (Signatures) should be moved to section 6.3.2 Linked Data Proofs.

**Comment by dmitrizagidulin** [comment]
+1, although I think we should phrase it in terms of switching off of the signature method.

LD Signatures - `proof` REQUIRED.

JWS signatures - proof not required (but `signature*` field is required, as per the spec, etc)

**Comment by awoie** [comment]
please also update the corresponding test in the test suite and make the proof property optional.
