### ISSUE TITLE
The table of format comparisons should be replaced by a section for each proposed format

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-data-model#439]
Decision from F2F Barcelona:
A proponent for each format will write a section in the implementation guide describing the format. 
- JSON-LD proofs (Manu)
- JSON-LD + JWT and JSON + JWT (Oliver)

To do:
- [ ] @stonematt will open an issue in the implementation guidance repo to track this
- [x] @msporny will write the section on LD Proofs
- [ ] @awoie will write the section on JSON-LD + JWT and JSON + JWT
- [ ] close this issue

**Comment by msporny** [comment]
Moved to https://github.com/w3c/vc-imp-guide/issues/8 ... this issue will be tracked over there now. Closing issue.
