### ISSUE TITLE
Conformance clauses are missing, wrong or inconsistent

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#440]
Reviewing the conformance statements (MUST, MAY, SHOULD) in the normative sections of the data model has revealed the following problems:
1. The following properties have no conformance statement: credentialSubject, @context, issuer, refreshService, evidence, credentialSchema
2. The following sections have inconsistencies: 4.3 on types lists the properties that must have types but does not include all the properties that must have types, proof and JWT encoding, 
3. The following properties have wrong conformance statements: type, credentialStatus, expirationDate, termsOfUse

**Comment by jonnycrunch** [comment]
related to https://github.com/w3c/vc-data-model/issues/421#issuecomment-470582105

**Comment by brentzundel** [comment]
This issue has been addressed by PR #443

**Comment by msporny** [comment]
PR #443 has been merged. Closing this issue as the updated conformance statements written by @David-Chadwick and refined by @brentzundel and @msporny are in the spec now. Reopen if you disagree.
