### ISSUE TITLE
RESOLUTION: Make the expression of the @context property mandatory in the data model

### ISSUE THREAD

**Issue by stonematt** [w3c/vc-data-model#444]
based on discussion and resolution on Day 2 in Barcelona.  Update spec to reflect that @context is a required attribute.

See https://www.w3.org/2019/03/05-vcwg-minutes.html for details.

**Comment by David-Chadwick** [comment]
I can add this to the PR on conformance if required

**Comment by msporny** [comment]
This issue would be fixed if PR https://github.com/w3c/vc-data-model/pull/443/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR857 is merged.

**Comment by jonnycrunch** [comment]
This is a related issue:  https://github.com/w3c/vc-data-model/issues/421#issuecomment-471068235

**Comment by burnburn** [comment]
Issue #421 has been deferred.  However, your comment may still be relevant to how this issue (#444) is resolved.

**Comment by brentzundel** [comment]
This issue has been addressed by PR #443

**Comment by msporny** [comment]
PR #443 has been merged. The new language addresses the original issue that was raised. Closing this issue. Reopen if you disagree.
