### ISSUE TITLE
Is Proof mandatory or optional?

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#447]
The Proof is said to be mandatory in a VC but the JWT mapping says it is optional.
I suggest that JWT makes it mandatory and sets the type to JWT with no further content

**Comment by burnburn** [comment]
Decision at Barcelona f2f was that one, or the other, or both, was acceptable.  We just need a PR.

**Comment by msporny** [comment]
Fixed in 0985ddc6ef4ac2e937f5040ee9578613c56f81de. Please re-open the issue if you disagree.
