### ISSUE TITLE
Add section/language about presentation of claims

### ISSUE THREAD

**Issue by jandrieu** [w3c/vc-data-model#46]
The dominant mental model is that a singular claim is issued and later presented to an inspector. However, there has been significant discussion about how a subset of a credential may be presented as well as how claims from multiple issuers may be aggregated for presentation.  

This significantly impacts privacy around the issue of minimal disclosure and selective disclosure. 

In particular, what is the thing that is presented when it is not a single credential from a single issuer? Given a name for that we can flesh out how a controller might construct such presentations from multiple credentials. Right now, there is no language about this.

**Comment by jandrieu** [comment]
Based on our conversations last meeting, https://www.w3.org/2017/06/20-vcwg-minutes.html, I think it's clear we don't have a consistent term that we use for what is presented to the inspector.

We do have the terms credentials and entity profiles.

However, we do *not* describe the workflow as 

1. Issuers issue credentials
2. Claimants create entity profiles combining one or more claims from one or more credentials
3. Claimants present entity profiles to Verifiers
4. Verifiers verify the claims are statements made by the issuer

And I think we should. The current equivalent language is
1. An Issuer issues Claims about Subjects using Identifiers.
2. Claimant presents claims (either directly or indirectly) to an Verifier.
3. A Verifier verifies that the Claims represent statements made by the original Issuer.

Even if the terms I use above aren't quite ideal, I think we need to shift our language to use language similar to this to highlight that the lifecycle of a claim is far more flexible than traditional, static credentials where you *do* have to give your entire driver's license to the bouncer to get into the bar.

**Comment by jandrieu** [comment]
The poll terminology may be fine as long as we clarify in the FPWD that this is in the simplest case of a single claim. To address issues of minimal and selective disclosure we should then also expand that flow to clarify the terms credential and entity profile.

I think our conversations often stumble because we conflate credentials, claims, and entity-profiles.

I'd prefer to just have the one inclusive flow from credentials through to profiles and for us to gradually learn to be more rigorous in how we talk about it. 

For instance, I think it makes far more sense that issuers issue credentials, and that claimants present profiles. Period. The claims themselves are the individually verifiable statements within those credentials and profiles, but even when a credential has a single claim, it is clearer to discuss the issuer issuing the credential. Similarly, when a profile has a single claim, calling it a profile makes it clear the place it has in the process, who controls it, and who receives it.

I believe that clarity would improve the dialog.

**Comment by David-Chadwick** [comment]
Hi Joe. Do you think this issue has now been resolved in the latest data model document? If so can we close this issue.
If not, can you propose some text changes below that would resolve the issue for you.
Thanks

**Comment by jandrieu** [comment]
Yes. We can close this issue.
