### ISSUE TITLE
Add "information related to the kind/type of credential" as a bullet in section 1.1

### ISSUE THREAD

**Issue by RieksJ** [w3c/vc-data-model#462]
Section 1.1 lists 5 pieces of information that a physical credential consists of. It seems obvious that the idea here is to mimic these pieces for digital credentials. If this is the intention of the authors, then **I suggest to add another piece of information: "information related to the kind/type of the credential (for example: Dutch passport, American driving license, Health insurance)"**. 

Information about the kind/type of a credential might well include "Information related to the specific attribute(s) or properties being asserted" (third bullet), but is broader than that: it may include, or refer to, policies for issuing, use and revocation, addresses of where to send messages to that request for issuing or revocation, and more.

**Comment by chaals** [comment]
That is "information related to the specific attribute(s) or properties being asserted..." (e.g. that the subject has been approved to drive a car, small bus, or bulldozer in the state of Massachusetts), which is already there. 

As an editorial improvement it would make sense to clarify this with an example, as is already the case with preceeding points in the list.

**Comment by burnburn** [comment]
In call today @David-Chadwick said he would write a PR.

**Comment by David-Chadwick** [comment]
PR#503 fixes this issue and adds further clarification to the other bullet points

**Comment by msporny** [comment]
The PR has multiple reviews and has been merged. The next step is to see if the WG agrees with the change and closure of the issue.

**Comment by stonematt** [comment]
Resolved on VCWG call 4/16/2019.
RESOLVED: Issue #462 is addressed by PR #503, which makes non-normative changes detailing type information stored in a credential as requested by the reviewer. The PR has been approved by multiple parties and has been merged. Issue #462 should be closed.

Plan to close in 7days
