### ISSUE TITLE
Definition of 'credential

### ISSUE THREAD

**Issue by RieksJ** [w3c/vc-data-model#465]
Section 1.1. has "A verifiable credential can represent all of the same information that a physical credential represents". While not normative, it would be nice to accomodate for this in the definiton of 'credential', which currently is "A set of one or more claims made by an issuer. "

I suggest to rephrase that, e.g. as follows: "A set of one or more claims, and metadata about this set, made by a single issuer".

**Comment by brentzundel** [comment]
I feel this is explained very well already in the terminology section.
From section 3.2:
`A credential is a set of one or more claims made by the same entity. Credentials might also include an identifier and metadata to describe properties of the credential, such as the issuer, the expiry date and time, a representative image, a public key to use for verification purposes, the revocation mechanism, and so on. The metadata might be signed by the issuer. A verifiable credential is a set of tamper-evident claims and metadata that cryptographically prove who issued it.`

**Comment by burnburn** [comment]
@RieksJ we believe that the response from @brentzundel resolves this issue, with no changes planned for the specification.  We will close this issue two weeks from today if we receive no further concerns from you in the issue.

**Comment by RieksJ** [comment]
I can live with that. I recognize that while it is my preference of being as precise as possible when stating definitions, others are satisfied when the description is not wrong and readers can find the rest elsewhere.
