### ISSUE TITLE
Anybody knows about the details of vc?

### ISSUE THREAD

**Issue by DianeFeng** [w3c/vc-data-model#468]
Anybody knows about the details of vc? I don't really understand very much>=<

**Comment by burnburn** [comment]
Hi @DianeFeng you might find this primer helpful:  https://github.com/WebOfTrustInfo/rwot7-toronto/blob/master/topics-and-advance-readings/verifiable-credentials-primer.md

If you are interested in the work, I suggest visiting the [Credentials Community Group](https://w3c-ccg.github.io/).  It is a good entry point into this space.
