### ISSUE TITLE
JWS Examples and JOSE Consistency

### ISSUE THREAD

**Issue by jricher** [w3c/vc-data-model#470]
The JWS examples in the LD Proofs section use the JWS Detached method from RFC 7797, while the JWT proofing section uses JWS from the original JOSE suite, with a specific requirement to use the JWT compact serialization. The detached serialization method is not mentioned in either this document or the LD-related documents linked from this specification.

**Comment by msporny** [comment]
Ping @dlongley -- is a PR for this in process?

**Comment by dlongley** [comment]
@msporny, No, but I believe what @jricher requested as a simple "Note" after each `RsaSignature2018` examples that had an informative reference to its spec and that mentioned it used a JWS detached signature with an informative reference to the JWS spec.

**Comment by jricher** [comment]
@dlongley That would be sufficient for my concerns and would help developers reading through the examples.

**Comment by stonematt** [comment]
From VCWG call on April 30, 2019: 
RESOLUTION: Issue #470 should be addressed by making a set of non-normative changes to the specification that adds a simple note after each RsaSignature2018 example with an informative reference to that spec and that mentions it used a JWS detached signature with an informative reference to the JWS spec. Issue #470 should be closed after the PR is merged.

**Comment by burnburn** [comment]
Now it's been 7 days.  Closing.
