### ISSUE TITLE
Need clarity on ID URIs and what dereferencing does

### ISSUE THREAD

**Issue by mavarley** [w3c/vc-data-model#473]
Section 4.2 "id" and 4.5 "issuer"
_The value of the id property MUST be a single URI. It is RECOMMENDED that dereferencing the URI results in a document containing machine-readable information about the identifier._

I understand what resolving a DID gets the verifier - I am not sure what resolving a HTTP url is supposed to result in (if anything) and when is it recommended to use a non-resolvable ID (like the urn:uuid:...). I think needs to either define some guidance, or explicitly state this is out of scope. 

Hopefully we can provide guidance, for interoperability.

**Comment by burnburn** [comment]
Anything in this document other than the data model and syntactic representations is out of scope.  The group is expressly prevented from any other definitive guidance.  However, the group was encouraged to provide limited informative guidance.  There is a [separate document](https://github.com/w3c/vc-imp-guide) being started, important to this group, that will provide more implementation guidance.

Please post this question to that repo.  Closing.
