### ISSUE TITLE
Subject matters (conflicting definitions, meaningless use, ...)

### ISSUE THREAD

**Issue by RieksJ** [w3c/vc-data-model#481]
[Section 1.2](https://w3c.github.io/vc-data-model/CR/2019-03-26/#ecosystem-overview) defines 'subject' as: `A role an entity might perform by having one or more verifiable credentials asserted about it`. [Section 2](https://w3c.github.io/vc-data-model/CR/2019-03-26/#terminology) defines it as: `An entity about which claims are made`.

While these definitions may seem to be the same, the first (and older) one was based on the assumption that every credential contains claims about the entity to which it has been issued. This assumption turned out to be false (see e.g. #55): in fact, it is currently ok to issue a credential to an entity about whom no claim is made in that credential. An example is a credential that only contains claims about a specific dog, and is issued to its owner. The definition in section 2 better reflects this new way of thinking.

This issue 
1. generically calls for more unity in texts/descriptions that are definition-like, by using literal quotes from the authoritative definitions. 
2. specifically calls for modifications in the texts of section 1.2, by replacing the first sentence of the description of every role with the definition as is given in section 2 (note that the definitions or roles other than 'subject' have recently been updated).
3. calls for adding a note, perhaps extending the note at the bottom of section 3.2, saying something like `It is (also) possible to have a credential that does not contain any claims about the entity to which the credential was issued. An example is a credential that only contains claims about a specific dog, and is issued to its owner.`

This issue is related to [this comment](https://github.com/w3c/vc-data-model/issues/464#issuecomment-476984796) of #464, which calls for replacing each occurance of the phrase "subject of the credential" with a correct representation of what is meant.

**Comment by brentzundel** [comment]
@RieksJ Please let me know if the changes proposed in PR #508 and #509 address this issue to your satisfaction.

**Comment by RieksJ** [comment]
I'm not very proficient in inspecting changes/results from PRs, but it seems that wrt this issue, the text is ok.

**Comment by msporny** [comment]
PRs #508 and #509 have been reviewed by multiple parties. Both PRs are expected to be merged (after merge conflicts are resolved. The next step is to see if the WG agrees with the changes.

**Comment by msporny** [comment]
PRs #508 and #509 are now merged. Waiting for approval from WG to close.

**Comment by stonematt** [comment]
Resolved on VCWG call 4/16/2019.
RESOLVED: Issue #481 is addressed by PR #508 and PR #509, which make multiple non-normative changes to the definitions of roles in the ecosystem as requested by the reviewer. The PR has been approved by multiple parties and have been merged. Issue #481 should be closed.

Plan to close in 7days
