### ISSUE TITLE
Introduction is misleading

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#482]
The introduction is misleading as this talks about signing .. "he addition of technologies, such as digital signatures, makes verifiable credentials more tamper-evident and more trustworthy than their physical counterparts." this specification does not implement signatures.

**Comment by brentzundel** [comment]
I believe this data model document does not specify which signatures must be used with verifiable credentials because the choice of signature type depends on the protocol within which verifiable credentials will be used.
Per the working group charter, this group may not specify protocol.
This does not mean that a place for signatures (the proof property) cannot be specified in the data model. The specification does not implement signatures, but it does specify where signatures may be used.

**Comment by nadalin** [comment]
it does unless you have a signature that actually works with the data model chosen, a solution exists for JWT as there are JWS/E/K specifications.

**Comment by brentzundel** [comment]
Is it your contention that unless a signature scheme is part of a published specification, that it cannot be considered as a means of verifying a credential?

**Comment by nadalin** [comment]
I'm not set on a signature as a proof mechanism so I would say unless there is a agreed upon proof mechanism, which there is not today, in the case of a JWT/CWT a JWS or JWE could be used as a proof.

**Comment by brentzundel** [comment]
I agree that in the case of JWT/CWT, a JWS or JWE could certainly be used as a proof. 
To my understanding, there is nothing in the data model that prohibits this.

**Comment by msporny** [comment]
> The introduction is misleading as this talks about signing

The editors are having a hard time translating this into a concrete specification text change. Could you please provide some concrete text change that would address the issue you raised so that the WG has something concrete to discuss?

**Comment by stonematt** [comment]
WG resolution: https://www.w3.org/2019/04/02-vcwg-minutes.html#resolution04
RESOLUTION: Add more clarifying text to the specification noting that while the specification does not standardize on signature format, the WG is aware of at least three mechanisms (JWTs, LD-Proofs, and ZKPs) that are capable of protecting the contents of the data model at the time of publication that are being used in deployments of the technology and expects those mechanisms to mature independently as well as new mechanisms to become standardized.

**Comment by msporny** [comment]
Clarifying text has been merged in PR #531 to address the issue raised by @nadalin. The resolution from the WG has been applied. More than 7 days has passed since the resolution passed. Closing the issue per the WG's approved CR issue processing procedure.
