### ISSUE TITLE
7.17 In-Private

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#492]
This is not a standard, each browser does this different and presents different properties to the user, so this miss-represents the privacy aspects, either clarify the fact that you have to check with the browser you are using or remove

**Comment by brentzundel** [comment]
Would it address your concern to add the following sentence to the private browsing section? 
>As each browser vendor handles private browsing differently, it is important for implementers to be aware of these differences and implement solutions accordingly.

**Comment by nadalin** [comment]
Some browsers don't even implement this feature, I can't suggest wording as I'm not part of the WG but if you propose a slight change I would agree

**Comment by brentzundel** [comment]
I have proposed a change in PR #510 
please let me know if these changes address your concerns.

**Comment by stonematt** [comment]
WG resolution: https://www.w3.org/2019/04/02-vcwg-minutes.html#resolution01
RESOLUTION: Merge non-normative PR #510 in order to clarify private-browsing mode concerns raised in issue #492.

**Comment by msporny** [comment]
PR #510 has been merged.
