### ISSUE TITLE
8. Security Considerations

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#493]
There are "musts" in this section yet it is marked non-normative, how can you have a security section that is non-normative with musts to implementers ? Suggest that this section be  rewritten into normative and non-normative sections since this is a very important section

**Comment by brentzundel** [comment]
@nadalin Please let me know if PR #505 addresses this issue to your satisfaction, or if there are more changes you feel are needed.

**Comment by brentzundel** [comment]
It looks like @chaals beat me to the punch. 
PR #499 addresses the same language as #505, so I have closed #505.

**Comment by stonematt** [comment]
WG Resolution: https://www.w3.org/2019/04/02-vcwg-minutes.html#resolution02
RESOLUTION: Merge non-normative PR #499 in order to clarify that existing 'must' was not a normative statement, which was raised in issue #493. Close issue #493 after the merge.
