### ISSUE TITLE
8.4 Token Binding

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#495]
Token Binding is now an IETF RFC 8471, the link and reference need to be updated

**Comment by nadalin** [comment]
This should also be a normative reference

**Comment by brentzundel** [comment]
@nadalin I have raised PR #506 to update the link to the rfc, thank you for pointing this out.

As far as making this a normative statement, unfortunately our charter limits this group to producing a data model. If this section were normative, it would specify aspects of protocol that we are currently limited to only providing guidance about.

**Comment by brentzundel** [comment]
See #497

**Comment by stonematt** [comment]
WG resolution: https://www.w3.org/2019/04/02-vcwg-minutes.html#resolution03
RESOLUTION: Merge non-normative PR #497 in order to update to an informative reference to RFC8471 raised in issue #495. Close issue #495 once the PR is merged.
