### ISSUE TITLE
Proof of Age insufficient for some regulatory requirements

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#5]
Note that even if one may desire to remain anonymous when purchasing alcohol, a photo ID may still be required to provide appropriate assurance to the merchant. The merchant may not need to know your name or other details (other than that you are over a certain age), but in many cases a mere proof of age may still be insufficient to meet regulations. We need to mention language in the specification calling this out specifically.

**Comment by ottonomy** [comment]
I always considered this use case to be somewhat abstract. Of course a `"isOverAge": 21` is not yet compatible with regulations that say "Only a DMV, military or government photo ID is accepted as proof of age". Those regulations weren't developed until after the technology to print photo IDs was widely deployed. It seems like the default would be to assume the same thing would happen with proof of age credentials, that they would only be accepted by governments after they are widely deployed for use in less regulation-impacted commercial transactions, like offers/coupons/loyalty programs.

To my eye, no addition is necessary to support this request, but modifying the use cases to call it out wouldn't detract from the document, so I'm neutral as to whether to make a change.

**Comment by msporny** [comment]
We have text in the spec now that addresses this issue: https://github.com/w3c/vc-data-model/blob/700263aca114f2d06a64762d2502e39686d409e5/index.html#L1669
