### ISSUE TITLE
Add Accessibility Use Case for under 3.3 Healthcare

### ISSUE THREAD

**Issue by Ryladog** [w3c/vc-data-model#50]
This could be better worded, but I rushed to put this together when I noticed the notice to publish FPWD. I could also come up with one for Education.

H.5 Proving Legal Disability Status
 
Trina, who is legally blind is currently unemployed and needs to use the local free disability ride service to get to the employment office. To use this service she is required to verify that she, in fact, maintains legal disability status. Trina provides her government-issued disability credential to sign up for the ride service, and in doing so it is not necessary for her to disclose her specific disability to the ride service as it could put her at personal risk.

**Comment by msporny** [comment]
@Ryladog I think you're looking for this repo: https://github.com/w3c/vc-use-cases

Please re-raise the issue there. I think the group already cleared an FPWD publication for next Tuesday, so FPWD will go out w/o this use case, but we'll quickly implement the auto-publishing workflow so your use case above will quickly make it into that spec after FPWD.

**Comment by David-Chadwick** [comment]
This issue is not about the data model document so can be closed in my opinion

**Comment by msporny** [comment]
I'll close as soon as @jandrieu either 1) creates an issue in vc-use-cases w/ the text above, or 2) creates a PR for vc-use-cases that includes this Accessibility use case.

**Comment by msporny** [comment]
ping @jandrieu @stonematt ... trying to close this issue, please add the use case @Ryladog mentioned above to the VC Use Cases document.

**Comment by TzviyaSiegman** [comment]
We could tie this into the Education use cases by making it about proving disability to get accessible textbooks.

**Comment by jandrieu** [comment]
Moved to Use Cases https://github.com/w3c/vc-use-cases/issues/74
