### ISSUE TITLE
Can JWT represent a verifiable credential with multiple subjects

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#511]
The text in 6.3.1 about JWT encoding states

sub MUST represent the id property contained in the verifiable credential subject. 

However, a VC can be about multiple subjects e.g. a marriage certificate. 

RFC 7519 states

 The "sub" (subject) claim identifies the principal that is the
   subject of the JWT.  The claims in a JWT are normally statements
   about the subject.  The subject value MUST either be scoped to be
   locally unique in the context of the issuer or be globally unique.
   The processing of this claim is generally application specific.  The
   "sub" value is a case-sensitive string containing a StringOrURI
   value.  Use of this claim is OPTIONAL.

We need to either:
a) decide how multiple subjects can be represented in JWT, or 
b) state that any one of the subjects of the VC may appear in the JWT "sub" property

**Comment by nadalin** [comment]
I would take a look at https://datatracker.ietf.org/doc/draft-yusef-oauth-nested-jwt/ which we discussed today at the WG meeting

**Comment by David-Chadwick** [comment]
this IETF draft does not appear to be solving the same problem. It is for nesting one credential inside another one. In this case the subjects would not be peers. In our case the subjects are peers and the ordering of the elements in the set of credentialSubjects is not significant.

**Comment by nadalin** [comment]
There is nothing to say nested JWT are not peers

**Comment by nadalin** [comment]
You can also just create and register a new claim value that would allow multiple subjects

**Comment by brentzundel** [comment]
@David-Chadwick, with @nadalin's positive response about the possibility of representing multiple subjects in a JWT encoded VC, do you still feel this is an issue that needs to be resolved?

**Comment by David-Chadwick** [comment]
It is something that JWT should be able to solve in the future through nesting (the draft is currently very sparse so it will be a while before it is finalised). Its not a very efficient solution either as it will require multiple signatures, one per peer and one on the outer JWT.
Registering a new claim value is perhaps the better option, so maybe we should do that as part of our work

**Comment by awoie** [comment]
if you remove the `sub` attribute and use multiple `credentialSubjects`, it would work.

**Comment by awoie** [comment]
But I raised a separate issue because it is not clear to me how multiple subjects are represented in general.

**Comment by awoie** [comment]
I created a new issue #541 that addresses the first problem.

**Comment by msporny** [comment]
I suggest we add non-normative text to the spec that notes that currently JWTs can only support one subject and that implementers should check the JWT claim registry for multisubject claim types. We can also point to the spec that @nadalin mentions as an alternative.

**Comment by nadalin** [comment]
@msporny That's fine

**Comment by msporny** [comment]
> @msporny That's fine

Great... I'll create the PR and link to it once it's ready for review.

**Comment by stonematt** [comment]
From VCWG call on April 30, 2019: 
RESOLUTION: Issue #511 should be addressed by making a non-normative change to the specification noting that multiple subjects are not supported by JWTs and implementers should refer to the JWT registry for future multisubject properties or the yusef-nested-jwt specification. Issue #511 should be closed after the PR is merged.

**Comment by burnburn** [comment]
Approved by requester.  Closing.
