### ISSUE TITLE
Is Proof mandatory in Verifiable Presentation?

### ISSUE THREAD

**Issue by chaoxinhu** [w3c/vc-data-model#521]
Is the field Proof mandatory in Verifiable Presentation?

IMHO, the purpose of Proof is to store someone's identity such that the object (VC, VR) is actually signed by that one. In the case of VC it is easy to understand, because the Verifiable Claim contains real user data info and it ought to be signed by someone. However, Verifiable Representation should be a combination of multiple VCs only, and each VC is self-verifiable itself. So we were wondering if there is some business meaning behind the Proof in Verifiable Presentation..?

Thanks in advance.

**Comment by msporny** [comment]
> So we were wondering if there is some business meaning behind the Proof in Verifiable Presentation..?

Yes, the signature on the Verifiable Presentation is expected to be from the Holder of the Verifiable Credentials. The signature on a Verifiable Credential is expected to be from the Issuer of the Verifiable Credential.

So, the signature on the Verifiable Credential proves that it was issued by a particular issuer. The signature on the Verifiable Presentation proves that the Holder chose to put those Verifiable Credentials together into a presentation and provide it to the Verifier.

Does that answer your question?

**Comment by chaoxinhu** [comment]
Thanks @msporny - crystal clear. Closing.
