### ISSUE TITLE
Section 4 normative and non-normative parts 

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#523]
I'm having some issues relative to normative and non-normative sections

4.1 Conetxt is normative and says it used for 4.7 and 4.10 and 4.7 and 4.10 don't provide any specified mechanisms for interop, thus these are at RISK and if no interop is shown on a defined mechanism then these would have to be non-normative and thus I don't see how 4.1 could me made a MUST and normative 

4.7 see above

4.9 Status is normative but there is no specified mechanism for interop so I don't see how this can be normative

4.10 See above (4.1)

**Comment by msporny** [comment]
You seem to think the group is attempting to achieve interop on ALL proof mechanisms. It is not. The group is attempting to get interop at the data model layer as expressed in the syntaxes. It is also true that we can get interop for JWTs (as those statements are normative).

**Comment by nadalin** [comment]
@msporny for things define mechanisms  to be normative theybneed to be defined, either in this special or another one so there are a lot of undefined mechanisms here that are missing specifications

**Comment by stonematt** [comment]
Resolved on VCWG call 4/16/2019.
RESOLVED: One of the goals of the Verifiable Credentials Data Model specification is to define extensibility points in the data model and achieve interoperability on the extensibility points (not the extensions themselves). The interoperability tests will focus on ensuring that the minimum information exists in extensions to identify the extension without needing to define each extension in detail for this iteration of the Working Group. Defining extensions to
... the base data model is outside of the scope of the WG's charter. All features that the Working Group deems at risk were marked before entering CR. No new at-risk features have been identified after processing issue #523, which should be closed with no changes to the specification.

Plan to close in 7 days

**Comment by nadalin** [comment]
@stonematt This issue (as I don't think it was handled correctly) will come back up if/when transition to Recommendation happens
