### ISSUE TITLE
Change W3C TR link to vc-data-model

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#526]
Our current TR link is https://www.w3.org/TR/verifiable-claims-data-model/ ... which doesn't match the title of the specification anymore. Suggest that we ask sysreq to change it to https://www.w3.org/TR/vc-data-model/ and redirect all old references to the new TR link.

**Comment by ashimura** [comment]
I talked within the W3C Team about this request and got approval to change the shortname to "vc-data-model". So I'm now working with the Webmaster for that change.

**Comment by burnburn** [comment]
Thanks Kaz!

**Comment by msporny** [comment]
> I talked within the W3C Team about this request and got approval to change the shortname to "vc-data-model".

Wonderful, thank you @ashimura!

**Comment by ashimura** [comment]
I talked with the Webmaster and what we can do is:
* publish the next draft as a Proposed Recommendation with the new shortname, "vc-data-model".
* add a redirection from:
    https://www.w3.org/TR/verifiable-claims-data-model/
  to:
    https://www.w3.org/TR/vc-data-model/
  which will return the latest version of the document.
* However, the dated URLs will remain untouched and won't redirect.

**Comment by TallTed** [comment]
As this progresses, we should ensure that [all existing references](https://github.com/w3c/vc-data-model/search?q=verifiable-claims-data-model&unscoped_q=verifiable-claims-data-model) (except perhaps any that are cast-in-stone moment-in-time captures) get updated.

**Comment by burnburn** [comment]
@TallTed agreed that a number of items need to be updated, such as the vocabulary/ies.  Would you care to create a PR?

**Comment by msporny** [comment]
The PR is in, just need W3C Sysreq to update when we publish next time.

**Comment by burnburn** [comment]
WG resolution on 28 May 2019 call:

RESOLUTION: Issue #526 is resolved via PR #645, which updates the TR links in the specification. Close issue #526 after the transition to Proposed Recommendation has occurred.

**Comment by burnburn** [comment]
It appears the Sysreq update has already been done.  However, the pointer to the CR doc in the spec is now incorrect.

**Comment by burnburn** [comment]
This has been completed with the publication of the second CR. Closing.
