### ISSUE TITLE
Consolidate all Verifiable Credential Registries to a single registry

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#530]
We have a Verifiable Credential Status Registry, and will most likely have other registries. We should just consolidate all of the registries into a single document that lists all the extensibility points that we know of in the spec. So the combined registry would contain all status schemes, terms of use schemes, proof mechanisms, evidence schemes, etc.

**Comment by stonematt** [comment]
From VCWG call on April 30, 2019: 
RESOLUTION: Issue #530 should be addressed by creating a Verifiable Credentials Extension Registry in the W3C Credentials Community Group and requesting that the registry is adopted as an official W3C CCG Work Item. Issue #530 should be closed after the W3C CCG accepts the registry as a Work Item.

**Comment by msporny** [comment]
PR https://github.com/w3c-ccg/vc-extension-registry/pull/2 and PR #591 are in. This issue should be closed as soon as those PRs are merged.

**Comment by msporny** [comment]
> This issue should be closed as soon as those PRs are merged.

PRs have been merged, the registry exists, closing issue.
