### ISSUE TITLE
Add informative references to LD Proofs, LD Signatures, detached JWS, and RsaSignature2018

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#543]
Add references in section 3.4 and 4.7 (and anywhere else a full proof is defined and understanding it is vital to understanding the section).

/cc @jricher

**Comment by stonematt** [comment]
From VCWG call on April 30, 2019: 
RESOLUTION: Issue #543 should be addressed by providing informative references to detached JWS, LD-Proofs, LD-Signatures, and the RsaSignature2018 signature suite in sections 3.4, 3.7, and any other section where it is appropriate. Issue #543 should be closed after the PR is merged.

**Comment by msporny** [comment]
PR https://github.com/w3c/vc-data-model/pull/593 addresses this issue. The issue should be closed once the PR is merged.
