### ISSUE TITLE
Appendix examples not complete

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#551]
The examples in Appendix B (Subject-Holder Relationships) do not contain an @context property, which is mandatory. Furthermore. "https://www.w3.org/2018/credentials/examples/v1" does not contain aliases for all of the vocabulary used in Appendix B.

**Comment by David-Chadwick** [comment]
This has been fixed in PR #563

**Comment by burnburn** [comment]
Resolution on the VCWG 7 May 2019 call:
Issue #551 is addressed by PR #563 which makes non-normative changes to fix the missing @context values in a number of the examples in the appendix. Issue #551 should be closed.
