### ISSUE TITLE
unclear bit of text in "JWT Encoding" section

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-data-model#552]
see https://github.com/w3c/vc-data-model/blob/c74f5c98fe517e1196e5043ba8304798e77a4715/index.html#L3088

```
              <h5>JWT Encoding</h5>
            <p>
To encode a <a>verifiable credential</a> as a JWT, specific
<a>properties</a> introduced by this specification MUST be encoded as standard
JOSE header parameters, JWT registered <a>claim</a> names, or contained in the
JWS signature part. If no explicit rule is specified, <a>properties</a> are
encoded in the same way as with a standard <a>verifiable credential</a>, and are
added to the <code>vc</code> <a>property</a> of the JWT. As with all JWTs,
the JWS-based signature of a <a>verifiable credential</a> represented in the JWT syntax is
calculated against the literal JWT string value as presented across the wire, before any 
decoding or transformation rules are applied. The following paragraphs describe 
these encoding rules.
            </p>
```

I'm not sure I understand the three possibilities in the MUST. I think `encoded as standard JOSE header parameters, JWT registered` -> `encoded as standard JOSE header parameters, encoded as JWT registered` but if that's not what was meant, then some other word-smithing will be needed.

**Comment by msporny** [comment]
I believe your interpretation is correct, @TallTed. Can you please produce a PR that applies your suggested change?

@awoie, could you please ensure that both of us are not mis-interpreting the text you wrote?

**Comment by awoie** [comment]
If a specific processing rule for a specific property exists in this specification, the rule defines how to encode the property in a JWT using:
1. registered JWT claim names, e.g., `expirationDate` -> `exp`
2. registered JOSE header names, e.g., `proof` -> `alg` (+ JWS)
3. or use the JWS, e.g., `proof` -> JWS

If no processing rule exists, e.g., `refreshService`, then add the property to the `vc` property.

@TallTed does this answer your question?

**Comment by stonematt** [comment]
From VCWG call on April 30, 2019: 
RESOLUTION: Issue #552 should be addressed by making a non-normative clarification related to the various ways the data model can be encoded using a JWT. Issue #552 should be closed after the PR is merged.

**Comment by burnburn** [comment]
Approved by submitter and merged.  Closing.
