### ISSUE TITLE
problematic phrasing in 4.2 https://w3c.github.io/vc-data-model/#identifiers

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-data-model#556]
circa https://github.com/w3c/vc-data-model/blob/acec79f7944aa7ad3b6efe86d34855a24b646e15/index.html#L1103

I do not think this phrasing -- 

```
If present, identifiers that 
others are expected to use when expressing statements about a specific thing 
MUST be expressed using the <code>id</code> <a>property</a>.
```

-- expresses what was intended.  Flipping the word order around without changing what the sentence is saying --

```
If identifiers [that others are expected to use when expressing statements 
about a specific thing] are present, they MUST be expressed using the 
<code>id</code> <a>property</a>.
```

I think the intended statement is about `id` (not about "identifiers intended to be used by others") and ought to include something about cardinality.  Something more like: 

```
If the <code>id</code> <a>property</a> is present:
<ul>
  <li>the <code>id</code> <a>property</a> MUST express an 
      identifier that others are expected to use when expressing 
      statements about specific thing identified by that 
      identifier</li>
  <li>the <code>id</code> <a>property</a> MUST NOT have more 
      than one value</li>
  <li>the value of the <code>id</code> <a>property</a> MUST 
      be a URI</li>
</ul>
```

**Comment by msporny** [comment]
@TallTed agreed that the changes you are suggesting are non-substantive and more accurate. Can you please put them in a PR so we can merge/close this issue?

**Comment by stonematt** [comment]
From VCWG call on April 30, 2019: 
RESOLUTION: Issue #556 should be addressed by applying the non-substantive changes requested by the issuer submitter. Issue #556 should be closed after the PR is merged.

**Comment by TallTed** [comment]
@stonematt @msporny - PR has been merged; should be `Pending 7 Day Close`
