### ISSUE TITLE
@Context

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#557]
"The value of the @context property MUST be an ordered set where the first item is a URI with the value https://www.w3.org/2018/credentials/v1."

I don't believe that this has to be a ordered set, the specification should allowed this to be treated as just a string if this value has to be present, which I still have concerns about

**Comment by David-Chadwick** [comment]
This issue has already been raised by me in PR #548. So I suggest that when it is answered there, this issue can be closed.

**Comment by nadalin** [comment]
@David-Chadwick Agree

**Comment by msporny** [comment]
> I don't believe that this has to be a ordered set, the specification should allowed this to be treated as just a string if this value has to be present, which I still have concerns about

It has to be an ordered set. If it is not, JSON implementations would be forced to use a JSON-LD processor, which is not what you want.

**Comment by msporny** [comment]
> This issue has already been raised by me in PR #548. So I suggest that when it is answered there, this issue can be closed.

PR #548 was merged with PR #546, which was approved by the WG and merged into the specification, thus addressing this issue.

**Comment by stonematt** [comment]
From VCWG call on April 30, 2019: 
RESOLUTION: Issue #557 is addressed by PR #546 which made non-substantive changes to explain why @context is an ordered set. PR #546 has been merged and issue #557 should be closed.
