### ISSUE TITLE
Ideas for roles to add to the data model for next draft

### ISSUE THREAD

**Issue by rvarn** [w3c/vc-data-model#57]
Some of these terms are already defined and this is just my way of expressing them in single framework to layout some other roles and dependencies/relationships. 

•	An **Issuer** issues claims about Subjects using Identifiers
•	**Subject** is the party about whom the claim is made and can be a:
     o Person
     o Thing
     o	Entity
     o	Artificial Intelligence
     o Other?
•	An **Asserter** of a claim is the party submitting the claim to an Inspector and can be:
     o	Subject
     o Holder
     o	Broker
     o	Agent
•	**Seekers** are parties looking for specific claims or claim elements who have not yet been authorized by the Subject of a claim to receive the claim
•	Broker is a party that facilitates connections and exchange between Subjects and Seekers in regard to a claim
•	**Agent** is a party acting on behalf of a Subject
•	**Inspector** accepts claims or claim elements from Asserters
•	**Verifier** is a party that determines the elements of a claim necessary for validity are present and current and that its contents and status are consistent and fedelitous with the issuer’s terms and purpose 
•	**Accessors** are those with permission to examine some or all of the contents of a claim
•	**Claimvelope** is the encapsulation of the contents of claim and securing said contents from unauthorized access, use, or modification
•	**Claimvelope** Label contains the data necessary to facilitate transmission and verification of a claim and to gain or request access to some or all of the contents.
•	**Published Claims** are claims made public by the subject of a claim in which the claim and subject are revealed and such a revelation is allowed by the terms of issuance
•	**Discoverable Claims** are non-public claims that can be queried, if allowed, to determine if it contains attributes of interest to a Seeker
•	**Identifiers** are methods of associating a Subject with a claim and can be:
     o	Anonymous 
     o	Pseudo-nonymous 
     o	Veri-nonymous

**Comment by David-Chadwick** [comment]
Hi Richard
Would you like to comment on the current state of this issue, given that things have moved on somewhat since you raised it in July 2017. Can it be closed or are there outstanding pieces of text that you would like to be added to the latest version of the Data Model.
regards
David

**Comment by burnburn** [comment]
@rvarn please give us a status.

**Comment by burnburn** [comment]
Direct message sent, no reply.  Put on permanent hold.

**Comment by RieksJ** [comment]
I would say that since this is a standard, we should only define terms (or roles) if it is relevant for understanding and/or working with the standard. That relevance should then also be documented.

**Comment by kdenhartog** [comment]
We discussed this on the maintenance call and believe that the comment from @RieksJ is adequate. If the author believes this should still be addressed it would be handled in V2 and they could reopen the issue to manage it then.
