### ISSUE TITLE
JSON schema reference

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#589]
The reference to JSON schema is way out of date. The Internet Draft expired in 2013. We should instead point to 
https://json-schema.org/
which is the home of JSON schema and provides up to date information

**Comment by msporny** [comment]
Looks like this is the latest for JSON Schema at IETF: https://tools.ietf.org/html/draft-handrews-json-schema

W3C Process frowns upon pointing to websites that might disappear when there is an appropriate standards organization document that we could point to instead.

**Comment by David-Chadwick** [comment]
There is a problem pointing to IETF drafts in that they expire in 6 months time. So any reference to them is bound to be soon out of date, which is not good for a Recommendation that will last for years. Referencing an RFC is different since these typically last for years.
So I would prefer us not to reference an IETF draft. I think https://json-schema.org/ is going to have a reasonably long life (it has so far)

**Comment by msporny** [comment]
We should point to the IETF page and submit a PR that does that.

**Comment by msporny** [comment]
PR is in #647. Suggest close after that is merged.

**Comment by David-Chadwick** [comment]
Agreed

**Comment by burnburn** [comment]
WG resolution on 28 May 2019 call:

RESOLUTION: Issue #589 is addressed via PR #647 which updates the non-normative reference to JSON Schema to a more stable IETF URL. Issue #589 should be closed after the PR is merged.

**Comment by burnburn** [comment]
PR merged long ago, submitter agreed.  Closing.
