### ISSUE TITLE
Recommend adding `holder` to non-ZKP VPs in implementation guide

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-data-model#596]
In order to support a separation of concerns within software architecture, we should recommend that non-ZKP style VPs (Verifiable Presentations) include a `holder` property. This allows for one software process to verify the proofs on a VP (including ensuring that the keys used were in control of the holder) and a secondary process to easily find the `holder` identifier, knowing that the first process ensured that it was valid. There may also be multiple proofs on a VP where calling out the intended `holder` can be a useful differentiator.

We could also add something non-normative to the spec to say we didn't have anything normative to say about `holder` in a VP in this version, but readers should see the implementation guide -- where I do think we should recommend its usage to make writing software that follows this pattern easier.

**Comment by David-Chadwick** [comment]
I strongly support the addition of holder to VPs, and was strongly against it being removed in the first place. I suggest we add it now as an optional parameter that MAY exist in a VP, and then the CR will not need to be re-issued

**Comment by msporny** [comment]
Reserve holder in a non-normative way in the main spec. Add something to best practices that notes it's expected usage.

**Comment by msporny** [comment]
Potentially merge this into a larger non-normative PR that reserves certain keywords including "validFrom", "validUntil", "DisputeCredential", and "holder".

**Comment by msporny** [comment]
The PR for adding `holder` in a non-normative way is in PR #648. Reserving `validFrom` and `validUntil` is in PR #646. Suggest closing after both are merged.

**Comment by burnburn** [comment]
WG resolution on 28 May 2019 call: 

RESOLUTION: Issue #596 is addressed via PR #648, which adds non-normative text describing the holder property. Issue #596 should be closed after the PR is merged.

**Comment by burnburn** [comment]
PR merged a month ago.  Closing.
