### ISSUE TITLE
What would a counter-signed RWoT claim look like?

### ISSUE THREAD

**Issue by kimdhamilton** [w3c/vc-data-model#60]
_From @ChristopherA on July 14, 2017 22:43_

Using my DID (the latest value from Shannon's code), and signing a verifiable claim (created from the verifiable claims playground and signed with my correct testnet private key I used to create the DID transaction) I get:

```
{
  "@context": [
    "https://schema.org/",
    "https://w3id.org/security/v1"
  ],
  "claim": {
    "id": "did:btcr:xyv2-xzyq-qqm5-tyke",
    "alternate-name": "ChristopherA",
    "knows": {
      "id": "did:btcr:rzqq-qqqq-uvlj-ez",
      "alternate-name": "Alice"
    }
  },
  "signature": {
    "type": "EcdsaKoblitzSignature2016",
    "created": "2017-07-14T22:38:36Z",
    "creator": "ecdsa-koblitz-pubkey:02b97c30de767f084ce3080168ee293053ba33b235d7116a3263d29f1450936b71",
    "signatureValue": "IGbDlNVSLIk7//rnuEEw7vtRKQ1HFLb+/K0cFHZ80zcVbFkF6vQj+jtDANc0MD9o0nhL5ykGFTd1VoP7a7B2iqM="
  }
}
```

This should be (hopefully and eventually) inspectable, validatable, verifiable and confirmable.

However, under the BTCR method, we are extremely self-sovereign centric, so this claim is not considered to be valid until it is countersigned by Alice.

@dlongley What would that extra countersignature look like?

_Copied from original issue: WebOfTrustInfo/btcr-hackathon#45_

**Comment by kimdhamilton** [comment]
I think the signatures accumulate in a single array at the end, like this. But @dlongley would know better.

https://github.com/WebOfTrustInfo/btcr-did-tools-js/blob/master/claims/kimh-countersigned.jsonld

**Comment by msporny** [comment]
@kimdhamilton @ChristopherA Multisig for LDS is defined here: https://w3c-dvcg.github.io/ld-signatures/#multiple-signatures

There are two options... set signatures and chained signatures. If the order of signatures matters, you should use chained signatures. Note that we have set signatures implemented, but chained signatures are not implemented and we should discuss some of the concerns before going that route.

In any case, hopefully the spec link above helps shed some light on the options available.

**Comment by burnburn** [comment]
@kimdhamilton please take a look at this.  May be blocked same as #32.

**Comment by kimdhamilton** [comment]
I think this one is ok to close. Signature sets or chains should suffice for the original example (depending on whether signature order is important)

**Comment by msporny** [comment]
> I think this one is ok to close.

We now have signature sets (renamed to proof sets) implemented in the JSON-LD Signatures reference implementation... Veres One uses them. Implementing signature chains would be trivial, but it's not implemented yet.
