### ISSUE TITLE
Example VerifiablePresentation types need updating

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c/vc-data-model#600]
Since CR1 requires VerifiablePresentation type's to be `VerifiablePresentation` plus another specific type, the examples need to be updated to reflect that.

**Comment by dmitrizagidulin** [comment]
Fixed in PR https://github.com/w3c/vc-data-model/pull/601 (though it looks like I need to resolve a conflict?)

**Comment by burnburn** [comment]
WG resolution on 28 May 2019 call: 

RESOLUTION: Issue #600 is addressed via PR #601, which makes non-normative changes to the examples. Close issue #600 after the PR has been merged.
