### ISSUE TITLE
Non-normative sections contain musts

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#602]
Section 3.1 is non-normative buts contains musts, would be good to reword these and not use must even though it's lower case

**Comment by nadalin** [comment]
Maybe better to use "should" and not "must" in non-normative sections

**Comment by TallTed** [comment]
If we must (I mean, need to) avoid some [RFC2119](https://tools.ietf.org/html/rfc2119) (i.e., `must`) words regardless of capitalization, we should (I mean, ought to) avoid them all (including `should`), and fall back to [RFC6919](https://tools.ietf.org/html/rfc6919) or other thesaurus fruit.

That said, I note that [RFC8174](https://tools.ietf.org/html/rfc8174) states explicitly "that only UPPERCASE usage of the key words have the defined special meanings", and wonder whether we could simply cite this in the preamble of the document...

**Comment by nadalin** [comment]
@TallTed It's very hard to tell what are really the "MUSTS" and what are really "musts" in this document. So it would be acceptable to just reiterate RFC8172

**Comment by msporny** [comment]
Make the following change "To be able to trust claims, more information must be added." change to "To be able to trust claims, more information is expected to be added to the graph."

**Comment by msporny** [comment]
PR #649 addresses this issue by removing the non-normative 'must'. ReSpec has also been updated to refer to RFC8172 to make it even more clear that lowercase must/should/may are not normative statements.

**Comment by burnburn** [comment]
WG resolution on 28 May 2019 call:

RESOLUTION: Issue #602 is addressed via PR #649, which removes the non-normative "must" in favor of "is expected to". Issue #602 should be closed once the PR is merged.

**Comment by burnburn** [comment]
This issue will be closed 7 days from 28 May (when sufficient approving reviews were received) unless new information is added.
