### ISSUE TITLE
Patent Policy 

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#603]
"This document was produced by a group operating under the W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy."

I would hope the last "must" in the last sentence is really a "MUST"

**Comment by msporny** [comment]
This text is produced by ReSpec, which is a toolchain used to produce many W3C specifications (including the one for the group that you Co-Chair, WebAuthn). I will note that this text is exactly the same as in the WebAuthn specification in the same section:

https://www.w3.org/TR/webauthn/#status

The text you mention above is the same text that W3C uses across all W3C specifications. As such, the WG is not in a position to change the text from lowercase must to uppercase MUST. This change is out of scope for the WG and requires buy in from W3M. I suggest an issue is raised w/ W3M.

**Comment by nadalin** [comment]
@msporny You should bring this up to the W3C and not ignore as it will come back up when going to Recomendation. If you have a note from W3C that's says it can't be changed then place it in the issue please

**Comment by TallTed** [comment]
@nadalin - As a WG Co-Chair, you are in an arguably better position to raise this concern with W3 Management. As this concern is more yours than ours at this point, I encourage you to do so. Given your comments here, I am frankly shocked you allowed this text to persist in the document(s) your own WG has published as TR!

**Comment by burnburn** [comment]
> If you have a note from W3C that's says it can't be changed then place it in the issue please

Tony, as pointed out above this boilerplate is that generally approved by W3C.  No issue will be placed in the text.  As WG Co-chair, I am closing this issue.
