### ISSUE TITLE
Example URI

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#605]
"This document uses the examples context URI (https://www.w3.org/2018/credentials/examples/v1) for the purposes of demonstrating examples. The examples context URI must not be used for any other purpose, such as in pilot or production systems"

Is the "must" here normative? if so this should be a MUST, if not change to a should

**Comment by msporny** [comment]
It's not testable, thus is non-normative. We should change it to "Implementations are expected to not use the URI for any other purpose, such as in pilot or production systems."

**Comment by nadalin** [comment]
That is a fin solution

**Comment by msporny** [comment]
Great, we'll apply that change to the spec.

**Comment by msporny** [comment]
The change is in PR #650. Close this issue after that's merged.

**Comment by burnburn** [comment]
WG resolution on 28 May 2019 call: 

RESOLUTION: Issue #605 is addressed via PR #650, which makes a non-normative change to the spec regarding changing a lowercase "must not" to a "is expected to not". Issue #605 should be closed after the PR is merged.

**Comment by burnburn** [comment]
This issue will be closed 7 days from 28 May (when sufficient approving reviews were received) unless new information is added.

**Comment by burnburn** [comment]
Closing.
