### ISSUE TITLE
Section 4.2

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#606]
This does not say if "identifiers" are mandatory or optional, it sort of hints at a privacy concern but does not state explicitly if this is mandatory or optional

**Comment by msporny** [comment]
The specification states: "The id property MAY be present." -- it's optional. The privacy concern around identifiers is in Section 7.3: Identifier-based Correlation: https://w3c.github.io/vc-data-model/#identifier-based-correlation.

**Comment by nadalin** [comment]
@msporny As I said this is not clear in the present wording thus I opened a issue, not seeing a fix here

**Comment by msporny** [comment]
The group discussed this today and noted that we should link to "Section 7.3: Identifier-based Correlation". In addition, @brentzundel has made the optional nature of this more clear in the specification: https://github.com/w3c/vc-data-model/pull/616 . 

The group is going to close once the PR adding the link is merged.

**Comment by TallTed** [comment]
Also see #628

**Comment by msporny** [comment]
PR #651 has added a reference to "Section 7.3: Identifier-based Correlation". That was the last PR that was needed, close after all of them have been merged.

**Comment by burnburn** [comment]
WG resolution on 28 May 2019 call:

RESOLUTION: Issue #606 is addressed via PRs #616, #628, and #651 by making non-normative clarifications to the specification. Issue #606 should be closed after all associated PRs have been merged.

**Comment by nadalin** [comment]
Looks good

**Comment by burnburn** [comment]
All PRs merged.  Closing.
