### ISSUE TITLE
Conformance

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#609]
" At the time of publication, Working Group members had implemented verifiable credentials using at least three proof mechanisms: JSON Web Tokens [JWT], Linked Data Signatures [LD-SIGNATURES], and Camenisch-Lysyanskaya Zero-Knowledge Proofs [CL-SIGNATURES]"

Please note that JWT is not a proof mechanism since JWTs don't have to be signed, the pointer should be to JWS for a proof mechanism

**Comment by msporny** [comment]
Ok, will update to JWS.

**Comment by nadalin** [comment]
@msporny Will wait to see PR

**Comment by msporny** [comment]
PR #652 is in, please review, @nadalin. We will close the issue once you review.

**Comment by burnburn** [comment]
WG resolution on 28 May 2019 call:

RESOLUTION: Issue #609 is addressed via PR #652, which makes a non-normative clarification to the specification regarding JWS. Issue #609 should be closed after the 7 day review period and after the PR is merged.

**Comment by nadalin** [comment]
@msporny See my comments in #652 as they apply here

**Comment by burnburn** [comment]
Your comment was about interoperability, which is already tracked via issue #632.  Closing.
