### ISSUE TITLE
decentralized identifier document

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#610]
This term is defined but not used, this should be removed if not used

**Comment by TallTed** [comment]
It would be helpful if you would include links to the specific areas you're flagging. In this case, I *think* you mean [lines 33-38 of terms.html](https://github.com/w3c/vc-data-model/blob/55fc3b740153ab2bc389e5983c62074a3dd3b71c/terms.html#L33). Is that correct?

**Comment by nadalin** [comment]
@TallTed Have no idea as the HTML version I'm looking at has no line numbers

**Comment by TallTed** [comment]
@nadalin - OK... Are you looking at [2. Terminology](https://w3c.github.io/vc-data-model/#terminology) and more specifically at [decentralized identifier document](https://w3c.github.io/vc-data-model/#dfn-decentralized-identifier-documents) therein?

**Comment by TallTed** [comment]
The spec uses the term "DID document", which is an alias of the expanded "decentralized identifier document", in --
> For example, the <code>kid</code> can refer to a key in a
<a>DID document</a>, or can be the identifier of a key inside a JWKS.

I've tweaked the definition.  Does my change suffice?

**Comment by burnburn** [comment]
Text changes have been merged.  Marking with 7 Day close.

**Comment by nadalin** [comment]
@burnburn Since there is no normative reference to a DID specification, is the notion of a DID abstract in this specification?

**Comment by burnburn** [comment]
@nadalin I don't understand what you mean by 'DID abstract'.  Are you asking whether we can include an informative reference to the early work at https://w3c-ccg.github.io/did-spec/ to help explain what a DID is?

**Comment by nadalin** [comment]
@burnburn There are many DID specifications out there, none have been standardized so thus I ask the question is the term DID used in a generic context that would apply to all these different DID specifications ?

**Comment by brentzundel** [comment]
> @burnburn There are many DID specifications out there, none have been standardized so thus I ask the question is the term DID used in a generic context that would apply to all these different DID specifications ?

Yes
