### ISSUE TITLE
 Expiration

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#613]
Is "expiration" mandatory or optional, as it's not explicitly stated ? Suggest that this be worded in way that conformance test can be generated and developers know what parameters are required and which ones are optional

**Comment by TallTed** [comment]
Optional. Some credentials are never meant to expire. Adjusting the text...

**Comment by nadalin** [comment]
+1

**Comment by msporny** [comment]
We should be clear that this is a non-normative change as it clarifies what the group had intended... that this was always an optional property.

**Comment by nadalin** [comment]
@msporny Its not clear, and the reader has no way to know what the group had intended so a clearification is required

**Comment by burnburn** [comment]
> @msporny Its not clear, and the reader has no way to know what the group had intended so a clearification is required

Manu's point is that this is not a change in behavior (which would be normative).  It is instead a clarification of the text by the group to explain something always intended to work this way.  Thus it is a non-normative change.  Marking with a 7 Day close that began when #615 was merged.

**Comment by burnburn** [comment]
WG resolution on 28 May 2019 call:

RESOLUTION: Issue #613 is addressed via PR #615, which makes non-normative changes to expiration to clarify its usage. Issue #613 should be closed immediately.
