### ISSUE TITLE
"Inspector-Verifier" terminology is confusing

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#64]
I'm concerned about the recent decision to pick "inspector-verifier" as a glossary term for the following reasons:

* From a communication and marketing standpoint, it's awkward to say and use alongside the other terminology (issuer, holder, etc.). Having used the term to talk about the ecosystem, it sounds out of place when said out loud on a stage or when talking with customers.
* It makes it seem like there are two roles instead of one.
* It sounds like the Chairs mis-read the IRV poll results, which showed Verifier as the clearly preferred choice.

I suggest we select "Verifier" as the winner because:

* That is aligned with the results of the poll.
* It doesn't lead to confusion over number of roles.
* Its easy for readers/listeners to understand the concept based on the word.

**Comment by stonematt** [comment]
you missed the group discussion following the vote.  even though verifier gained the most votes in the run off, the interim process showed more polarization than the other 2 roles did.  we were all a bit surprised by the nuance of the results.  The concern was that "Verifier" was overburdened and not necessarily intuitive in this context.  The hyphenated term is meant to be uncomfortable, so we continue the discussion. Identify appropriate supporting roles in the eco system and ultimately settle on a term that fits better.  Simultaneously, we didn't want to block progress on FPWD.

I'm not comfortable w/ simply selecting "Verifier" at this point.

**Comment by msporny** [comment]
> the interim process showed more polarization than the other 2 roles did

What do you mean by "the interim process"?

**Comment by msporny** [comment]
> The hyphenated term is meant to be uncomfortable, so we continue the discussion. 

The hyphenated term has led to a fair number of people confused about the hyphenated term. It is now causing more damage. The group needs to make a decision. Multiple organizations are now using "verifier" in their product literature. 

Another data point is that the voting process we were using is designed to select the item that has the most consensus, even if its close. Reading "nuance" into the voting outcome is problematic because the voting mechanism we used takes that nuance into account and picks a winner not based on polarized choices, but based on whether or not the electing body can live with the result. So the two top choices were things where the voting body could live with either one, but the term "verifier" came out on top because there was a slight preference for that over "inspector".

I suggest we go with verifier because 1) that's what companies are starting to use in their marketing literature, and 2) it was the top pick for the poll.

**Comment by stonematt** [comment]
I support this.

**Comment by ChristopherA** [comment]
+1
