### ISSUE TITLE
The confusing nature of type and presentation

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-data-model#653]
The text in the spec is unclear about whether it is required for presentations and encapsulated objects to have multiple types. My understanding is that the type field for a verifiable credential MUST have more than one type, but that presentations, encapsulated objects, etc. do not have this requirement.
I recommend text be added to clarify that while `type` is required for presentations and encapsulated objects, it is not required for those objects to have multiple types. Examples in the spec should also be changed to reflect this.

Related to issue #600

**Comment by burnburn** [comment]
From the VCWG call on 11 June 2019:

RESOLUTION: Merge PR #658 as it reflects the consensus of the Working Group. Specifically, more organizations would object to more stringent type requirements than what exists in PR 658.
[10:37] manu: I'll merge that as soon as Brent makes the minor change
[10:38] burn: that resolution only applies after a change has been made.

**Comment by msporny** [comment]
The minor change was made in https://github.com/w3c/vc-data-model/pull/658/commits/12681f9a24bb7669e0f23268b16ef4d318b172c2 and was merged into the specification 9 days ago. Please close.
