### ISSUE TITLE
"@context" missing in verifiable credentials embedded in verifiable presentation examples

### ISSUE THREAD

**Issue by ken-ebert** [w3c/vc-data-model#654]
"@context" should be present within verifiable credentials embedded within verifiable presentations. We have four example verifiable presentations and the base context in the specification:

Section 3.4, example 2:
>"verifiableCredential": [{
>    "id": "http://example.edu/credentials/1872",

should become

>"verifiableCredential": [{
>   "@context": [
>      "https://www.w3.org/2018/credentials/v1",
>      "https://www.w3.org/2018/credentials/examples/v1"
>    ],
>    "id": "http://example.edu/credentials/1872",

and the proof section of the embedded verifiable credential could be updated and the proof section of the verifiable presentation could be updated to reflect the new content.

Section 5.6, example 20:
>  "verifiableCredential": [{
>    "id": "http://example.edu/credentials/3732",

should become

>  "verifiableCredential": [{
>    "@context": [
>      "https://www.w3.org/2018/credentials/v1",
>      "https://www.w3.org/2018/credentials/examples/v1"
>    ],
>    "id": "http://example.edu/credentials/3732",

Section 5.8, example 23:
This example is already correct.

Appendix B, Base Context:
It is unclear to me if any changes to define the context within an embedded verifiable credential are required to this section of the base context:
> "VerifiablePresentation": {
>      ...
>        "verifiableCredential": {"@id": "cred:verifiableCredential", ... }

Appendix C.5, example 39:
This example is already correct, except that there is an indenting issue in the second embedded credential.

I will create a pull request to implement these changes.

**Comment by burnburn** [comment]
From VCWG call on 11 June 2019:

RESOLUTION: Issue #654 is addressed via PR #655. The PR has been merged, close the issue immediately (no 7 day close).
