### ISSUE TITLE
Issue 6 and 8 (ZKP and JWT) implementers

### ISSUE THREAD

**Issue by Iso5786** [w3c/vc-data-model#662]
Hi all,
on the VC data model 1.0 page it states under issue 6, that "Zero Knowledge Proofs are a feature at risk. The Working Group is looking for multiple implementers to support the feature during the W3C Candidate Recommendation phase."
I cannot find any related issue here, hence I create a new one to introduce a project that implements this feature.

This project is called IRMA, maybe some of you already read about it. 
From the official doc: 
"IRMA is a set of software projects implementing the Idemix attribute-based credential scheme, allowing users to safely and securely authenticate themselves as privacy-preserving as the situation permits" (via [https://irma.app/docs/what-is-irma/](https://irma.app/docs/what-is-irma/)) 
How IRMA uses ZKP is described here: [https://irma.app/docs/zkp/](https://irma.app/docs/zkp/).

Currently, I am writing my master thesis about whether it is possible to embed the IRMA infrastructure within the VC specification / how to make IRMA comply to the VC specification.

Kind regards,
Daniel Ostkamp

**Comment by brentzundel** [comment]
This is excellent news. I am working on an implementation for Evernym, and @ken-ebert is doing one for Sovrin, both of which will also support ZKPs.
We'd love to touch base with you as you work through incorporating VCs into IRMA. And we invite you to add a [test suite implementation](https://github.com/w3c/vc-test-suite)

**Comment by Iso5786** [comment]
@brentzundel Good to gear! Am now in the phase of describing IRMA and VC in detail and starting to identify differences in concepts of both. 
How would you like to touch base with me? I suggest to have a skype call once I have set some first steps incorporating VCs into IRMA (like in a month or so).
I already had the test suite on my todo list but it's not top priority at the moment.

**Comment by Iso5786** [comment]
Additionally, IRMA can be configured to use JWT (see https://irma.app/docs/session-requests/#jwts-signed-session-requests) because in the VC spec issue 8 states that the JWT  support is a feature at risk.

**Comment by Iso5786** [comment]
@brentzundel Could you provide more information about the projects you mentioned? Also, what are other projects trying to implement VC? This would be useful for my thesis later to mention it in the related work.

**Comment by brentzundel** [comment]
@Iso5786 I sent an email to the address in your profile to continue the conversation.

I recommend we close this issue, as it doesn't call for any changes to the spec.

**Comment by burnburn** [comment]
From VCWG call on 11 June 2019:

RESOLUTION: Issue #662 has not and does not appear likely to result in any suggested changes to specification text, the issue should be closed after a 7 day wait period. Notify the issue submitter that we are moving the discussion to the public-vc@w3.org mailing list.

**Comment by brentzundel** [comment]
@Iso5786, I sent an email to the address listed in your github profile. We could also continue the conversation using the working group mailing list.
If you have more questions related to this topic, please send an email to:
`public-vc@w3.org`
with the subject line:
`Issue #662 - Issue 6 and 8 (ZKP and JWT) implementers`

If you have questions or concerns about a different topic, please email the working group feel free to craft your own subject line.

**Comment by Iso5786** [comment]
@brentzundel Thanks for the info. Will reply to your mail either tomorrow or Friday.
