### ISSUE TITLE
tracking issue for iat → nbf related changes

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-data-model#667]
see https://github.com/w3c/vc-data-model/pull/646#issuecomment-503162022

Changes are still needed to the JWT mapping section, particularly the following, which are now focused on JWT `exp` and JWT `iat` and do not mention JWT `nbf` --

* [lines 3458-3459](https://github.com/w3c/vc-data-model/blob/5a1f617cda647a8be681d5d46fa9232e284aa492/index.html#L3458)
* [lines 3465-3466](https://github.com/w3c/vc-data-model/blob/5a1f617cda647a8be681d5d46fa9232e284aa492/index.html#L3465)
* [lines 3539-3542](https://github.com/w3c/vc-data-model/blob/5a1f617cda647a8be681d5d46fa9232e284aa492/index.html#L3539)
* [lines 3549-3551](https://github.com/w3c/vc-data-model/blob/5a1f617cda647a8be681d5d46fa9232e284aa492/index.html#L3549)

PR for the above to come from @awoie

**Comment by awoie** [comment]
PR is here: https://github.com/w3c/vc-data-model/pull/668

**Comment by msporny** [comment]
I haven't heard back from the Director yet, and I need to prep the document for publication next week (either as a CR or a PR). The group has decided to make this change whether or not a new CR is required per the 2019-07-16 telecon:

https://www.w3.org/2019/07/16-vcwg-minutes.html#item03

The PR has been merged.

**Comment by burnburn** [comment]
In 23 July 2019 call, @awoie and @TallTed agreed with the merge.  No objections.  Closing.
