### ISSUE TITLE
Update list of Editors/Authors for spec.

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#675]
I ran a few tools to determine who has contributed to the specification and in what ways. We need to be careful with these numbers because they don't tell the entire story. For example, there is a ton of work that goes into initial design, offline discussions, implementations, etc. It's also dangerous to count quantity over quality. So, take these numbers with a grain of salt.

The first statistic is lines of code, commits, and file changes. I used a tool called git-fame to do the calculation. The sorting matches GitHubs algorithm pretty closely. The sorted order is below for the top contributors:

```
msporny@tao:~/work/vc-data-model$ git-fame -w -C -M .

| Author               |   loc |   coms |   fils |  distribution   |
|:---------------------|------:|-------:|-------:|:----------------|
| Manu Sporny          |  2430 |    479 |     67 | 66.2/49.3/27.3  |
| Grant Noble          |   240 |     76 |     11 | 3.8/ 4.5/ 2.4   |
| Dave Longley         |   117 |     30 |      7 | 3.2/ 3.1/ 2.9   |
| Dan Burnett          |   116 |     69 |     13 | 3.2/ 7.1/ 5.3   |
| Brent Zundel         |   111 |     43 |     13 | 3.0/ 4.4/ 5.3   |
| Gregg Kellogg        |    86 |     26 |     15 | 2.3/ 2.7/ 6.1   |
| David-Chadwick       |    78 |     31 |     17 | 2.1/ 2.6/ 6.1   |
| Ted Thibodeau Jr     |    78 |     35 |      3 | 2.1/ 3.6/ 1.2   |
| Oliver Terbu         |    73 |      9 |      4 | 2.0/ 0.9/ 1.6   |
| David I. Lehn        |    43 |     18 |      7 | 1.2/ 1.9/ 2.9   |
| Matthew Collier      |    37 |      1 |      5 | 1.0/ 0.1/ 2.0   |
```

I also wrote a tool to pull every single comment from the specification repository and tally the results. The score is the number of comments, plus the number of bytes written divided by 1024. Yes, that's arbitrary, but the arbitrary rule seemed somewhat fair in calculating a final score as it was applied equally across every contributor. Again, the top rankings are shown below:

```
                user |  score |   comments |    bytes |
---------------------------------------
             msporny |   1237 |        810 |   437940 |
      David-Chadwick |    694 |        445 |   255881 |
            dlongley |    366 |        205 |   165495 |
            jandrieu |    305 |        137 |   172485 |
         brentzundel |    263 |        186 |    79741 |
           stonematt |    227 |        168 |    61143 |
            burnburn |    204 |        170 |    34825 |
             nadalin |    167 |        141 |    26942 |
             TallTed |    126 |         72 |    56063 |
            agropper |    108 |         33 |    77424 |
              Drabiv |     94 |         49 |    46694 |
              RieksJ |     75 |         39 |    37402 |
        kimdhamilton |     55 |         30 |    25631 |
        ChristopherA |     48 |         32 |    16398 |
               awoie |     44 |         33 |    12217 |
              chaals |     41 |         31 |    10867 |
            gkellogg |     34 |         25 |     9538 |
          grantnoble |     31 |         29 |     2972 |
```

My suggestion is that we use these numbers to guide who is listed as an Editor and as an Author. Anyone remaining will be specifically called out and thanked above and beyond the typical "Acknowledgements" section.

**Comment by ChristopherA** [comment]
I did a lot of the early architecture, initially as part of the Oasis XDI on blockchain project with Drummond,  later at early #RWOT meetings, and in the google doc. I hope to continue to be considered one of the authors.

**Comment by msporny** [comment]
"Author" has a very specific meaning in W3C land and the bar to be listed there is quite high. It is typically that you contributed a large chunk of substantive text or design to *this* specification. 

You will definitely be listed in the Acknowledgements section, and we could mention RWoT, IIW, and other organizations as being vital to the development of the work. Would that work for you?

**Comment by ChristopherA** [comment]
Yes, for the VC-data-model the acknowledgement and mentions of organizations driving it is acceptable. There will be a similar problem with DID as some of the work was done pre-W3C, but in that case I definitely qualify as "Author".

**Comment by msporny** [comment]
> Yes, for the VC-data-model the acknowledgement and mentions of organizations driving it is acceptable. 

Ok, I'll prep a PR so you and others requesting to be listed in different areas have a chance to review before we go into the Proposed Recommendation stage.

> There will be a similar problem with DID as some of the work was done pre-W3C, but in that case I definitely qualify as "Author".

Yes, and you're listed as such (Author) on that specific document.
