### ISSUE TITLE
Update feature at risk section

### ISSUE THREAD

**Issue by awoie** [w3c/vc-data-model#681]
The current spec text reads:
> The following features are considered at risk of removal due to potentially insufficient implementation experience (reports): credentialSchema property, refreshService property, evidence property, zero-knowledge proof support, disputedClaim property, JWT support, nonTransferable property.

I know that we intend to update the section. This is just a reminder to update the respective section.

**Comment by msporny** [comment]
Fixed in d92ceaf801da67cc698fb80756130c75e04531cb.
