### ISSUE TITLE
Holder Bundling of Separate Claims

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#70]
As pointed out in the section "Bundling of Dependent Claims" the bundling might be done by the holder, when the issuer is happy to issue separate credentials (e.g. to support minimum disclosure). However we need to ensure that the holder does not bundle together separate credentials that were not meant to be bundled together (as in the example of the university issuing Staff member in Dept Computing and Student in Dept Economics as 4 separate credentials). 

One solution to this problem is to provide a group ID with properties that belong together in a credential. If the credential is atomized, each individual property would contain the group ID. In this way, when the holder bundles together a set of credentials and sends them to an inspector, the inspector can immediately tell which properties belong together and which do not. 

This will require a change to the syntax of properties. Currently a property is defined as a name-value pair. But if a property is defined as a set of attributes and a group ID, each of which are name-value pairs, then the inspector can easily link together the properties of complex credentials. 

Viz: in general a property would be:

 “property”: {
    "attributeName": "AttributeValue",     ----- one or many
    "groupID": "groupValue”
  }

For example if the university in the example above issued two VCs to the person, they would contain the following properties:

“property”: {
    "status": "Staff", 
    “dept:”: “Computing”,    
    "groupID": "12345”
  }

“property”: {
    "status": "PG Student", 
    “dept:”: “Economics”,    
    "groupID": "98765”
  }

If the university now atomized the properties, and issued four VCs, they would contain:

“property”: {
    "status": "Staff",  
    "groupID": "12345”
  }

“property”: {
    “dept:”: “Computing”,    
    "groupID": "12345”
  }

“property”: {
    "status": "PG Student", 
    "groupID": "98765”
  }

“property”: { 
    “dept:”: “Economics”,    
    "groupID": "98765”
  }

Now when the holder bundles them together, the inspector can tell if the credentials are related or not.

**Comment by stonematt** [comment]
options in current DM:  

- Issuers doesn't issue atomic credentials that they don't want to be rebounded discreetly
- use ZKP approach.

do these options address the risk? 
-- @jandrieu @TzviyaSiegman we should add this to our use case document

**Comment by jandrieu** [comment]
Moved to use case repo for consideration there. https://github.com/w3c/vc-use-cases/issues/75
