### ISSUE TITLE
(editorial) inline comments make JSON invalid

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-data-model#704]
I hadn't noticed it until flagged by @peacekeeper's comment  https://github.com/w3c-ccg/did-spec/issues/221#issuecomment-513227824 -- but inline comments are not valid JSON.

The syntax-highlight graying of the text is *helpful* but is not sufficient, especially as the gray text is so dark that it is easy to overlook the graying ... which is necessary to have sufficient contrast with the background to pass accessibility standards.  Dimming the background of those *lines* would be better, if we can do this by only styling the text.

I think we should *minimally* state that the `//`-delimited comments are not valid JSON, and advise that such should be removed for use. *Better*, we should provide valid JSON alongside the blocks with these inline comments (e.g., [Example 1](https://w3c.github.io/vc-data-model/#example-1-a-simple-example-of-a-verifiable-credential)).

**Comment by ken-ebert** [comment]
In many examples, the proof section has
"proof": { ... }
We should advise the user that it means that some content has been omitted.

**Comment by brentzundel** [comment]
Would it be sufficient to add a note to the spec that states the examples may contain comments and other notation which makes them invalid JSON?

**Comment by peacekeeper** [comment]
> Would it be sufficient to add a note to the spec

I think that would be my preference as well.

**Comment by ken-ebert** [comment]
Agree with brentzundel and peacekeeper.

**Comment by msporny** [comment]
The WG discussed this issue on 2019-08-13, merged a PR to address the issue, and got confirmation from @TallTed that he was happy with the change.
