### ISSUE TITLE
Verification definition incorrect

### ISSUE THREAD

**Issue by jandrieu** [w3c/vc-data-model#705]
In section 2. Terminology, the spec has the following definition of verification:
> **verification**
> The evaluation of whether a verifiable credential or verifiable presentation complies with this specification.

Unfortunately, this is conformance to the specification, and not verification as meant in the "verifiable" part of "verifiable credentials".

In 5.1 Lifecycle details, we have the following language:
> A verifier verifies the authenticity of the presented verifiable presentation and verifiable credentials. This should include checking the credential status for revocation of the verifiable credentials.

We should use this language (or similar) to correct the glossary term.

**Comment by stonematt** [comment]
PR merged,  Issue resolved.
