### ISSUE TITLE
Verifiable Credentials Implementation Guidelines 1.0

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#714]
There is the table in 7.2  Benefits of JSON-LD and LD-Proofs where it states and X in the Designed to easily support experimental signature systems field, as JWTs allow usage of non-registered signatures to be used, via Collision-Resistant Name.

Also has an X in the Canonicalization requires only base-64 encoding for JWT, this is also not correct.

**Comment by burnburn** [comment]
@nadalin this is an issue against the Implementation Guidelines (https://github.com/w3c/vc-imp-guide/issues).  Please copy your issue/question there.  Closing.
