### ISSUE TITLE
Expressing which credentials are acceptable

### ISSUE THREAD

**Issue by rceleste125** [w3c/vc-data-model#724]
Is anyone working on how to express (JSON?) which credentials or group of credentials are acceptable to access a service or information?  Along those lines, is there work on credential equivalency?  For example (using the classic use case):  If I need to prove i'm over 21, I might show my State issued driver's license, or my government issued passport, etc.  There could be alternative credentials, or n of n (ie: provide 2 of these 5 kinds of credentials).

**Comment by David-Chadwick** [comment]
@rceleste125 Whilst this is a very valuable standardisation topic, unfortunately it is not within the scope of the VC working group. Consequently your request should be taken to the Credentials Community Group.

**Comment by ChristopherA** [comment]
This is an emerging topic in the [CCG](https://w3c-ccg.github.io) (W3C Credentials Community Group) but has not emerged as an official work item yet. But there were some [topic papers](https://github.com/WebOfTrustInfo/rwot9-prague/blob/master/topics-and-advance-readings) and [collaborative drafts](https://github.com/WebOfTrustInfo/rwot9-prague/tree/master/draft-documents) submitted to #RWOT9 related to this topic. Some of these will advance to the CCG.

**Comment by dlongley** [comment]
This is also very related to the Credential Handler API work -- as however this information is expressed would flow through that API. There's some experimentation going on right now regarding how to format this stuff.

@dmitrizagidulin -- do we have any good links we can share yet on examples of CHAPI queries for VCs?

**Comment by dmitrizagidulin** [comment]
@dlongley - Not yet, we're still working on the documentation / spec.
But, for example, here's what a CHAPI query looks like, that asks "Give me all VerifiablePresentations that have the following fields - are of a certain type, and for a particular subject id".

(For those familiar with MongoDB's [document query filters](https://docs.mongodb.com/manual/core/document/#document-query-filter), `QueryByExample` type queries work on a similar principle.)

```
  {
    "web": {
      "VerifiablePresentation": {
        "query": [{
          "type": "QueryByExample",
          "credentialQuery": {
            "example": {
              "type": ["VerifiableCredential", "AlumniCredential"],
              "credentialSubject": {
                "id": "did:example:ebfeb1f712ebc6f1c276e12ec21"
              }
            }
          }
        }]
      }
    }
  }
```

**Comment by brentzundel** [comment]
As this issue is not calling for changes to the specification, and answers have been provided for the issue creator, we will close it in 7 days if there is no objection.

**Comment by brentzundel** [comment]
No engagement since being marked pending close. 7-day window has elapsed. Closing.
