### ISSUE TITLE
openid implementations

### ISSUE THREAD

**Issue by victorherraiz-santander** [w3c/vc-data-model#725]
Is there any example of implementation of the specification on top of openid?

**Comment by dmitrizagidulin** [comment]
@victorherraiz-santander Yes, definitely. Although it partly depends on what you mean by on top of OpenID.

In general, the JWS serialization of Verifiable Claims, which is part of the spec, is intended to be able to be dropped right in to existing JOSE-based protocols such as OpenID Connect. For an example of how you can use OpenID to _obtain_ Verifiable Credentials, look at the paper from Rebooting Web of Trust 8, [Using OpenID Connect Self-Issued to achieve DID Auth](https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/draft-documents/did-auth-oidc.md) (specifically, the [Presentation of claims](https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/draft-documents/did-auth-oidc.md#presentation-of-claims) section), which uses the Self-Issued OpenID Connect flow to receive Verifiable Credentials as you would any other claims in an ID Token. 

For an example of how you can do _authentication_ using a combination of VCs and OIDC, look at the work the Government of British Columbia and Mattr teams are doing over at https://github.com/bcgov/vc-authn-oidc/blob/master/docs/README.md. 

(And keep in mind that this working group and this spec (this VC Data Model repo) has only standardized the _data model_, and that there will be ongoing work to standardize the _protocol_ aspect of it, the part of how do you actually use it.)

**Comment by victorherraiz-santander** [comment]
Thank you @dmitrizagidulin, those links will keep busy for a while!

**Comment by brentzundel** [comment]
@victorherraiz-santander not sure if there is more that you are looking for here. Would it be okay to close this?

**Comment by kdenhartog** [comment]
marking this as pending close with the note that lots of work has been happening in the OIDF to integrate VCs into OIDC. I'd suggest looking at their bitbucket account or joining their mailing list for more details.

**Comment by brentzundel** [comment]
No comments since marked pending close. Closing
