### ISSUE TITLE
Relying party definition is missing

### ISSUE THREAD

**Issue by kimdhamilton** [w3c/vc-data-model#735]
"Relying party" is used in the VC-data-model document, with links that go nowhere. They reference https://w3c.github.io/vc-data-model/#dfn-relying-parties, but this link target is missing in the document.

Example:

> An identity provider, sometimes abbreviated as IdP, is a system for creating, maintaining, and managing identity information for holders, while providing authentication services to relying party

The "relying party" link target is missing.

**Comment by brentzundel** [comment]
The link provided now takes the user to the term `relying party` within the `verifier` definition. Is this sufficient?
I don't believe more changes are needed. We will close in 7 days if there is no objection.

**Comment by brentzundel** [comment]
No engagement since being marked pending close. 7-day window has elapsed. Closing.
