### ISSUE TITLE
Clarification of the Verifiable Data Registry (VDR)

### ISSUE THREAD

**Issue by marceljay** [w3c/vc-data-model#738]
Regarding the role of the Verifiable Data Registry, it might not be clear to some (at least to me), what kind of authorities and permissions it has and what it could control. 
Examples of such registries are, according to the spec "trusted databases" or "distributed ledgers". The VDRs mediate the "creation and verification of identifiers". 

In the [aries vdri package](https://github.com/hyperledger/aries-framework-go/blob/master/pkg/vdri/registry.go#L89) a function to create DID documents is implemented. 
`func (r *Registry) Create(didMethod string, opts ...vdriapi.DocOpts) (*diddoc.Doc, error) {`

**Why would such a registry create DID documents and who would control these documents?** 

In a [2018 discussion](https://docs.google.com/document/d/1dCPGKiW9uqVd1X_Ye6BCFt4qzRRGjPNfTuYEQKIZk6k/edit#), it was mentioned that the VDR could be perceived as a centralized component and a naming proposal for "Lookup Service" was made. If viewed as a lookup service, why should it be able to create DID documents?

[Excerpt from the spec:](https://w3c.github.io/vc-data-model/#ecosystem-overview)

> 
> verifiable data registry
> A role a system might perform by mediating the **creation and verification of identifiers**, keys, and other relevant data, such as verifiable credential schemas, revocation registries, issuer public keys, and so on, which might be required to use verifiable credentials. Some configurations might require correlatable identifiers for subjects. Example verifiable data registries include trusted databases, decentralized databases, government ID databases, and distributed ledgers. Often there is more than one type of verifiable data registry utilized in an ecosystem. 
>

**Comment by David-Chadwick** [comment]
On 22/04/2020 21:36, Marcel Jackisch wrote:
>
> Regarding the role of the Verifiable Data Registry, it might not be 
> clear to some (at least to me), what kind of authorities and 
> permissions it has and what it could control.
> Examples of such registries are, according to the spec "trusted 
> databases" or "distributed ledgers". The VDRs mediate the "creation 
> and verification of identifiers".
>
If we have a distributed system where entities are creating their own 
identifiers, then we have to have some rules for this otherwise it would 
be anarchy. The VDR conceptually sets these rules. We could have an 
entity that controls the identifier creation according to its own rules 
(e.g. IANA and the DNS) or have a prior agreed set of rules that say how 
distributed entities can create identifiers themselves without any fear 
of clashes (e.g. FIDO2 where the identifiers are public keys 
independently created by the users, or DIDs with DLTs where again users 
create their own identifiers). Either way, the VDR is the conceptual 
entity that controls this. Different VC ecosystems will have different 
VDRs with different sets of rules. This might mean that they are unable 
to interoperate (unfortunately).

Kind regards

David

**Comment by marceljay** [comment]
Understanding the role of the VDR as a referee/arbitrator that enforces the rules of a DID method or VC scheme made a lot of sense to me. Holders register their DIDs on the VDR, the VDR checks if the creation was according to the method's specification, otherwise, the request to register a DID is denied. This is how I grasped the concept. 

The spec states, the VDR mediates the "**creation [...] of identifiers**". I would understand mediation in terms of enforcing rules. However, Aries implemented an interface that requires the "Creation" of DID documents. Is that an edge case, or was that the intention of the spec? If so, what is it necessary for?

**Comment by llorllale** [comment]
@marceljay 

> Aries implemented an interface that requires the "Creation" of DID documents. Is that an edge case, or was that the intention of the spec? If so, what is it necessary for?

These are good questions and the term "mediating" remains in the spec still.

@David-Chadwick 

Can we get some clarification on this nuance to ensure the VC Data Model and aries-framework-go are conceptually aligned?

**Comment by David-Chadwick** [comment]
@llorllale you will need to ask the author of the Aries spec to explain how it conforms to the VC Data Model

**Comment by brentzundel** [comment]
@marceljay has your question been answered such that this issue could be closed?

**Comment by brentzundel** [comment]
No response from the issue creator. We will close in 7 days if there is no objection.

**Comment by marceljay** [comment]
I unfortunately do not work on DIDs currently and cannot comment. If you feel the question has been answered, please close.

**Comment by brentzundel** [comment]
No substantial engagement since being marked pending close. 7-day window has elapsed. Closing.

**Comment by TalentedSunday** [comment]
Hi @llorllale , please were you able to get in contact with the author of the Aries spec that @David-Chadwick mentioned is the one to ask?
