### ISSUE TITLE
Necessary of VC Template specification

### ISSUE THREAD

**Issue by kryptojet** [w3c/vc-data-model#740]
According to the example in the vc-data-model document, the ID of the VC has the form of a single URI, and the ID is also used in refreshService. And that is kind of VC's type ID, and if it is correct, I think the VC's Template specification is also needed. Have you already discussed this? Or am I missed it?
```javascript
// EXAMPLE 20: Usage of the refreshService property by an issuer
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.edu/credentials/3732",
  "type": ["VerifiableCredential", "UniversityDegreeCredential"],
  "issuer": "https://example.edu/issuers/14",
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  },
  "refreshService": {
    "id": "https://example.edu/refresh/3732"
    "type": "ManualRefreshService2018",
  },
  "proof": {  }
}
```

**Comment by wyc** [comment]
Hi @kryptojet, is this still a concern? If so, could you please restate your questions or concern as there may have been changes since your posting.

**Comment by brentzundel** [comment]
No engagement since being marked pending close. 7-day window has elapsed. Closing.
