### ISSUE TITLE
type vs @type

### ISSUE THREAD

**Issue by JaceHensley** [w3c/vc-data-model#745]
Hello!

So in the context file for VCs `"type"` is mapped to `"@type"` and this is called out [here](https://www.w3.org/TR/vc-data-model/#h-note-10) for making it simpler so devs don't need to know the JSON-LD type system. The only problem is that makes it harder for devs with an existing data model to use the VC Data model, if an object they want to put into the credentialSubject already has a "type" field then they cannot do it, even tho it is valid JSON-LD.

My proposal is to use [`"@propogate": false`](https://w3c.github.io/json-ld-syntax/#context-propagation) field when setting `"type": "@type"` and `"id": "@id"`. So the context file would start like this:

```json
{
  "@context": {
    "@version": 1.1,
    "@protected": true,
    "@propagate": false,

    "id": "@id",
    "type": "@type",

    ...
  }
}
```

**Comment by JaceHensley** [comment]
Quick follow up, my proposed solution wouldn't actually work. I can't quite get it to behave how I want so I'm open to suggestions on how to resolve this.

My end goal is to be able to use the "type" field separately from the "@type" field within `credentialSubject`. But maybe that's not possible, it just seems odd that I can have valid JSON-LD but not when using the VC Data Model context.

**Comment by dlongley** [comment]
The definition for `type` is locked in for `credentialSubject`, but if you nest something underneath `credentialSubject` you can change `type` from there (by using a property-scoped context for whatever property you're nesting under).

**Comment by JaceHensley** [comment]
Ah okay so I'd have to nest my actual credentialSubject data in a field like this:

```json
{
  "type": ["VerifiableCredential", "CustomCredential"],
  "credentialSubject": {
    "id": "did:...",
    "data": {
      "@type": "MyDataType",
      "type": "The type of MyDataType"
    }
  }
}
```

and then have a context like this:

```json
{
  "CustomCredential": {
    "@id": "prefix:CustomCredential",
    "@context": {
      "@version": 1.1,
      "@protected": true,

      "data": {
        "@id": "prefix:data",

        "@context": [
          null, // Clear the current context
          {
            "@version": 1.1,
            "@protected": true,

            "@vocab": "https://example.com/"
          }
        ]
      }
    }
  }
}
```

**Comment by JaceHensley** [comment]
So I tried this but it doesn't seem to work because "data" isn't a field directly on the "CustomCredential" ([playground link](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2018%2Fcredentials%2Fv1%22%2C%7B%22CustomCredential%22%3A%7B%22%40id%22%3A%22prefix%3ACustomCredential%22%2C%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22%40protected%22%3Atrue%2C%22%40vocab%22%3A%22https%3A%2F%2Fexample.com%2F%22%2C%22data%22%3A%7B%22%40id%22%3A%22prefix%3Adata%22%2C%22%40context%22%3A%5Bnull%2C%7B%22%40version%22%3A1.1%2C%22%40protected%22%3Atrue%2C%22%40vocab%22%3A%22https%3A%2F%2Fexample.com%2F%22%7D%5D%7D%7D%7D%7D%5D%2C%22type%22%3A%5B%22VerifiableCredential%22%2C%22CustomCredential%22%5D%2C%22credentialSubject%22%3A%7B%22data%22%3A%7B%22type%22%3A%22MyRegularType%22%2C%22otherField%22%3A%22Hello%20There%22%7D%7D%7D))

I tried to nest it within a "credentialSubject" context but it complains that that is a protected term ([playground link](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2018%2Fcredentials%2Fv1%22%2C%7B%22CustomCredential%22%3A%7B%22%40id%22%3A%22prefix%3ACustomCredential%22%2C%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22%40protected%22%3Atrue%2C%22%40vocab%22%3A%22https%3A%2F%2Fexample.com%2F%22%2C%22credentialSubject%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2018%2Fcredentials%23credentialSubject%22%2C%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22%40protected%22%3Atrue%2C%22data%22%3A%7B%22%40id%22%3A%22prefix%3Adata%22%2C%22%40context%22%3A%5Bnull%2C%7B%22%40version%22%3A1.1%2C%22%40protected%22%3Atrue%2C%22%40vocab%22%3A%22https%3A%2F%2Fexample.com%2F%22%7D%5D%7D%7D%7D%7D%7D%7D%5D%2C%22type%22%3A%5B%22VerifiableCredential%22%2C%22CustomCredential%22%5D%2C%22credentialSubject%22%3A%7B%22data%22%3A%7B%22type%22%3A%22MyRegularType%22%2C%22otherField%22%3A%22Hello%20There%22%7D%7D%7D))

Finally I just put the "data" context entry at the top level and that seems to get me what I what ([playground link](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2018%2Fcredentials%2Fv1%22%2C%7B%22CustomCredential%22%3A%7B%22%40id%22%3A%22prefix%3ACustomCredential%22%2C%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22%40protected%22%3Atrue%2C%22%40vocab%22%3A%22https%3A%2F%2Fexample.com%2F%22%7D%7D%2C%22data%22%3A%7B%22%40id%22%3A%22prefix%3Adata%22%2C%22%40context%22%3A%5Bnull%2C%7B%22%40version%22%3A1.1%2C%22%40protected%22%3Atrue%2C%22%40vocab%22%3A%22https%3A%2F%2Fexample.com%2F%22%7D%5D%7D%7D%5D%2C%22type%22%3A%5B%22VerifiableCredential%22%2C%22CustomCredential%22%5D%2C%22credentialSubject%22%3A%7B%22data%22%3A%7B%22type%22%3A%22MyRegularType%22%2C%22otherField%22%3A%22Hello%20There%22%7D%7D%7D)). I do wish I could scope it under the `CustomCredential` type tho, but this is fine. Thanks for the help!

**Comment by dlongley** [comment]
> I do wish I could scope it under the CustomCredential type tho, but this is fine. Thanks for the help!

There are two additional options here. The first is to set `"@propagate": true` for your `CustomCredential` scoped-context. Note that this still won't "scope it to your CustomCredential" (it will live beyond it, but only in further nested data). But I think what you actually want here is to "scope it to the value of `credentialSubject`". To do the latter, which is the second option, you must add a type to your `credentialSubject` value -- with an entry for it in the context that has its own scoped context that defines `data`.

**Comment by JaceHensley** [comment]
Cool, yeah I actually ended up doing the latter :) I'll close this issue now, thanks again!
