### ISSUE TITLE
verifiable data registry description in EcoSystem

### ISSUE THREAD

**Issue by whatisthejava** [w3c/vc-data-model#749]
What is the purpose of **might** in the following section 

https://www.w3.org/TR/vc-data-model/#ecosystem-overview

verifiable data registry
A role a system **might** perform by mediating the creation and verification of identifiers, keys, and other relevant data, such as verifiable credential schemas, revocation registries, issuer public keys, and so on, which might be required to use verifiable credentials. Some configurations might require correlatable identifiers for subjects. Example verifiable data registries include trusted databases, decentralized databases, government ID databases, and distributed ledgers. Often there is more than one type of verifiable data registry utilized in an ecosystem.

I cannot see a VDR could exist without an entity performing this issue, thus the might is misleading.

(Holder also uses the term might and I am sure it is a mandatory role)

From my reading, I think you are suggesting that the VDR is not required within the ecosystem.   
I think this may be hinted at in this diagram https://www.w3.org/TR/vc-data-model/diagrams/ecosystemdetail.svg but I do not think its explained in enough detail

Thanks

**Comment by brentzundel** [comment]
> From my reading, I think you are suggesting that the VDR is not required within the ecosystem.

This is the correct reading. While in many cases a VDR may play a role in a VC ecosystem, it might not.

**Comment by David-Chadwick** [comment]
On 07/09/2020 16:41, whatisthejava wrote:
>
> What is the purpose of *might* in the following section
>
> https://www.w3.org/TR/vc-data-model/#ecosystem-overview
>
> verifiable data registry
> A role a system *might* perform by mediating the creation and 
> verification of identifiers, keys, and other relevant data, such as 
> verifiable credential schemas, revocation registries, issuer public 
> keys, and so on, which might be required to use verifiable 
> credentials. Some configurations might require correlatable 
> identifiers for subjects. Example verifiable data registries include 
> trusted databases, decentralized databases, government ID databases, 
> and distributed ledgers. Often there is more than one type of 
> verifiable data registry utilized in an ecosystem.
>
> I cannot see a VDR could exist without an entity performing this 
> issue, thus the might is misleading.
>
> (Holder also uses the term might and I am sure it is a mandatory role)
>
> From my reading, I think you are suggesting that the VDR is not 
> required within the ecosystem.
>
Yes this is my interpretation of might

But I agree that it is ambiguous as it could imply that a VDR does exist 
and it might do abc or a VDR might exist, and if it does, ...

Essentially it is possible to configure the issuer, holder and verifier 
with all the meta data they need without recourse to a VDR. And if you 
have one or more VDRs you will not obviate the need for some 
configuration information.

Kind regards

David

**Comment by whatisthejava** [comment]
> > From my reading, I think you are suggesting that the VDR is not required within the ecosystem.
> 
> This is the correct reading. While in many cases a VDR may play a role in a VC ecosystem, it might not.

Without a VDR I presume the issuer only has the following options to verify their own identity 

Provide evidence out of band to the verifier
Provide a secured public  endpoint and delegate the responsibility to the CA that issued their certificate 
Use a FIDO2 based system 

Again, sorry this may be slightly off topic  but again I think the spec really needs some sample implementations to help clarify the differences available

**Comment by David-Chadwick** [comment]
On 08/09/2020 11:23, whatisthejava wrote:
>
>         From my reading, I think you are suggesting that the VDR is
>         not required within the ecosystem.
>
>     This is the correct reading. While in many cases a VDR may play a
>     role in a VC ecosystem, it might not.
>
> Without a VDR I presume the issuer only has the following options to 
> verify their own identity
>
> Provide evidence out of band to the verifier
> Provide a secured public endpoint and delegate the responsibility to 
> the CA that issued their certificate
> Use a FIDO2 based system
>
FIDO2 does not verify the identity of the issuer, only the key of the holder

Kind regards

David

**Comment by kdenhartog** [comment]
I don't believe this will require any additional text to the spec so I'm going to mark this as pending close with no further action items needed.

**Comment by brentzundel** [comment]
No comments since marked pending close. Closing
