### ISSUE TITLE
Verifiable Credential status

### ISSUE THREAD

**Issue by NikosFotiadis** [w3c/vc-data-model#757]
Hi everyone,
I have a question regarding reading the status of the verifiable credential.

I am using an ethereum smart contract to store verifiable credentials and the status of the. In order to read the status of a credential, the spec says that the `credentialStatus` object can contain a link. Can that be a link to an endpoint that will read the status from the smart contract and return it?

Obviously, that can be done but would an implementation like that be according to the spec?

**Comment by kdenhartog** [comment]
Yeah this can be done, but you may be venturing into an area where you'll want to define what the credentialStatus object will look like and how it will behave via a draft spec similar to [vc-status-rl-2020](https://github.com/w3c-ccg/vc-status-rl-2020).

If you're just looking to expand on a credentialStatus already defined then this should be possible by extending the documentLoader to be able to retrieve the document from the smart contract and then it can be processed in the same way as others. For example, when using a web server with vc-status-rl-2020 our implementations expect that a well formatted VC will be returned. It could be the case that your documentLoader is able to read a condensed portion of data from the smart contract and then build a VC that matches the VCs returned by web servers normally. This would allow you then to be able to use a link to the smart contract that your document loader understands and then all other VC processing would work the same way including the revocation checks.

**Comment by brentzundel** [comment]
No engagement since being marked pending close. 7-day window has elapsed. Closing.
