### ISSUE TITLE
Credential type for Vaccination Passports?

### ISSUE THREAD

**Issue by dpjanes** [w3c/vc-data-model#763]
What would be an appropriate credential type for a "Vaccination Passport" / "Medical Test Result"? e.g. a credential asserts that I've received a vaccination or got a test. Or should a new type be created, e.g. `HealthCredential`.

**Comment by dpjanes** [comment]
Although now looking further, it seems that credential types are all very loose at this time?

**Comment by OR13** [comment]
Implementers are responsible for creating their own credential types, I would suggest inheriting from an stablished ontology when doing so.

**Comment by tplooker** [comment]
Hi @dpjanes we have start to define an experimental vocab for this [see here](https://github.com/mattrglobal/vaccination-certificate-vocab)

**Comment by dpjanes** [comment]
Hi @tplooker it looks like we are working along similar lines

https://github.com/Consensas/information-passport/tree/main/docs

or if you just want to see an example (and in action)

* https://github.com/Consensas/information-passport/blob/main/docs/VerifiableCredential.md
* https://passport.consensas.com/

**Comment by talltree** [comment]
[Lumedic](https://www.lumedic.io/lumedic-exchange), which is part of Providence Healthcare, already has their W3C VC-based vaccination credentials in production. They are going to be publishing all of it as open source/open governance. I'll ping them about this thread.

**Comment by jstclair2019** [comment]
@dpjanes happy to discuss what Lumedic is using for Providence Health Systems. As @talltree said we'll be releasing our schema through the Lumedic Exchange and publishing to the web as a v1, with a possible GitHub repo.

**Comment by tplooker** [comment]
@jstclair2019 thats great, are you using a JSON-LD based schema representation?

**Comment by tplooker** [comment]
@dpjanes thanks for the links! note the examples in our linked repo are also valid verifiable credentials that we produced with our infrastructure to verify the vocabulary definition. The JSON-LD syntax in your linked example is interesting, would be great to chat about it more?

**Comment by jstclair2019** [comment]
> @jstclair2019 thats great, are you using a JSON-LD based schema representation?

@tplooker Tobias, great question. We are based on the Aries stack, so at this point we are ZKP-CL, however we want to evaluate migration to JSON-LD/BBS+ eventually. As you probably know, healthcare is highly regulated and our architecture was reviewed through Compliance as part of implementation. We are also looking to follow-on accreditation (HIPAA/HITRUST, FISMA, etc) and the use of these specifications will also get examined in that vein, as well as promoting interoperability (which I love). 
Publishing the schema will provide an opportunity to field comments and recommendations that we'll consider as part of the development lifecycle.

**Comment by tplooker** [comment]
@jstclair2019, thanks for the clarification. One of the goals of the approach we have taken is to be able to issue fully conformant W3C Verifiable Credentials out of the box, that are using an underlying vocab that defines as little as possible, in our opinion ideally it should really be just aggregating existing definitions from the relevant healthcare standards. It would be great to review your schema once available and look for overlap. However as you highlight, it may be difficult to completely reconcile these approaches at the moment because ZKP-CL uses a bespoke schema definition format and the issued credentials still have a way to go in order to be W3C VC spec compliant. W.r.t a potential future migration to JSON-LD/BBS+ thats great to hear, happy to help in that process.

**Comment by jstclair2019** [comment]
@tplooker Yes, I fully agree with your summation. I understand Ontario recently sponsored a code-a-thon around JSON-LD/BBS+ and I'm hoping some lessons come out of that we can leverage. This is a good use case example of why we created the Lumedic Exchange as an independent stakeholder body of health industry reps to contribute to standards adoption and conformance. More to come!

**Comment by dpjanes** [comment]
I wrote a thing about W3C Verifiable Credentials yesterday, and its issues:
https://medium.com/consensas/w3c-verifiable-credentials-the-fairly-odd-blueprints-ef30f3ae606a

One issue with the JSON-LD proofs is adds _a lot of code_ that never really gets used except during the signing and verification steps. 13Mb by my count, though likely there's a lot of duplication. This is fine for backend processes, but if you're trying to port to a new language or a constrained system, you've signed up for a lot of pain.

By belief is that the issuer should create documents that are designed to be easily consumed: i.e. push as much work as possible to the issuer. 

@tplooker I guess my issue with the relevant health care standards - and I assume this FHIR - is it's not really easy to deliver business logic to deal with it without coding something. It's also more (from what I can see) more of a graph than a document. On the other hand, schema.org defines a very broad vocabulary that encompasses medical terminology and is widely understood.

@jstclair2019 - you're on the LF Public Health Slack? Do you have a link to the code-a-thon … I'm looking around for it and can't see anything.

**Comment by jstclair2019** [comment]
@dpjanes You bet, it was actually a competitive procurement, and it was British Columbia not Ontario, sorry: https://digital.gov.bc.ca/marketplace/opportunities/code-with-us/3f9f0e86-b8bf-47ee-9f3d-5b272f9ec845
I rad your Medium post about the size of the JSON-LD proofs and thought it was a good summary, as well.

**Comment by dlongley** [comment]
@jstclair2019 and @dpjanes,

> I rad your Medium post about the size of the JSON-LD proofs and thought it was a good summary, as well.

A quick (pedantic?) note for readers here. The size of JSON-LD proofs themselves isn't covered in that article, rather the node.js installation size of the most commonly used JavaScript JSON-LD processor is covered. Furthermore, it's not clear what's meant by this note in the article:

> If you need to have JSON-LD installed to verify a message in your web app, you’ve signed up for 13.2 megabytes of code over 74 packages!

If this is read literally and you're verifying a message *in your web app*, then you won't be using the node.js version of the library. The browser version of the library minimizes and gzips to ~60KB. It's true that the current node.js version of the library does install ~13MB of packages, but this is typically not a major concern in that ecosystem. With a minor bit of effort that could be reduced by more than half if it were a priority. But if the concern here is over what may be delivered to a Web app to support JSON-LD processing -- that should be on the order of ~60KB once minimized and gzipped. There's a `/dist` directory that is built for the browser version of the processor where the minimized file can be manually gzipped to get this number. You may want to update your article to include this information.

You can also visit the [JSON-LD playground](https://json-ld.org/playground) and use the Chrome developer tools to see live download sizes which, for me, for whatever version the playground is using, reports ~63KB for the processor and ~18K for the jsonld-signature verification library.

Anyway, the point is that the optimization targets (node vs. the browser) are very different.

**Comment by jstclair2019** [comment]
Thanks @dlongley ! Speaking for myself, I appreciate that sort of clarification. I'm also glad to keep plugging the work we seek to do in [Lumedic Exchange](https://www.lumedic.io/lumedic-exchange) for stakeholders to define the use cases and workflows that consider these technical aspects as part of any proposed specs/implementation guides.

**Comment by dpjanes** [comment]
I literally just did `npm install jsonld` and showed the output in the article. So even if it compresses to 60KB or 13KB, that's still 60KB or 13KB of code that does one thing on a client: unpack a JSON object into a graph, apply an algorithm, and say "yes" or "no". 

But yes thank you @dlongley, I will add a note. I'm not trying to misrepresent anyone, and the last thing I want to be doing is implementing or arguing about signature algorithms (but I will argue about them, it's just not high on the priority list).

**Comment by OR13** [comment]
JSON in not mean to be size efficient.... use CBOR or GZIP if you need things to be smaller... use JSON for human / machine readable formats... side note, base64url inflates JSON even more, making VC-JWT both large and not human readable.

the vc data model is about a semantically unambiguous verifiable credential format that is both human and machine readable.

You will likely need to apply compressing, encryption and other technology solutions to use this standard at scale... IMO its a good thing that they are not "baked into" the format... do one thing, and do it well.

**Comment by kdenhartog** [comment]
I've marked this as pending 7 days close. It appears the question has been answered at this point and there's no action items that can be taken to address this within this spec.

**Comment by brentzundel** [comment]
No comments since marked pending close. Closing
