### ISSUE TITLE
nonTransferable not in context

### ISSUE THREAD

**Issue by clehner** [w3c/vc-data-model#765]
The [nonTransferable property](https://w3c.github.io/vc-data-model/#nontransferable-property) (non-normative section) is not in the credentials v1 JSON-LD context or in the example context. [json-ld-api](https://github.com/w3c/json-ld-api/) says keys without definitions in context should be [ignored](https://w3c.github.io/json-ld-api/#overview-3) during JSON-LD expansion - but [vc-http-api](https://github.com/w3c-ccg/vc-http-api) requires verifying a credential with an unknown property to [fail](https://github.com/w3c-ccg/vc-http-api/blob/be2932ae3e1342821c4af6997d059935af8b6377/packages/plugfest-2020/plugfest-2020.spec.js#L268-L281). Either way means `nonTransferable` cannot be used as-is. Is there an existing URI for it that could be used in a context object to make it useful in the example?

**Comment by brentzundel** [comment]
this may be a duplicate of #731

**Comment by clehner** [comment]
Yes, it is, thanks @brentzundel
