### ISSUE TITLE
AlumniCredential missing from example VC context

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#769]
The AlumniCredential term is missing in the Verifiable Credentials Example context: https://www.w3.org/2018/credentials/examples/v1

... which causes the value to be interpreted as a relative URL in Example 2, which is wrong:

https://www.w3.org/TR/vc-data-model/#example-2-a-simple-example-of-a-verifiable-presentation

Thanks to @iherman for catching the bug.

**Comment by iherman** [comment]
@msporny, this is not a normative file; i.e., I believe it is perfectly all right to update the file on the repository without any further ado.

**Comment by msporny** [comment]
> @msporny, this is not a normative file; i.e., I believe it is perfectly all right to update the file on the repository without any further ado.

In this particular case, I completely agree with you, but our reasoning might be different.

It's ok to add something to this particular context to fix a bug because it's just an example context. No one should be using it for anything production grade.

If we had to make the change in the `https://www.w3.org/2018/credentials/v1` (the main context)... I would object as it could change the signatures on already deployed systems. I'm sure you already know this, but just saying it out loud since we're moving into new territory here (updating REC'd specifications in the VCWG). :)

**Comment by iherman** [comment]
> If we had to make the change in the `https://www.w3.org/2018/credentials/v1` (the main context)... I would object as it could change the signatures on already deployed systems. I'm sure you already know this, but just saying it out loud since we're moving into new territory here (updating REC'd specifications in the VCWG). :)

Agree. Beyond what you say, by the way, the spec includes a copy of the main context (which should be considered, therefore, the authoritative version). All the more reasons not to change without some general agreement and care.

**Comment by clehner** [comment]
There is also `DisputeCredential`, used in [Example 26](https://www.w3.org/TR/vc-data-model/#example-26-a-subject-disputes-a-credential]) but not in the examples context. Reported in https://github.com/w3c/vc-data-model/issues/750

**Comment by kdenhartog** [comment]
I believe this PR has been addressed by #783 and github didn't automatically close this like I expected. Closing.
