### ISSUE TITLE
Typo in description of Figure 7

### ISSUE THREAD

**Issue by pchampin** [w3c/vc-data-model#775]
The describing text in [§3.3](https://w3c.github.io/vc-data-model/#presentations) says:

> The `verifiablePresentation` property in the graph refers to (...)

but it seems to me that it should say

> The `verifiableCredential` property in the graph refers to (...)

**Comment by kuzdogan** [comment]
@pchampin seems to be right. The full sentence is: "The `verifiablePresentation` property in the graph refers to one or more **verifiable credentials** (each a self-contained graph) which in turn contains credential metadata and claims."

Also in Figure 8 the described edge is labeled as `verifiableCredential`.

**Comment by kdenhartog** [comment]
This issue appears to have been addressed in #785 

See this line for details, https://github.com/w3c/vc-data-model/pull/785/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R837

Marking as pending close.

**Comment by pchampin** [comment]
Yes, #785 correctly addresses this issue. Thanks.

Not sure if you expect me to close it now, or to close it once #785 is merged.

**Comment by brentzundel** [comment]
PR #785 has been merged. With @pchampin agreeing that it addresses this issue, I am closing it.
