### ISSUE TITLE
Bound Credentials and Unbound Credentials

### ISSUE THREAD

**Issue by mwherman2000** [w3c/vc-data-model#799]
This issue documents the existence of the difference between Bound Credentials and Unbound Credentials. No fundamental changes are needed to support these 2 broad categories of (Verifiable) Credentials.

NOTE: Bearer Credentials are a more purpose-specific specialization of the more general-purpose concept of Unbound Credentials.

This issue replaces PR https://github.com/w3c/vc-data-model/pull/788 . This issue should be marked as Defer V2

References:
- [Structured Credential Model v0.51 (AKUW Edition)](https://www.youtube.com/watch?v=9RLYS7Xvabc)
- Issue https://github.com/w3c/vc-data-model/issues/792

**Comment by brentzundel** [comment]
>  No fundamental changes are needed to support these 2 broad categories of (Verifiable) Credentials.

I propose closing this issue without further action

**Comment by brentzundel** [comment]
No response since marked `pending close`, closing.
