### ISSUE TITLE
Update github link to use TR instead of github.io

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#852]
![Screen Shot 2021-12-16 at 11 02 34 AM](https://user-images.githubusercontent.com/8295856/146416040-96bdbcf2-2584-4356-a99b-2a774c911e27.png)

**Comment by csarven** [comment]
As far as I can tell, https://w3c.github.io/vc-data-model/ is used as the ED. https://www.w3.org/TR/vc-data-model/ refers to it as the ED as well.

Please correct me if I'm wrong: as far I know, W3C doesn't include EDs under `https://www.w3.org/TR/` - only W3C "published" documents as per Process.

Is there something in the works that wil incorporate EDs under w3.org TR/ ?

**Comment by csarven** [comment]
On second read.. I suppose you meant to refer to REC as opposed to ED.

**Comment by kdenhartog** [comment]
Removing the labels because I realized this has nothing to do with the spec and is about the link in this repo. Normally we've referenced the ED in that link, but I'm good with referencing the official REC version there instead. @iherman is the only one who can do that from what I know about the GH permissions at the moment.

**Comment by iherman** [comment]
> Removing the labels because I realized this has nothing to do with the spec and is about the link in this repo. Normally we've referenced the ED in that link, but I'm good with referencing the official REC version there instead. @iherman is the only one who can do that from what I know about the GH permissions at the moment.

Thanks @kdenhartog; I must admit I did not understand the issue at first. I have changed the repo and it now points at the Rec:

![Screen Shot 2022-01-12 at 11 41 51](https://user-images.githubusercontent.com/520723/149125261-9242aa55-3d53-4f51-9ff3-8ee01c529ece.png)
