### ISSUE TITLE
Is there a solution of zero knowledge proof for secp256k1 curve?

### ISSUE THREAD

**Issue by picardcapt1212** [w3c/vc-data-model#861]
Hi, I have a question about zero knowledge proof(below i will refer as zkp).

I made my own custom VC/VP and now I am looking for methods to secure personal information in verifiable credentials using ZKP or Selective Disclosure.

What I found is using CL signature, BLS signature and Bullet Proof. I runned the test code I found and made a conclusion below.

(CL Signature)
I knew hyperledger indy was using CL signature(RSA based). I wanted to see how anoncred looks. I runned hyperledger indy test code and found out the result of anoncred was also too big to fit in Verifiable Credential structure. In this case for one commitment(to prove i know this value), the proof was way too big. This was the ZKP I studied about. How did they put these result in VC/VP(like EXAMPLE24, EXAMPLE25 in vc data model)? 

(BLS Signature)
I runned jsonld-signatures-bbs test code and got the result I expected. In this case I knew BLS signature was based on bn curve and this was not the ZKP I studied about. To me I understand it as Selective Disclosure.

(BulletProof)
I found BulletProof algorithm for ZKP based on secp256k1. But when i runned the test code, the result was too big to fit in Verifiable Credential Structure. In this case for one commitment(to prove i know this value), the proof was way too big. This was the ZKP I studied about. How to put these result in VC/VP(like EXAMPLE24, EXAMPLE25 in vc data model) is another challege for me. 

---

In my case i'm using secp256k1 curve so it doesn't match either of those signature scheme(cuz cl signature is based on Strong RSA and bls signature use bn curves ) or BulltProof(cuz the proof for one commitment was too big) .

So my questions are below.
Q1. If Possible, is it okay to apply Selective Disclosure to VC/VP for privacy?

Q2. Is there a solution to use secp256k1 for ZKP or Selective Disclosure?(Really Really Need To Know😭)
(for me BLS Signature is the ideal selective disclousre i want to use)

Q3. Can I get the test code of these two EXAMPLE25, 25? I wonder how I can put the commitment proof in VC/VP.
- EXAMPLE 24: A verifiable credential that supports CL Signatures
```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "type": ["VerifiableCredential", "UniversityDegreeCredential"],
  "credentialSchema": {
    "id": "did:example:cdf:35LB7w9ueWbagPL94T9bMLtyXDj9pX5o",
    "type": "did:example:schema:22KpkXgecryx9k7N6XN1QoN3gXwBkSU8SfyyYQG"
  },
  "issuer": "did:example:Wz4eUg7SetGfaUVCn8U9d62oDYrUJLuUtcy619",
  "credentialSubject": {
    "givenName": "Jane",
    "familyName": "Doe",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts",
      "college": "College of Engineering"
    }
  },
  "proof": {
    "type": "CLSignature2019",
    "issuerData": "5NQ4TgzNfSQxoLzf2d5AV3JNiCdMaTgm...BXiX5UggB381QU7ZCgqWivUmy4D",
    "attributes": "pPYmqDvwwWBDPNykXVrBtKdsJDeZUGFA...tTERiLqsZ5oxCoCSodPQaggkDJy",
    "signature": "8eGWSiTiWtEA8WnBwX4T259STpxpRKuk...kpFnikqqSP3GMW7mVxC4chxFhVs",
    "signatureCorrectnessProof": "SNQbW3u1QV5q89qhxA1xyVqFa6jCrKwv...dsRypyuGGK3RhhBUvH1tPEL8orH"
  }
}
```
- EXAMPLE 25: A verifiable presentation that supports CL Signatures
```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "type": "VerifiablePresentation",
  "verifiableCredential": [
    {
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://www.w3.org/2018/credentials/examples/v1"
      ],
      "type": ["VerifiableCredential", "UniversityDegreeCredential"],
      "credentialSchema": {
        "id": "did:example:cdf:35LB7w9ueWbagPL94T9bMLtyXDj9pX5o",
        "type": "did:example:schema:22KpkXgecryx9k7N6XN1QoN3gXwBkSU8SfyyYQG"
      },
      "issuer": "did:example:Wz4eUg7SetGfaUVCn8U9d62oDYrUJLuUtcy619",
      "credentialSubject": {
        "degreeType": "BachelorDegree",
        "degreeSchool": "College of Engineering"
      },
      "proof": {
        "type": "AnonCredDerivedCredentialv1",
        "primaryProof": "cg7wLNSi48K5qNyAVMwdYqVHSMv1Ur8i...Fg2ZvWF6zGvcSAsym2sgSk737",
        "nonRevocationProof": "mu6fg24MfJPU1HvSXsf3ybzKARib4WxG...RSce53M6UwQCxYshCuS3d2h"
      }
  }],
  "proof": {
    "type": "AnonCredPresentationProofv1",
    "proofValue": "DgYdYMUYHURJLD7xdnWRinqWCEY5u5fK...j915Lt3hMzLHoPiPQ9sSVfRrs1D"
  }
}
```

Im new about SSI, DID, VC, Privacy.  Please let me know if the direction of my study is wrong! 
I am looking forward for answers :)

Thanks!

**Comment by msporny** [comment]
> Q1. If Possible, is it okay to apply Selective Disclosure to VC/VP for privacy?

Yes, the current direction for doing that in a way that's supported by the VCWG seems to be BBS+.

> Q2. Is there a solution to use secp256k1 for ZKP or Selective Disclosure?(Really Really Need To Knowsob) (for me BLS Signature is the ideal selective disclousre i want to use)

Yes, there are a variety of mechanisms. A quick Google search can find them: https://www.google.com/search?q=zkp+secp256k1
 
> Q3. Can I get the test code of these two EXAMPLE25, 25? I wonder how I can put the commitment proof in VC/VP.

There is no test code for those examples. They are an example of what a ZKP could look like. In the 2nd iteration of the VCWG, there will be working test code for BBS+ ZKPs.
