### ISSUE TITLE
example.edu is not a reserved name

### ISSUE THREAD

**Issue by mcr** [w3c/vc-data-model#867]
Neither https://www.iana.org/domains/reserved, https://www.rfc-editor.org/rfc/rfc2606.html nor https://www.rfc-editor.org/rfc/rfc6761.html
reserve "example.edu".  Please don't squat.
You can use, "edu.example", or "university.example" ....

**Comment by TallTed** [comment]
@mcr -- Please see <https://example.edu/>, which states explicitly --

> This domain is for use in illustrative examples in documents. You may use this domain in literature without prior coordination or asking for permission.

-- and itself links to <https://www.iana.org/domains/example>.  There is also some discussion of this at <https://en.wikipedia.org/wiki/Example.com>.

I think your suggestion here would be better redirected to ICANN and IANA, and rewritten as a request to update the relevant registry and other documents to include `example.edu`, which appears, by all available evidence, to have been left out by accident.

**Comment by mcr** [comment]
> @mcr -- Please see https://example.edu/, which states explicitly --
> 
> > This domain is for use in illustrative examples in documents. You may use this domain in literature without prior coordination or asking for permission.
> 

Well, if ICANN really wants this included, then they really should have IANA put that on their web page.  
As a document author (15 RFCs myself), I would stick to what RFC2606 and the iana page says are example names,
and example.edu isn't on that list.   I'm sure it would be a major pain to redo all the examples.
Thank you for the attention.
