### ISSUE TITLE
Update LD-PROOF link to point to DATA-INTEGRITY

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-model#869]
The spec should update all references to LD-PROOF to point to DATA-INTEGRITY:

https://w3c-ccg.github.io/data-integrity-spec/

Note, these references will change once again once the VC 2.0 WG starts up.

**Comment by kdenhartog** [comment]
@peacekeeper was able to update what I thought was all of these references in this PR https://github.com/w3c/vc-data-model/pull/859/

It's worth giving it a double look over to make sure we didn't miss any, but from what I remember we managed to get them all.

**Comment by msporny** [comment]
I've set up a redirect from the old ld-proofs repo to the new data-integrity-spec repo here:

https://github.com/w3c-ccg/ld-proofs/commit/fe518926868289e78aaa1ce0c9d3ad2452304383

The old links work now:

https://w3c-ccg.github.io/ld-proofs/

**Comment by msporny** [comment]
> It's worth giving it a double look over to make sure we didn't miss any, but from what I remember we managed to get them all.

I just did a scan on the latest Editor's Draft... zero mentions of LD-PROOFS.
