### ISSUE TITLE
Diagram issues

### ISSUE THREAD

**Issue by davidlehn** [w3c/vc-data-model#873]
A few issues were reported in https://github.com/w3c/vc-data-model/pull/855#pullrequestreview-862977446 before that PR got merged, but they have not yet been addressed:

- [ ] background rect size: https://github.com/w3c/vc-data-model/pull/855#discussion_r792205469
- [ ] background rect missing: https://github.com/w3c/vc-data-model/pull/855#discussion_r792206583
- [ ] odd offsets: https://github.com/w3c/vc-data-model/pull/855#discussion_r792208466
- [ ] text cut off: https://github.com/w3c/vc-data-model/pull/855#discussion_r792209174
- [ ] "AlumniOf" should be "alumniOf" (1): https://github.com/w3c/vc-data-model/pull/855#discussion_r792219233
- [ ] "AlumniOf" should be "alumniOf" (2): https://github.com/w3c/vc-data-model/pull/855#discussion_r792219876

@chaals Are you still interested in looking at these?

**Comment by brentzundel** [comment]
I believe this work is complete, closing
