### ISSUE TITLE
Are Persistent URI's with https an implementation of VC?

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/vc-data-model#889]
Hi, 

Persistent URIs are URIs which are dereferenceable using content negotation.

So 
```
curl -H "Accept: text/turtle" https://registry.org/id/diploma/123
```

would return 

```
<https://registry.org/id/diploma/123> a <https://schema.org/educationalCredentialAwarded>.
<https://registry.org/id/diploma/123> dc:title "Master in geo sciences".
```

So if the issuer of the diploma, e.g. the university, sets up a PURI service, then
the holder of the diploma could share the PURI as credential.

The verification by the reciever is then simply a https request to this PURI.

The PURI could be made more dynamic if the issuer creates an instance for a student who's identity is known by the issuer.
So the student requests to the university a credential about its diploma and gets
`https://registry.org/id/credentialDiploma/12321312`

Then the job vacancy office can verify the content with 
```
curl -H "Accept: text/turtle" https://registry.org/id/credentialDiploma/12321312
```

would return 

```
<https://registry.org/id/credentialDiploma/12321312> a <https://registry.org/id/diploma/123>.
```

Indicating that this is an instance of the "Master of geo sciences".

Is this example, a valid implementation of the idea behind VC? Or does VC offers more?

**Comment by brentzundel** [comment]
Verifiable credentials is a data model. Unless the persistent URI is in the format of a verifiable credential, which I do not believe it is, it would not be considered to be a verifiable credential. That is not to say that a persitent URI, when dereferenced, might not serve a valid verifiable credential, but that doesn't seem to be what is being asked.

Recommend closing this issue.

**Comment by Sakurann** [comment]
Closing since no objections, marked pending close
