### ISSUE TITLE
issue in the example EXAMPLE 4: Usage of the id property

### ISSUE THREAD

**Issue by SamerW** [w3c/vc-data-model#903]
Hi,
I think that there is an error in the example 4 about the type of the degree mentioned https://www.w3.org/TR/vc-data-model/. You are using "type" to indicate the type of the degree but "type" term is not defined in the context (https://www.w3.org/2018/credentials/examples/v1). What is defined in the context above is "degreeType". Here is how it should be and it is resolving correctly 

 ```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.edu/credentials/3732",
  "type": ["VerifiableCredential", "UniversityDegreeCredential"],
  "issuer": "https://example.edu/issuers/565049",
  "issuanceDate": "2010-01-01T00:00:00Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "degreeType": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  }
}
 ```

the Expanded version 
 ```
[
  {
    "https://www.w3.org/2018/credentials#credentialSubject": [
      {
        "https://example.org/examples#degree": [
          {
            "https://example.org/examples#degreeType": [
              {
                "@value": "BachelorDegree"
              }
            ],
            "http://schema.org/name": [
              {
                "@type": "http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML",
                "@value": "Bachelor of Science and Arts"
              }
            ]
          }
        ],
        "@id": "did:example:ebfeb1f712ebc6f1c276e12ec21"
      }
    ],
    "@id": "http://example.edu/credentials/3732",
    "https://www.w3.org/2018/credentials#issuanceDate": [
      {
        "@type": "http://www.w3.org/2001/XMLSchema#dateTime",
        "@value": "2010-01-01T00:00:00Z"
      }
    ],
    "https://www.w3.org/2018/credentials#issuer": [
      {
        "@id": "https://example.edu/issuers/565049"
      }
    ],
    "@type": [
      "https://www.w3.org/2018/credentials#VerifiableCredential",
      "https://example.org/examples#UniversityDegreeCredential"
    ]
  }
]
 ```

**Comment by TallTed** [comment]
@SamerW -- Please edit your initial comment to put code fences around the JSON blocks (here, these should be lines that contain only three backticks, one above and one below the JSON block). This will both make what you've posted more readable (primarily by preserving whitespace), and stop the unwrapped `@type`, `@id`, `@value`, and `@context` from pinging those GitHub users on every update to this issue...

**Comment by msporny** [comment]
> You are using "type" to indicate the type of the degree but "type" term is not defined in the context (https://www.w3.org/2018/credentials/examples/v1).

The `type` term is defined in the first `@context` here: https://www.w3.org/2018/credentials/v1

The example states that the Verifiable Credential is a `UniversityDegreeCredential` and that the `degreeType` of that `UniversityDegreeCredential` is a `BachelorDegree`. 

AFAICT, the example is correct and well-formed.
