### ISSUE TITLE
Add normative reference to Data Integrity

### ISSUE THREAD

**Issue by Sebastian-Elfors-IDnow** [w3c/vc-data-model#912]
In section "[A.4 Proofs (Signatures)](https://w3c.github.io/vc-data-model/#proofs-signatures-0)" in the W3C Verifiable Credentials Data Model v2.0 draft, there is a description of Linked Data Signatures in the Note:

"For example, a Linked Data Signature created [property](https://w3c.github.io/vc-data-model/#dfn-property) establishes a date and time before which the [credential](https://w3c.github.io/vc-data-model/#dfn-credential) should not be considered [verified](https://w3c.github.io/vc-data-model/#dfn-verify)."

However, there is no definition nor reference to the Linked Data Signatures in the W3C VC v2.0 draft.

Furthermore, the Linked Data Proofs specification does not exist anymore at either the https://w3c.github.io/data-integrity/ nor https://w3c-dvcg.github.io/ld-proofs/.

It could make sense to specify Linked Data Proofs in a separate standard and then refer to this from W3C VC v2.0 - or in the lack of such Linked Data Proofs standard remove the description of Linked Data Signatures from the W3C VC v2.0 draft.

**Comment by Sakurann** [comment]
The work on Linked Data Proofs specification continues as Data Integrity specification. We should probably change all the references to LDPs in the v2 to Data Integrity and add a note explaining this difference.
(Might be good to have a section in v2 that summarizes "what is different in v2 from v1")

**Comment by msporny** [comment]
We need to add a normative reference to the Data Integrity specification from the VC Data Model specification. This issue is ready for a PR.

**Comment by msporny** [comment]
PR #993 has been raised to address this issue. This issue will be closed once PR #993 is merged.

**Comment by msporny** [comment]
PR #993 has been merged, closing.
