### ISSUE TITLE
Condense editors list to set of current editors

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-data-model#917]
I propose we condense the listed editors down to the set of current editors. Editors of previous versions are still listed under those versions.
If removal of former editors proves too painful for some, I suggest perhaps an "editors of previous versions" section.
We also have an acknowledgements section that could be suitable.

**Comment by 2byrds** [comment]
> I propose we condense the listed editors down to the set of current editors. Editors of previous versions are still listed under those versions. If removal of former editors proves too painful for some, I suggest perhaps an "editors of previous versions" section. We also have an acknowledgements section that could be suitable.

As a watcher, this is a little bit of a funny request in a git version control world :)
Perhaps spec editor lists need to evolve towards a committer model.

**Comment by Sakurann** [comment]
+1
