### ISSUE TITLE
Modify the .htaccess file for https://www.w3.org/2018/credentials

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-model#921]
There is a flaw, in my view, in the current setup for the credential URI redirections. 

The current approach is based on the https://www.w3.org/2018/credentials URL and is using the following `.htaccess` file:

```
RewriteEngine On

RewriteRule ^$ https://w3c.github.io/vc-data-model/vocab/credentials/credentials.html [P,L]

RewriteRule ^v1$ https://w3c.github.io/vc-data-model/contexts/credentials/v1 [E=json,P]
RewriteRule ^examples/v1$ https://w3c.github.io/vc-data-model/contexts/credentials/examples/v1 [E=json,P]

Header set Content-Type application/ld+json env=json
```

What this does is:

- https://www.w3.org/2018/credentials leads to the [HTML vocabulary definition](https://w3c.github.io/vc-data-model/vocab/credentials/credentials.html)
- https://www.w3.org/2018/credentials/v1 leads to the [JSON-LD Context file](https://w3c.github.io/vc-data-model/contexts/credentials/v1)
- https://www.w3.org/2018/credentials/examples/v1 leads to the [Example context file](https://w3c.github.io/vc-data-model/contexts/credentials/examples/v1)

So far so good. However, although the vocabulary definition is also available in Turtle and JSON-LD, and these formats are essentials for Linked Data processors, there is no way to get to those via the usual means. For example, 

```
curl --header "Accept: text/turtle" https://www.w3.org/2018/credentials
```

will _not_ return the Turtle file. If we take the Linked Data aspect of the VC data model, this is a problem.

My proposal is to do a change as follows:

1. Set up an `index.var` file in the directory with the following content:
    ```
    URI: index
    
    URI: index.html
    Content-Type: text/html
    
    URI: index.ttl
    Content-Type: text/turtle; qs=0.6
    
    URI: index.jsonld
    Content-Type: application/ld+json; qs=0.5
    ```
2. Modify the `.htaccess` as follows:
    ```
    RewriteEngine On
    
    RewriteRule ^v1$ https://w3c.github.io/vc-data-model/contexts/credentials/v1 [E=json,P]
    RewriteRule ^examples/v1$ https://w3c.github.io/vc-data-model/contexts/credentials/examples/v1 [E=json,P]
    
    RewriteRule ^$ https://www.w3.org/2018/credentials/index [P]
    
    RewriteRule ^index.html$ https://w3c.github.io/vc-data-model/vocab/credentials/credentials.html [P]
    RewriteRule ^index.ttl$ https://w3c.github.io/vc-data-model/vocab/credentials/credentials.ttl [P]
    RewriteRule ^index.jsonld$ https://w3c.github.io/vc-data-model/vocab/credentials/credentials.jsonld [P]
    
    Header set Content-Type application/ld+json env=json
    ```

(The `.var` file is the usual idiom to set up content negotiations based on media type.)

Of course this needs tests. I have set up this structure in `https://www.w3.org/People/Ivan/Temp/` and I ran some tests which seems to be conclusive:

```
curl --header "Accept: text/turtle" https://www.w3.org/People/Ivan/Temp/
curl --header "Accept: application/ld+json"" https://www.w3.org/People/Ivan/Temp/
curl --header "Accept: application/ld+json" https://www.w3.org/People/Ivan/Temp/
curl --header "Accept: text/turtle application/ld+json" https://www.w3.org/People/Ivan/Temp/
curl --header "Accept: text/html text/turtle application/ld+json" https://www.w3.org/People/Ivan/Temp/
```

and both https://www.w3.org/People/Ivan/Temp/v1 and https://www.w3.org/People/Ivan/Temp/ behave as expected.

WDYT?

@TallTed @pchampin @msporny @dlongley

**Comment by iherman** [comment]
@msporny let us discuss this at TPAC; it is a very technical detail that may not require separate WG discussion. But we should try to settle this soon.

A related issue whether we should, from now on, redirect `https://www.w3.org/2018/credentials` to the v2 version of the vocabulary right now. After all, and in contrast to the v2 version of the context, the vocabulary is backward compatible, so it may not do any harm, and the many small bugs of v1 would then become moot...

cc @brentzundel @Sakurann

**Comment by msporny** [comment]
@iherman and I talked about the redirect to the v2 version of this (as well as the changes above) and it seems to be ok to make all the changes that are suggested. Digital Bazaar will schedule some time to test the .htaccess rules and will then (if approved by the WG), schedule time to do the switch over and then test heavily to make sure nothing broke. We plan to do this in the next month or so.

**Comment by msporny** [comment]
> Of course this needs tests. I have set up this structure in https://www.w3.org/People/Ivan/Temp/ and I ran some tests which seems to be conclusive

I've now been able to test this and it works as expected. +1 to implement these updates.

**Comment by msporny** [comment]
> Of course this needs tests. I have set up this structure in https://www.w3.org/People/Ivan/Temp/ and I ran some tests which seems to be conclusive

I've now been able to test this and it works as expected. +1 to implement these updates.

**Comment by dlongley** [comment]
+1 to the plan here.

**Comment by iherman** [comment]
I have updated .htaccess in /2018/credentials/. It looks like working now:-).

Closing the issue.
