### ISSUE TITLE
Minor edit: correction to out of sync link titles in section 4.3 to JSON-LD spec

### ISSUE THREAD

**Issue by richardbergquist** [w3c/vc-data-model#925]
Minor editorial point. In section 4.3 the note mentions :

> The type system for the Verifiable Credentials Data Model is the same as for [JSON-LD] and is detailed in Section 5.4: Specifying the Type and Section 8: JSON-LD Grammar. 

It's noted that the section numbers in the links appear to be out of sync with the JSON-LD spec. They should point to : 

> Section **3.5**: Specifying the Type and Section **9**: JSON-LD Grammar. 

(I have a fork of the repo, with the links corrected. Happy to submit a PR if that helps)

Thanks
@richardbergquist

**Comment by msporny** [comment]
Good catch. Yes, please submit a PR to fix this @richardbergquist!

**Comment by richardbergquist** [comment]
Thanks. PR submitted: https://github.com/w3c/vc-data-model/pull/955

**Comment by decentralgabe** [comment]
Fixed in #955
