### ISSUE TITLE
Definition of evidence should align with NIST

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-model#926]
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-160v1.pdf

> By applying the security design principles within a systems engineering process, it is possible to assemble a
body of evidence to demonstrate that trust is warranted in an individual system component or
in the system. Once a sufficient basis exists to grant trust, a judgement can be made as to
whether the level of trust granted is sufficient for the specific missions or business operations.

> The security aspects of the solution include the development of the system protection strategy; the
system security design requirements; the security architecture views and viewpoints; the security
design; the security aspects, capabilities, and limitations in the system life cycle procedures; and
the associated security performance verification measures. The security aspects of the solution are
realized during the implementation of the system security design in accordance with the security
architecture and in satisfaction of the security requirements. The evidence associated with the
security aspects of the solution is obtained with a level of fidelity and degree of rigor that is
influenced by the level of assurance  targeted by the security objectives. Assurance evidence is
obtained from standard systems engineering verification methods (e.g., analysis, demonstration,
inspection, and test) and from complementary validation methods applied against the stakeholder
requirements.

^ A few quotes.

**Comment by kdenhartog** [comment]
+1 to this aspect. Thanks for breaking it out into a separate issue.

**Comment by awoie** [comment]
The current definition of evidence is as follows (as per W3C VC spec 1.1):

> This specification defines the evidence property for expressing evidence information.
> evidence
> The value of the evidence [property](https://www.w3.org/TR/vc-data-model/#dfn-property) MUST be one or more evidence schemes providing enough information for a [verifier](https://www.w3.org/TR/vc-data-model/#dfn-verifier) to determine whether the evidence gathered by the [issuer](https://www.w3.org/TR/vc-data-model/#dfn-issuers) meets its confidence requirements for relying on the [credential](https://www.w3.org/TR/vc-data-model/#dfn-credential). Each evidence scheme is identified by its [type](https://www.w3.org/TR/vc-data-model/#dfn-type). The id [property](https://www.w3.org/TR/vc-data-model/#dfn-property) is optional, but if present, SHOULD contain a URL that points to where more information about this instance of evidence can be found. The precise content of each evidence scheme is determined by the specific evidence [type](https://www.w3.org/TR/vc-data-model/#dfn-type) definition.

@OR13 are you suggesting that we change this definition? The current definition is generic enough to also include NIST definition. Do you have a suggestion on what needs to change or which specific part is missing?

**Comment by OR13** [comment]
I'd like to see explicit citation, and alignment with NIST terms... they have their own framing which I believe we can do a better job of relating to our existing term definitions.

**Comment by OR13** [comment]
Suggest we apply post CR label

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-06-vcwg-special#section1-2) on 2023-06-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.2. Definition of evidence should align with NIST (issue vc-data-model#926)

_See github issue [vc-data-model#926](https://github.com/w3c/vc-data-model/issues/926)._




> *Orie Steele:* suggest applying post CR label.

**Brent Zundel:** Definition of evidence as defined by NIST -- do we need to address this before CR? Editorial? Normative changes?  

> *Andres Uribe:* +1 to post Cr.

**Brent Zundel:** Suggestion to set as post-CR - any objections?  

> *Phillip Long:* Post CR works for me.

**all:** No objections, marking as post-CR.  

> *Orie Steele:* We have no required RDF types for evidence.

> *Orie Steele:* best we have are community drafts that are not interoperable, which claim to use evidence.

**Joe Andrieu:** Do we have implementers that have used evidence, isn't it still at risk? I like it, personally, anyone using it?  

**Brent Zundel:** We do need to understand if it's used.  

**Joe Andrieu:** I'm fine w/ moving on.  

**Andres Uribe:** We are debating using this for identity proofing -- right now, thinking of using it.  

</details>

**Comment by longpd** [comment]
The use of evidence is central to the VCs that have been introduced in the education/training community through 1Edtech. Two efforts were undertaken to transform the OBv2.x Open Badge credential to conform with the W3C VC v1.1 data model specification as [OBv3.](https://www.imsglobal.org/spec/ob/v3p0/#evidence-0) Similarly the Comprehensive Learner Record (CLR) was revised to also make it compatible with the VC v1.1 data model and released as [CLRv2](https://www.imsglobal.org/spec/clr/v2p0/). Both of these specifications are done, and are now in Final Candidate Public, meaning they are available to the public for implementation. Both have multiple companies who have committed to incorporate these specifications into their products. 

As more and more educational institutions embrace verifiable credentials, the evidence property will be very important to them, especially in considering Prior Learning Assessments.

**Comment by brentzundel** [comment]
no objections since marked `pending close`, closing
