### ISSUE TITLE
Change the target file for "https://www.w3.org/2018/credentials/"  (at some point...)

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-model#944]
This is more a note to ourselves and may not require immediate actions but, eventually, should be done...

Having changed the relevant `.htaccess` file (see #921) the vocabulary content negotiations now work for the vocabulary, see

```
curl --header "Accept: text/html" https://www.w3.org/2018/credentials/
curl --header "Accept: text/turtle" https://www.w3.org/2018/credentials/
curl --header "Accept: application/ld+json" https://www.w3.org/2018/credentials/
```

They refer to `https://w3c.github.io/vc-data-model/vocab/credentials/credentials.{html,ttl,jsonld}`.

That vocabulary is the "historical" vocabulary, which also has bugs. At some point, the new version of the vocabulary, i.e.,

```
https://w3c.github.io/vc-data-model/vocab/credentials/v2/vocabulary.html
https://w3c.github.io/vc-data-model/vocab/credentials/v2/vocabulary.ttl
https://w3c.github.io/vc-data-model/vocab/credentials/v2/vocabulary.jsonld
```

should take over, i.e., the .htaccess file must be modified to set up new redirections. We have to decide when.

**Comment by iherman** [comment]
To give my personal opinion on the question: it may be done _now_. 

- **Pro**: the v2 version of the vocabulary is backward compatible (and it must remain so!), ie, such a change should not harm any deployed application making direct use of those files.
- **Pro**: the v2 version is maintained, ie, past and future bugs are handled
- **Con**: the v2 version is maintained (😀), ie, new vocabulary items may be added, the current items may be enriched by new statements (e.g., `xxx a owl:ObjectProperty` statement may be added to emphasize that the range of a property _must_ be URL-s). This means there is no 100% stability.

**Comment by msporny** [comment]
This is related to issue #758.

**Comment by iherman** [comment]
@msporny I think this issue can be closed now. Yes, #758 may mean changing the target URL if that one carries, but the current issue is to use v2 in the first place. And that has been done.
