### ISSUE TITLE
Clarification of the type of the "verifiableCredential" field in a VP 

### ISSUE THREAD

**Issue by vdods** [w3c/vc-data-model#958]
https://www.w3.org/TR/vc-data-model/#presentations-0 states
> verifiableCredential - If present, the value of the verifiableCredential [property](https://www.w3.org/TR/vc-data-model/#dfn-property) MUST be constructed from one or more [verifiable credentials](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials), or of data derived from [verifiable credentials](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials) in a cryptographically [verifiable](https://www.w3.org/TR/vc-data-model/#dfn-verify) format.

Semantically speaking, "verifiableCredential" is singular, and I'd expect to be able to pass a verifiable credential directly in to this field, and by the spec, I'd understand that I could also pass in an array of VCs.  If it were "verifiableCredentials", I'd expect to have to pass in an array of VCs.

In VPs I've seen, this field can be an array or a single value (which would canonically convert into a single-element array if an array was required).  Examples:
- https://www.w3.org/TR/vc-data-model/#presentations-0 shows all as arrays.
- https://www.w3.org/TR/vc-imp-guide/#example-3-a-targeted-verifiable-presentation shows a single value (`{ ... }`).
- https://github.com/w3c-ccg/vc-examples/tree/master/docs/chapi-http-edu#response-2 shows a single value.
- https://github.com/danubetech/verifiable-credentials-java/blob/main/examples-ldp-vp.md shows a single value.

Trying to "follow my nose":
- https://www.w3.org/2018/credentials/v1 shows `"verifiableCredential"` has type `@id` (makes no sense) but has `@id` `cred:verifiableCredential` (great).  Looking up `cred` gives...
- https://www.w3.org/2018/credentials# -- a human-readable document which states "The value of the verifiableCredential property MUST describe a VerifiableCredential" (suggests singular) and seems to give a circular definition of "rdfs:range cred:VerifiableCredential" (I'm assuming it's case-insensitive after searching didn't turn up any other document containing "cred:VerifiableCredential").  Looking up "rdfs:range"...
- https://www.w3.org/TR/rdf-schema/#ch_range -- seems to state that rdfs:range is a kind of type definition (which seems redundant with rdfs:type), and in this case implies that the `"verifiableCredential"` field indeed has type `cred:VerifiableCredential` (again, singular).

The VC data model states that arrays of VCs within a VP are allowed, as is the practical necessity.  Though every bit of formal documentation I could find regarding the schema suggested that single values are allowed.

Can anyone offer any clarity on this?  From my experience, it seems like the right answer is that the field is "one or many" (see the many uses of `OneOrMany` in https://github.com/spruceid/ssi/blob/adc604d1a5e0074353ee94ce1c2b20bebd4c67fb/ssi-vc/src/lib.rs) in that a single value is acceptable, an array of values is acceptable.

**Comment by TallTed** [comment]
When you looked up `cred:verifiableCredential`, you stopped at its first occurrence in <https://www.w3.org/2018/credentials#>.  Take a look at its second occurrence, in [4. Term Definitions](https://www.w3.org/2018/credentials/#term-definitions), where it says —
> cred:verifiableCredential with string values interpreted as `@id` with array values interpreted as `@graph`

It's perhaps also worth noting that <https://www.w3.org/2018/credentials#> is an RDFa document, readable by both humans and machines, and includes links to [Turtle](https://www.w3.org/2018/credentials/credentials.ttl) and [JSON-LD](https://www.w3.org/2018/credentials/credentials.jsonld) renditions of the same information.  

Looking at the RDFa, which content I've rendered as Turtle for easier reading here, you can find --
```
...
<https://w3.org/2018/credentials#VerifiableCredential> rdf:type rdfs:Class .
<https://w3.org/2018/credentials#VerifiableCredential> rdfs:label "Verifiable Credential"^^rdf:langString .
<https://w3.org/2018/credentials#VerifiableCredential> rdfs:comment "A credential is a set of one or more claims made by an issuer. A verifiable credential is a tamper-evident credential that has authorship that can be cryptographically verified. Verifiable credentials can be used to build verifiable presentations, which can also be cryptographically verified. The claims in a credential can be about different subjects."^^rdf:langString .
<https://w3.org/2018/credentials#VerifiableCredential> rdfs:isDefinedBy <https://w3.org/2018/credentials#> .
...
<https://w3.org/2018/credentials#verifiableCredential> rdf:type rdf:Property .
<https://w3.org/2018/credentials#verifiableCredential> rdfs:label "verifiable credential"^^rdf:langString .
<https://w3.org/2018/credentials#verifiableCredential> rdfs:comment "The value of the verifiableCredential property MUST describe a VerifiableCredential."^^rdf:langString .
<https://w3.org/2018/credentials#verifiableCredential> rdfs:isDefinedBy <https://w3.org/2018/credentials#> .
<https://w3.org/2018/credentials#verifiableCredential> rdfs:range <https://w3.org/2018/credentials#VerifiableCredential> .
<https://w3.org/2018/credentials#verifiableCredential> rdfs:domain <https://w3.org/2018/credentials#VerifiablePresentation> .
...
```

As you can see in the above, identifiers are case-sensitive.  `cred:VerifiableCredential` is a class; `cred:verifiableCredential` is a property.  (Convention is that Classes start with CapitalLetters, while Properties start with lowercaseLetters.  Yes, this can be confusing.  I didn't invent the convention, and it's firmly in place in many minds, so I haven't been able to change it.)

(I used the [OpenLink Structured Data Sniffer](https://github.com/OpenLinkSoftware/OSDS_extension/) to get the above.  You can acquire this extension from your favorite browser's extension "store", or build it yourself.  The `/develop` branch is a better choice than the `/master`, at the moment.)

**Comment by OR13** [comment]
Potentially related:


- https://openid.net/specs/openid-4-verifiable-presentations-1_0.html

**Comment by brentzundel** [comment]
Question has been answered, no additional clarification requested, closing.
