### ISSUE TITLE
'issued' vs. 'validFrom' (formerly 'issuanceDate') 

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-model#965]
These two properties [`issued`](https://w3c.github.io/vc-data-model/vocab/credentials/v2/vocabulary.html#issued) and [`validFrom`](https://w3c.github.io/vc-data-model/vocab/credentials/v2/vocabulary.html#validFrom) have a strictly identical description. Is that normal? Shouldn't we differentiate these in the vocabulary description?

**Comment by msporny** [comment]
I think we had contemplated adding an `issued` property. Yes, they should be different, but it's debatable if we need `issued` at all. One could argue that the `created` date on the digital signature *is* the issued date and so we don't need an `issued` property at all.

I'm slightly leaning towards getting rid of `issued` as it's not clear what value it provides if we have both `validFrom` and the issuance time on the securing mechanism (either `created` or `iat`).

**Comment by brentzundel** [comment]
Can this issue be closed now that #992 has been merged?

**Comment by msporny** [comment]
The problem here is that the definitions between issued and validFrom are identical and both contain incomplete sentences in the last sentence. The next step here is to determine if "issued" is still needed... and what the new definitions for each item should be.

**Comment by TallTed** [comment]
We know that a VC could be `issued` before it becomes valid, before `validFrom`.  Both `issued`/`created` and `validFrom` are definitely needed.

`issued` and `created` have the same semantics, but subtly different English, so both may be worthwhile, even if they're defined to have the same value and meaning in the VC universe.  If we're going to ditch one of these, I'd be more inclined to drop `created`, partly but not only because `issued` has visible parallel to `iss`.

**Comment by Sakurann** [comment]
From the previous discussions, direction seemed to be an agreement that there are (at least) two sets of important dates: 
1. when a VC was secured/signed expressed issued/expiration
2. when VC becomes valid to be consumed by a Verifier, expressed using `validFrom`, `validUntil` properties.

and there are two points we need to agree on:
- whether properties to express the first point belong in a data model or data integrity / VC-JWT specs, since it is about validify of the signature.
- if this does belong to a data-model, which property names should be used to express the first point - `issued`, `created`, `expired`, etc. (if we decide this belongs to securing specs, we should move the issue to those)

**Comment by David-Chadwick** [comment]
the date/time the VC was secured should not be in the VCDM but in the specs that define how the credential is secured because they will be different in the different specs.
The validFrom property can be before, after or (almost) the same time that the credential was secured.

**Comment by OR13** [comment]
Proposal: remove `issued` from the core data model and context.

**Comment by msporny** [comment]
We also need to remove "issued" from the VC 2.0 JSON-LD context.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-09-15-vcwg#section5-1) on 2022-09-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.1. 'issued' vs. 'validFrom' (formerly 'issuanceDate')  (issue vc-data-model#965)

_See github issue [vc-data-model#965](https://github.com/w3c/vc-data-model/issues/965)._




**Manu Sporny:** As David Chadwick pointed out earlier, there are different kinds of issuance dates.  
… There is the credential issuance date and the signing date.  

**David Chadwick:** The proof should have its own issuance date and expiration date.  
… That's different from what's in the credential.  

**Kristina Yasuda:** There is agreement that these are separate.  
… That's true both about the credential and how it's secured.  
… This issue isn't clear enough on this point. I'd like to close it..  
… We need guidance in the spec on the differences.  

**David Chadwick:** If we do that, that would solve everything.  

**Kristina Yasuda:** Would you like to do a PR, David?.  

**David Chadwick:** Yes, I'd be glad to do a PR.  

**Joe Andrieu:** There's a real-world thing I have called a bachellors of science.  
… That's different than the credential representing the bachellors.  
… There is naming confusion between the three things.  

**Kristina Yasuda:** Is there an issue for that?.  

> *Ted Thibodeau Jr.:* TallTed: the diploma is distinct from the degree.

**Joe Andrieu:** We need to find a way to talk about this.  

</details>

**Comment by OR13** [comment]
"issued" is not in v2 context - https://github.com/w3c/vc-data-model/blob/main/contexts/credentials/v2

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-06-vcwg-special#section1-9) on 2023-06-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.9. 'issued' vs. 'validFrom' (formerly 'issuanceDate')  (issue vc-data-model#965)

_See github issue [vc-data-model#965](https://github.com/w3c/vc-data-model/issues/965)._




**Brent Zundel:** Issued vs. validFrom -- raised by Ivan, two properties have identical descriptions -- is this something that needs to be done.  

**Manu Sporny:** I don't know. I remember this being tricky.  
… Looking at it.  
… We're trying to figure out if we still need `issued`; it's not in the v2 context, since the vocab is not normative right now. If it becomes normative, we will have to do it before CR.  
… I'd say it's safe to close this and I don't think it will blow up on us, hopefully.  
… Everyone needs to remember that if we make the vocabulary normative, it may create issues for us if the definitions in there are not perfectly aligned.  
… Mark pending close is my suggestion.  

> *Shigeya Suzuki:* +1 Orie.

**Orie Steele:** I think we have a bunch of terms that were previously used in v1.1 that are anchored in the vocabulary -- a bit crazy to me that they're not normative, we need to clean that up -- processing v1.1 or v2.0, and if you click through them, you'll hit term definitions that (if they're not understood), we handle that. We should be cautious about this, this is an example of one of those terms. You're expecting the term to have a definition and you'll either see valid information or not.  
… If we are living in a world w/ v1 and v2 credentials, we have to clean this up.  

**Joe Andrieu:** I'm ok w/ any of the proposals, but wanted to note that we're still bumping in to this confusion about "the thing we're talking about"... validFrom/validUntil will be used by the credential, but not the VC itself.  
… I have a DL and it's valid for 3 years vs. the digital signature... there is confusion about what these properties refer to that are not the VC but are being represented by the VC.  

**Brent Zundel:** I've heard a number of folks saying pending close, if vocab is made normative and we have to clean it up, this being closed wouldn't stop us from cleaning that up.  
… Is there text that should go into the data model to fix this and if so, is the text going to be normative.  

**Phillip Long:** Is this something that would be better as a non-normative thing in an implementation guide? So there is a place where distinctions that Joe was making are clearly expressed? We keep running into it because two versions, need to address it, can we raise it in a non-normative way to help?

> *Orie Steele:* if there is confusion at this layer, we have failed to write the core spec properly.

> *Orie Steele:* http-range-14 strikes again.

**Joe Andrieu:** I do like the idea that we could have some of this stuff in implementation guide -- might it have an effect on normative text, might change meaning of validFrom -- VC vs. credential represented by the VC -- if we learned how to talk about it, might change definitions of properties.  

**Brent Zundel:** This tells me that we might need to talk about this, mark as before CR and move on. any opposition?  

**all:** None heard.  

</details>

**Comment by filip26** [comment]
+1 to drop `issued` property from the core model in favor of `proof.created`. 

`validFrom/issuanceDate` + `validUntil/expirationDate` properties determine time range in which claims are truthful. A credential can be issued ex-post multiple times. e.g. by adding a new signature to support the latest cryptography evolution with keeping the old proof to preserve backward compatibility. Having `issued`  property would prevent that as it implies that a credential cannot be re-issued later.

**Comment by David-Chadwick** [comment]
We also need to clarify the difference between the `validFrom` property in the DM and the `created` property in the data integrity proof and the` nbf` in the JWT/Jose spec, and between `validUntil` in the DM and `expires` in the data integrity proof and `exp` in the JWT.

**Comment by TallTed** [comment]
> time range in which claims are truthful

Truth is not an element of VCs/VPs.

Assertions are.

This time range is not one "in which claims are truthful", but one for which the asserter stands by their assertion.

**Comment by filip26** [comment]
@TallTed please note the discussion bellow this issue #1176 Your definition makes it even more interesting when considering multi-signed VC by separate issuers.

**Comment by brentzundel** [comment]
I do not see `issued` in the vocab, nor can I find it in the `@context`
I believe this issue has been fully addressed. We will close in 7 days if no one objects.
