### ISSUE TITLE
Ability to add images in verifiable claims

### ISSUE THREAD

**Issue by r3-za** [w3c/vc-data-model#97]
Are the any thoughts or discussions around how to embed images (ex. passport photos) in verifiable claims? Are there any recommendations of normalization methods, compression or encoding recommendations on binary/image data in VC?

**Comment by davidlehn** [comment]
One option is to add a property such as http://schema.org/image with a [data URL][] value.

[data URL]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

**Comment by msporny** [comment]
@r3-za what @davidlehn said. The recommended practice is to use schema.org image w/ a data URL value. That said, if you don't want multi-MB Verifiable Credentials, you should use links to images instead of embedding the images. There is also talk of using content-addressable links, like an IPFS link, for example... but there is no recommended practice for that yet.

**Comment by dlongley** [comment]
> That said, if you don't want multi-MB Verifiable Credentials, you should use links to images instead of embedding the images.

Keeping in mind the privacy considerations (leakage to the image server).

**Comment by r3-za** [comment]
Thank you for the suggestions.
I agree with @dlongley that storing images on a third party server raises some privacy concerns.
And using the image property to point to a server image may not be sufficient for signature validation since the image itself may change.. 
The content-addressable links are an interesting idea.. having the hash of the image in the URL address ex. /ipfs/QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ/passport_photo.jpg
or 
ni:///sha-256;QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ  .. That way changes to the image can break the hash and the signature in VC.

**Comment by r3-za** [comment]
Furthermore if the DOD which containts the verifiable claims contain an NI:// address then essentially the hash of a portrait photo is stored on blockchain. Isn't that a privacy concern?

**Comment by msporny** [comment]
> hash of a portrait photo is stored on blockchain. Isn't that a privacy concern?

That assumes two things 1) that we are storing hashes of photos on chain, which some will choose not to do (most will store that sort of stuff off chain in a private digital wallet), and 2) that the hashes are computationally feasible to reverse.

The first item is the best way to protect yourself, the second may be infeasible even with the advent of quantum computers. Whether or not something is a privacy concern is dependent on the expected level of privacy.

**Comment by stonematt** [comment]
what's the next step on this topic?

**Comment by David-Chadwick** [comment]
@r3-za 
Would you like to propose some text for inclusion in the data model document that describes how images can be embedded in VCs?

**Comment by r3-za** [comment]
@David-Chadwick Sure I am working on some preliminary work. Where can we propose the schemes?

**Comment by David-Chadwick** [comment]
You can add it to this issue in the first instance to get some feedback. Then when it is a relatively stable you can do a pull request on the existing data model document in order to get the text included in the next update

**Comment by r3-za** [comment]
The structures I have worked on so far are the following..

**Type 1: Image embedded using the 'data' property**
“blob”: {
“label”:”passport1”,
“type”:”jpeg”,
“encode”, “base64”,
“data”: ”[binary content of image in base64]”
}

**Type 2a: Image referenced on IPFS by specifying the protocol, host and hash**
```
“blob”: {
“label”:”passport1”,
“type”:”jpeg”,
“encode”, “base64”,
“protocol” : “ipfs”,
“uri”: “104.131.131.82“
“digest”, “QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvu”,
}
```

**Type 2b:I mage referenced on NI server by specifying the protocol, host and hash**
```
“blob”: {
“label”:”passport1”,
“type”:”jpeg”,
“encode”, “base64”,
“protocol” : “ni”,
“uri”: “/ip4/104.131.131.82/tcp/4001/“
“digest”, “QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvu”,
}
```
I am not sure about the property names blob, uri and digest..

**Comment by msporny** [comment]
I'm attempting to formulate this issue into some specification text or close the issue w/ no changes to the specification. I agree that being able to express an image is important and there have been a number of ways that have been explored in this issue. That said, the only spec text that could possibly change at this point is an example in the spec.

I suggest we do a PR that pulls in an image data URL. Describing images as @r3-za has outlined above is beyond the scope of the VC spec and is better explained via documentation on sites like schema.org or rNews and other IPTC specifications.

I suggest we submit a PR that shows a schema.org image property with a data-url as @davidlehn suggested above to resolve this issue.

**Comment by stonematt** [comment]
does solving this also solve issue #136
