### ISSUE TITLE
Strawman for Increasing Interop

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#972]
There are considerable discussions about whether the `@context` property should be mandatory or not. Regardless of the outcome of this, I believe that both camps would like to achieve interop between their products if at all possible. This issue proposes one way forward. Its a stawman that can easily be shot down in flames, or propped up with metal scaffolding, as you wish. Constructive criticism welcome.

Assumptions.
1. JSON-LD provides one way for decentralised extensability and semantic interoperability of VC products
2. IANA registries provide one way for centralised extensability and semantic interoperabilty of VC products
3. Private federations provide their own specific proprietary ways for extensability and semantic interoperability of VC products in their federation
4. This is not a complete list of ways that extensability and semantic interoperability may be achieved. No doubt countless other methods already exist and new ones will be invented in the future

Given the above, the proposal is to do the following.
A. remove `@context` from the list of mandatory properties that VCs must contain. Define all the existing top level VC properties in the standard without using JSON-LD notation so that their short form names are still valid.
B. add a new standard property "interopMethodsSupported" to the top level of a VC. This property is optionally inserted by the VC Issuer into the VCs that it issues.
C. The definition of this new property is that it contains a list of interop methods that the issuer supports. Each interop method comprises its type followed by any type specific properties. The type is a globally unique URI that identifies the type of interop method that this VC supports.
D. The standard specifies three known interop types, these being JSON-LD, Private and IANA. Other types can be added later.
E. The property of the JSON-LD type is an `@context` property
F. The property of the Private type is a list of property names that this issuer has invented, along with the URL of a page containing information about these properties.
G. The property of the IANA type is the URL of the IANA registry for VCs (note. does not yet exist).

Here is an example

```
{
	"interopMethodsSupported": [{
		"type": "https://www.w3.org/TR/json-ld11/",
		"@context": [
			"https://www.w3.org/2018/credentials/v1",
			"https://www.w3.org/2018/credentials/examples/v1"
		]
	}, {
		"type": "https://www.iana.org/",
		"registry": "https://www.iana.org/assignments/vc/vc.xhtml"
	}, {
		"type": "https://www.w3.org/credentials/v2/private/",
		"properties": ["doctor", "nurse", "prescription", "hospital", "etc"],
		"info": "https://some.page.com/definitionsOfTerms"
	}]
}
```
In this way it is up to each VC issuer to determine how much interop it wants to achieve, ranging from zero (no interopMethodsSupported property is inserted into its VCs) to maximum (both JSON-LD and either IANA or Private methods are inserted into its VCs). 

I don't know what problems the above will give to JSON-LD processors, by placing the `@context` one level down in the JSON rather then being at the top level. Maybe some pre-processing will be needed to bring it to the top leve first. (But then, those of us who implemented JWT proofing had to do some pre-processing of the vc claim before we recovered the complete credential from the JWT.

**Comment by talltree** [comment]
@David-Chadwick Interestingly, I was talking with Sam Smith yesterday and he suggested a very similar solution. He called it a "two layer data model". The first layer, as you described, consisted of a set of fixed properties that would appear in all types (or what you call "interop models") of VCs. The second layer would have type-specified properties and use type-specified extensibility models, just like you describe.

What I find so attractive about such a two-layer model is that it is the best of both worlds. The world of JSON-LD credentials would 100% supported with every one of its decentralized extensibility features. But so would the other worlds of semantic interoperability just as you describe in your post.

W3C VC 2.0 would be the "unifying standard" I hoped it would be.

Bravo.

**Comment by selfissued** [comment]
Thanks for the thoughtful contribution to the discussion, @David-Chadwick . This has significant merit.

**Comment by melvincarvalho** [comment]
When I first looked at this, I thought it a slightly unusual approach.  But the more I stare at it, the more it grows on me.

JSON-LD parsers would need to change how they fetch the context e.g.

```JavaScript
  var context = vc['@context']
```
becomes

```JavaScript
  var context = vc['@context'] || vc.interopMethodsSupported['@context']
```
This *might* be a big ask.  I am unsure.  

Slight nit is that "type" is traditionally used to be a Thing.  And here it's pointing to a document.  The naming and the exact values might benefit from a few rounds or refinement.  Make each entry into a robust object of well agreed shape (of a certain type -- e.g. InteropMethod).

But I think this could be a creative approach that might work today.  Current systems would ignore `interopMethodsSupported` and perhaps through a warning for an unregistered term.  And new implementers could perhaps run with this immediately.

I like that it lets you define your own spec and terms.

The sticking point that I see, is that there's no top level `@context` and that may be a breaking change, for some.

**Comment by melvincarvalho** [comment]
@David-Chadwick possible refinement?

```json
{
	"interopMethodsSupported": [{
		"type": "InteropMethod",
		"info": "https://www.w3.org/TR/json-ld11/",
		"context": [
			"https://www.w3.org/2018/credentials/v1",
			"https://www.w3.org/2018/credentials/examples/v1"
		]
	}, {
		"type": "InteropMethod",
		"info": "https://www.iana.org/",
		"registry": "https://www.iana.org/assignments/vc/vc.xhtml"
	}, {
		"type": "InteropMethod",
		"info": "https://some.page.com/definitionsOfTerms",
		"properties": ["doctor", "nurse", "prescription", "hospital", "etc"]
	}]
}
```

**Comment by David-Chadwick** [comment]
In your example the type serves no useful purpose as it is always the same. It is the info that is now being used to differentiate. So I do not see any value in your changes. Furthermore the VC DM says that types must be a URI

**Comment by TallTed** [comment]
s/`stawman`/[`strawman`](http://dbpedia.org/resource/Straw_man)/g

**Comment by decentralgabe** [comment]
This nicely addresses the concerns and suggestions I've raised in #947. I like the proposal and am supportive of it.

**Comment by OR13** [comment]
In the context of `vc-jwt` and `JSON Web Signature 2020`, I don't see this proposal as moving things forward.

I think we solved for this well, by providing clear media types.

**Comment by Sakurann** [comment]
RESOLVED: The base media type for the VCDM is credential+ld+json. @context is required (MUST) in the base media type; other media types MAY choose to include @context. Serializations in other media types (defined by the VCWG) MUST be able to be transformed into the base media type. Another media type MUST identify if this transformation is one-directional or bi-directional. Bi-directional transformation MUST preserve @context. Transformation rules MUST be defined, but not necessarily by this WG.

**Comment by TallTed** [comment]
@Sakurann — Please revisit https://github.com/w3c/vc-data-model/issues/972#issuecomment-1433763544 and wrap each instance of `@context` in code fences, a la ``` `@context` ```.
