### ISSUE TITLE
Resolve discrepancies between specifications, vocabularies, schemas

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-data-model#979]
From https://github.com/w3c/vc-data-model/pull/977#issuecomment-1312473563:

@iherman wrote...

> I think this is a perfect occasion to sync up the various places where vocabularies are defined. After all, there should be a 100% sync among the following documents:
> - [Data model specification](https://www.w3.org/TR/vc-data-model-2.0)
> - [Data model vocabulary (V2)](https://w3c.github.io/vc-data-model/vocab/credentials/v2/vocabulary.html) 
> - [Data Integrity specification](https://www.w3.org/TR/vc-data-integrity/)
> - [Data Integrity vocabulary](https://w3c.github.io/vc-data-integrity/vocab/security/vocabulary.html) (knowing that this one is still in a messy state; working on it...)
> - [The json schema in this PR](https://github.com/w3c/vc-data-model/blob/add-json-schemas/schema/verifiable-credential-schema.json)

Also noting...

>  - `issued`: is already in the [Data model vocabulary (V2)](https://w3c.github.io/vc-data-model/vocab/credentials/v2/vocabulary.html) but only [mentioned in a spec note](https://www.w3.org/TR/vc-data-model-2.0/#issuance-date); not sure what its fate is
>  - `validFrom` and `validUntil`: has been added to the [Data model vocabulary (V2)](https://w3c.github.io/vc-data-model/vocab/credentials/v2/vocabulary.html) but not yet into the specification; it was the subject of a PR that got in conflict with another one and should come soon now that the conflicts are solved
>  - `serviceEndpoint`: in the [Data model vocabulary (V2)](https://w3c.github.io/vc-data-model/vocab/credentials/v2/vocabulary.html), but not mentioned in the [Data model specification](https://www.w3.org/TR/vc-data-model-2.0). Should it be removed from the vocabulary?
>   - `proofChain`: is listed in the [Data Integrity specification](https://www.w3.org/TR/vc-data-integrity/) specification (not yet in the [Data Integrity vocabulary](https://w3c.github.io/vc-data-integrity/vocab/security/vocabulary.html)). It has a similar structure than `proof`
> - In par with the introduction of `validFrom` and `validUntil` the `expirationDate` and `issuanceDate` will be taken out of the spec. In the [Data model vocabulary (V2)](https://w3c.github.io/vc-data-model/vocab/credentials/v2/vocabulary.html) these are still listed as deprecated properties, and we have to decide whether they should be removed from the schema. Personally, I would propose to remove them; after all, `"additionalProperties":true` means that older VC-s will pass the schema, so there is no problem with backward compatibility.

Some additional callouts:

> Every example in the VCDM spec uses `verificationMethod` a single string value, which seems to conflict with how the property is defined in the Data Integrity spec. I will switch this to an array for now and note it in the new issue. Similarly the `type` property in the `verificationMethod`'s definition says it must be a string value, not an array of strings.

**Comment by decentralgabe** [comment]
We discussing on a WG call and agreed to do a pass right before we publish a version so all will be in sync.

**Comment by TallTed** [comment]
> We discussing on a WG call and agreed to do a pass right before we publish a version so all will be in sync.

To my mind, the issue should not be closed until that pass is made; else, it may be overlooked in the publishing froofrah... 

Or, there should be another issue with a checklist of all such "right before we publish" tasks.
