### ISSUE TITLE
Error in the JSON schema for `proof`

### ISSUE THREAD

**Issue by iherman** [w3c/vc-data-model#980]
The JSON schema in

https://github.com/w3c/vc-data-model/blob/cb0556463b58373afe94eed501eaeaff64764bf8/schema/verifiable-credential/verifiable-credential-schema.json#L73

is not correct. The `proof` property also allows for an array or proofs and not only a single one.

**Comment by decentralgabe** [comment]
https://github.com/w3c/vc-data-model/blob/cb0556463b58373afe94eed501eaeaff64764bf8/schema/verifiable-credential/verifiable-credential-schema.json#L271

Believe this is fine. The def is not the properties...

**Comment by iherman** [comment]
Oops, you are right @decentralgabe, I missed that. Sorry for the noise; closing.
