### ISSUE TITLE
Terminology needs to be revised

### ISSUE THREAD

**Issue by RieksJ** [w3c/vc-data-model#983]
In a [message](https://lists.w3.org/Archives/Public/public-credentials/2022Nov/0148.html) to the W3C Credentials CG list, @msporny made a couple of statements, e.g.:

> The three VC ecosystem roles have always been an imprecise simplification to get the most important concepts across. 

The bulk of his message is part of an argument that finds it roots in this 'imprecise simplification' of (in this case) the issuer. He concludes by saying:

> I just wanted to correct this critical misperception, specifically, because it led to a variety of misunderstandings in your previous post. I'll get around to responding to the rest of your email as I have time... there's a lot to unpack there. :)

I would not be surprised if Manu (and with him: many others) would have to spend increasingly more time addressing critical (or noncritical) misperceptions unless we mature (and professionalize) the terminology/definitions that are the source of these misperceptions. 

In fact, I think that the time and effort that is needed (once) to do this is much less than the time and effort that will be needed (many more times) to address misperceptions. Also, I think any text (standard, white paper, ...) that commits to using well-defined terms will be of a higher quality (i.e.: are easier to read, more difficult to misinterpret) than texts that use immature terms.

**Comment by mwherman2000** [comment]
I hope it is OK to ask a clarifying question about the VC 3-role model? ...a perhaps naïve question about the Verifiers role...

Is the Verifier role 
(a) a service that can be asked to verify the authenticity of a VC for someone? ...or... 
(b) is the Verifier the someone who is seeking to have the authenticity of a VC verified?  
...they're quite different.

...do you have link that explains your choice (e.g. into the VC spec)?

A Bank is used in many Verifier examples (not sure if its used in the VC spec itself) ...that choice doesn't provide any clarity because a Bank can be both an (a) and a (b).

This definition from the VC spec isn't adequate...

> A role an [entity](https://www.w3.org/TR/vc-data-model/#dfn-entities) performs by receiving one or more [verifiable credentials](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials), optionally inside a [verifiable presentation](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-presentations) for processing.

**Comment by RieksJ** [comment]
The fact that this question arises is yet another proof that revision of the terminology is needed, as a properly defined set of terms would definitely answer that question. Addressing the question itself is outside the scope of *this* issue (but could be raised as a separate one).

**Comment by RieksJ** [comment]
@brentzundel, @msporny, @dlongley, @kdenhartog: can any of you create a label `terminology` and add that to (a) this issue, (b) other terminology-related issues, e.g., #989, #984, #957, #915, #912, #902, and (c) all issues that I will be creating for proposing improved definitions for terms, the title of which I intend to start with the text `[Terminology]`?.

What I will be trying to do is to make the definitions such that every first sentence is a criterion that we can use to determine whether or not something qualifies as an instance/example of the term.

**Comment by Sakurann** [comment]
There is an agreement in the WG that terminology needs to be revised - and now we have a termonology tag and number of issues focusing on specific terms. Please keep opening concrete issues with the terms that should be redefined, ideally with a proposal how to redefine. Closing this general issue as there is no action pending.
