### ISSUE TITLE
issuer IRI should be anchored to term definition, page should scroll to definition

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c/vc-data-model#990]
My understanding is the expected behavior for a JSON-LD term is for the url to be a reference to the definition of the value. When I looked at the n-quads for issuer, i found it references the following url: https://www.w3.org/2018/credentials#issuer. 

`_:b0 <https://www.w3.org/2018/credentials#issuer> <did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U> .`

This link lands on the page, but does not anchor to the definition for issuer included in the page. 

![image](https://user-images.githubusercontent.com/86194145/206272011-9230fbcf-9a9d-44dd-8181-49af94ffca6d.png)

**Comment by OR13** [comment]
seems like we just need to add an anchor tag to the html.

@iherman is this page automatically generated? where do I open a PR to fix this?

**Comment by iherman** [comment]
@OR13 this is related to issue #966. For the time being, the credential vocabulary redirects to v1, which indeed does not have those anchors. If #966 is "solved" (meaning I get an official green light from the WG to change the redirections to v2) then this will be solved automatically; indeed, v2 has all the right anchors. For info, here it is for `issuer`:

https://w3c.github.io/vc-data-model/vocab/credentials/v2/vocabulary.html#issuer

and this will work as @BenjaminMoe expects.

**Comment by OR13** [comment]
Related https://github.com/w3c/vc-data-model/issues/966

**Comment by iherman** [comment]
@BenjaminMoe with the recent change of the vocabulary presentation, this issue has become moot: the URL you refer to goes to the specification. If you are fine, can you close this issue?

**Comment by msporny** [comment]
This issue has been fixed, closing.
